### ISSUE TITLE
Certificate trust with intermediate certificates fails (Wrong # of certs)

### ISSUE THREAD

**Issue by joshsouza** [zrepl/zrepl#103]
## Expectation: 
Peer certificates signed by an intermediary CA, containing the full certificate chain should be accepted by other peers that are configured with the root CA's certificate as their CA cert.

## Actual experience: 
Peer certificates with a full cert chain (host + intermediate) fail with the error: `unexpected number of certificates presented by TLS client`

Likely caused by code in `tlsconf.go`: 
```
if len(peerCerts) != 1 {
```

## Workaround: 
Adding the intermediate certificates to the trusted CA cert on the peers (and removing the full chain from the peer cert) causes the certificates to validate properly.

## Problem: 
Intermediate certs may be revoked at any time, and there may potentially be different intermediaries validating for a single root CA, so this isn't sustainable as a workaround.

## Further commentary:
It's pretty common practice when putting an internal CA in place to utilize intermediate CA servers, signed by the root ca, and to distribute only the root ca certificate for validation, such that as long as the client provides their certificate chain, it can be validated. At this time, `zrepl` appears to expect only one certificate to be sent by peers, preventing this from operating as expected. I'm sure that there is a reason this limitation was put in place, but for our (and likely other future users) needs this should be adjusted to support intermediary certificates. (Note that I believe some organizations may make use of multiple layers of intermediaries as well)

**Comment by problame** [comment]
Sorry for the delayed response: 

> Adding the intermediate certificates to the trusted CA cert on the peers (and removing the full chain from the peer cert) causes the certificates to validate properly.

So you had the entire chain in the file referenced by `serve.ca`?

Have you tried removing the line in question? A PR is always welcome!
Sadly, it'll take a little while until I get time to address this issue.

**Comment by joshsouza** [comment]
No worries on the timing, we're all busy!

Yes, the `server.ca` contained both the root cert and intermediate cert (so the full chain short the actual client cert).

I haven't had the opportunity to get a proper Go build environment set up on my machine, so I haven't actually tried adjusting the code yet. Once I get some of the other pieces of the puzzle for how we're trying to implement this in place I'll loop back around to getting a PR for you. (Probably some time next week)
