### ISSUE TITLE
zrepl allow negative regex

### ISSUE THREAD

**Issue by MoritzFago** [zrepl/zrepl#113]
Currently you can't specify to keep all snapshots that don't match a regex, this would be very convientient, because it would free you from thinking about zrepl when doing unrelated snapshots.

**Comment by problame** [comment]
`5e1ea21f` implements this, should be in the [release candidates](https://github.com/zrepl/zrepl/releases/tag/0.1.0-rc3) and will be available in zrepl 0.1
