### ISSUE TITLE
DOCS - does second replication begin if first replication is not finished?

### ISSUE THREAD

**Issue by woodsb02** [zrepl/zrepl#12]
I believe the documentation should explain the zrepl behaviour for what happens if the first replication is not finished at the time that the second replication is called to begin. This needs to cover the pull, push and local scenarios.

This is likely to occur during the first replication of many Gigabytes of data, if the interval of the pull job set as 10m. The first replication would not be finished by the time the second one was called to start. Given that this will be occurring to new users, it is important they are clear on the behaviour they can expect during this first time use.

**Comment by problame** [comment]
fixed in a4963cecb7168d055b3e71c9a1c1e2d1d8f4b97f (*patient job* )
