### ISSUE TITLE
Integration into mac os homebrew

### ISSUE THREAD

**Issue by JMoVS** [zrepl/zrepl#120]
Now that I looked at it further, (I'm still gonna test it a bit more), I think I will try to work on getting zrepl taken up into the homebrew (brew.sh) package manager for Mac OS. I'm opening this issue so I can discuss issues that arise with the brew team for integration.

**Comment by JMoVS** [comment]
I had further looks into it and homebrew will require a couple of things:

1. Stable release (so something that is not tagged as "pre-release" like the current rc
2. I'll have to figure out how to manually download the dependencies and not rely on .lazy.sh to download them
3. Figure out then how the build process works inside the homebrew environment. I think the only dependencies I've seen so far are go and python

**Comment by JMoVS** [comment]
I've got a first version of the formula [to work ](https://github.com/JMoVS/homebrew-core/tree/add-zrepl), but it's right now stil very hacky.

Can we somehow get the go dependencies on its own for brew?

Like https://github.com/Homebrew/homebrew-core/blob/b825200fd1944c4c66c3173dabb52b33149c49aa/Formula/goofys.rb

**Comment by problame** [comment]
> Can we somehow get the go dependencies on its own for brew?

What do you mean by that? Just use the Gopkg.lock file for exact versions.
We'll switch to Go modules at some point (see #112 ), but at least for the next release, it'll still be https://github.com/golang/dep

**Comment by JMoVS** [comment]
Ok, one question: What would be a good and easy way to test that zrepl "works"? Do you have tests that I can trigger to run?

**Comment by JMoVS** [comment]
You can track the progress here: https://github.com/Homebrew/homebrew-core/pull/38935

**Comment by problame** [comment]
> Ok, one question: What would be a good and easy way to test that zrepl "works"? Do you have tests that I can trigger to run?

The only self-check we have ATM is `zrepl configcheck`.
`zrepl version --show client` can be used to show the client's version.

wrt version, in particular if there are any patches, make sure to review the package maintainer info in the README.md https://github.com/zrepl/zrepl/blob/master/README.md#package-maintainer-information

**Comment by JMoVS** [comment]
✅
