### ISSUE TITLE
not obvious how zrepl can be used without a prefix

### ISSUE THREAD

**Issue by JMoVS** [zrepl/zrepl#121]
I am currently wondering if zrepl can be used without a prefix for the snapshots as I don't see this case in the documentation and also get complaints from configcheck if I omit a prefix. Is this expected behaviour? (Mac OS Mojave)

**Comment by problame** [comment]
The test is for `prefix != ""`, which is primarily due to Go's default value for an uninitialized string being `""`.
But I don't really see why _not_ having a prefix would pose problems for anyone.

**Comment by JMoVS** [comment]
if I do not have a prefix, how would I have to modify the regex then?

**Comment by JMoVS** [comment]
also if I don't provide a prefix at all (so no prefix field present), I get:

`  line 19: field prefix is required but not given`

**Comment by problame** [comment]
> if I do not have a prefix, how would I have to modify the regex then?

If you want non-zrepl snapshots to be covered by zrepl pruning rules, something like `regex: ".*"` would cover any snapshot of the matches filesystems. Make sure this is actually what you want, though.

> also if I don't provide a prefix at all (so no prefix field present), I get:
> ` line 19: field prefix is required but not given`

Yeah, that's exactly the intended behavior: zrepl expects that users will want a prefix, because otherwise they'd have to match the date-format that zrepl appends to the prefix if they only want zrepl-created snapshots to be affected by zrepl pruning.

**Comment by JMoVS** [comment]
> > if I do not have a prefix, how would I have to modify the regex then?
> 
> If you want non-zrepl snapshots to be covered by zrepl pruning rules, something like `regex: ".*"` would cover any snapshot of the matches filesystems. Make sure this is actually what you want, though.
> 
> > also if I don't provide a prefix at all (so no prefix field present), I get:
> > ` line 19: field prefix is required but not given`
> 
> Yeah, that's exactly the intended behavior: zrepl expects that users will want a prefix, because otherwise they'd have to match the date-format that zrepl appends to the prefix if they only want zrepl-created snapshots to be affected by zrepl pruning.

Hmm, I see a reasoning there. ;-) For me, I have an existing system to check independently if whatever backup service I'm running (znapzend, zrepl, whatever) is **actually** doing backups (have been bitten by znapzend quite a few times - independent verification helps there). But I think I can include the prefix in there/could rework them (I hope). (https://github.com/JMoVS/ZFS-TimeMachine). Therefore I was asking if I could use it without prefix and maybe even configure the date format.
https://justinscholz.de/2018/06/15/an-extensive-zfs-setup-on-macos/

**Comment by problame** [comment]
Configurable snapshot suffix is pretty low on my priority list, but since zrepl treats snapshot names as opaque, this should be feasible. If it's important to you, please create an issue, will tag it as good-first-issue ;)

**Comment by JMoVS** [comment]
I'll see, I think I will update the regex of my checking scripts to match the zrepl format ;-) Anyway, I'll see, thx!
