### ISSUE TITLE
pruner exits on filesystem-local errors

### ISSUE THREAD

**Issue by problame** [zrepl/zrepl#123]
Original report in https://github.com/zrepl/zrepl/issues/70#issuecomment-466814052

> As of 0.1.0-rc3, in a pull-job, **the whole pruning phase fails** (for the remaining filesystems as well!), because zrepl can not get the replication cursor bookmark for the deleted filesystem. Left me with 25000 unpruned snapshots, until I found out.
> 
> In my specific case, I'm replicating my Proxmox VMs hard disks every 10 minutes. Each VM hard disk is a zvol and therefore a separate dataset. Removing a VM and it's hard disk in Proxmox eliminates the dataset, including snapshots and bookmarks. Consequently, zrepl runs into trouble, because it can't find the cursor bookmark anymore - and aborts the whole pruning process with a PermErr.
> 
> In my case, I would expect the existing snapshots to remain on the receiver side and to be pruned according to the pruning sieves. That would leave me with some backups until the period defined in the last pruning sieve.

I think I spotted a similar issue on my test setup: https://github.com/zrepl/zrepl/pull/111#issuecomment-458074582

**Comment by jbliesener** [comment]
Sounds like it's the same. However, seeing something else here: 

![image](https://user-images.githubusercontent.com/5624993/53305696-6e99c600-3863-11e9-97fc-d0835f7e23aa.png)

Can you see that zpool/pve/vm-101-disk-1 is missing on the list of datasets pruned on the receiver side? I'll investigate this further.

**Comment by problame** [comment]
Non-exhaustive list of errors that should not cause the pruner to stop:

* replication cursor missing
* a single destroy failing
* < N destroy failing (if >= N destroys fail we should assume permission error / screen scrape ZFS)
* connection dying (remote prunes)

Basically the same ones as for replication.

Originally, I wanted to defer this to 0.2, but maybe we can integrate the pruning into the new ( WIP https://github.com/zrepl/zrepl/tree/problame/replication_refactor ) replication driver logic, which will have proper retry behavior for both FS-local and global (connectivity-related) errors.

**Comment by problame** [comment]
> Can you see that zpool/pve/vm-101-disk-1 is missing on the list of datasets pruned on the receiver side? I'll investigate this further.

I do, but I do not understand why there is no  `ErrPerm`. Did you fix that manually in the meantime?

**Comment by jbliesener** [comment]
No, still looking into it. vm-101-disk-1 exists on sender and receiver, is replicated and pruned on the sender's side. It's just missing from the datasets pruned on the receiver side. I'll look into it after the current prune job finishes (will take some more time).

**Comment by jbliesener** [comment]
Well, it looks like this may be a monitoring screen issue? When comparing a `zfs list` from half an hour ago with a fresh one, I see that vm-101-disk-1 acutally seems to be pruned. At least its releasing a lot of disk space. It just doesn't show up in the monitor screen:

![image](https://user-images.githubusercontent.com/5624993/53305949-3778e400-3866-11e9-8cc6-55fd737ad8e2.png)

**Comment by jbliesener** [comment]
Monitor screen issue. After completing vm-101-disk-1, it printed the "Completed" message over the existing "vm-110-disk-1 ... Pending" line. Want me to raise a separate the issue on this one? 

![image](https://user-images.githubusercontent.com/5624993/53306030-149aff80-3867-11e9-8c48-ee0f9f74fc1c.png)

**Comment by problame** [comment]
Could you post a screenshot of that 'over-drawing' state?
In any way, probably an off-by-one in the terminal-drawing code.
Please open a separate issue, can't promise to address this in 0.1, though (I want to get that thing out the door, finally ;) ).
In case you want to look into it: check out `client/status.go`.
The status drawing code is ~~rather messy~~ quick hack, any improvements appreciated.

**Comment by jbliesener** [comment]
Created #124, this should not delay any release version. Thank you, Christian.

**Comment by problame** [comment]
Awaiting feedback in #139
