### ISSUE TITLE
Status screen overwriting lines

### ISSUE THREAD

**Issue by jbliesener** [zrepl/zrepl#124]
The status monitor seems to overwrite lines. Here's a screenshot of the pruning process. Note that the sender prune shows four vm-1??-disk-1 items, while the receiver pruning process shows only three:

![mobaxterm_2019-02-24_18-37-51](https://user-images.githubusercontent.com/5624993/53306291-0e5a5280-386a-11e9-885c-2537dda53807.png)

When the current pruning step completes, one of the lines is overwritten (note that the middle line was "vm-110-disk-1 Pending" and now is "vm-101-disk-1 Completed":

![mobaxterm_2019-02-24_19-04-35](https://user-images.githubusercontent.com/5624993/53306295-1b774180-386a-11e9-8391-5f3f15a0701c.png)

Issue continues after finishing vm-110-disk-1, overwrites the vm-111-disk-1 line. Also - this is interesting -  the progress bar advances to 100%, although vm-111-disk-1 is still being pruned:

![image](https://user-images.githubusercontent.com/5624993/53306436-cb00e380-386b-11e9-871c-2a70cd120e3b.png)

![image](https://user-images.githubusercontent.com/5624993/53306450-ef5cc000-386b-11e9-9e5d-4dc60dbe5443.png)

When the process terminates, the last line is NOT overwritten.

**Comment by problame** [comment]
We since rewrote the status UI in a58ce74ed0c804651a6bb2c49bcb3fda68f2c0b5
