### ISSUE TITLE
Multiple mentions of a global configuration file links broken

### ISSUE THREAD

**Issue by JMoVS** [zrepl/zrepl#127]
In the documentation, there are mutliple mentions of the global configuration file linking to https://zrepl.github.io/installation.html#mainconfigfile - where there is no mention of this.

Is this the general config file that also configures the backup jobs?

**Comment by problame** [comment]
No, there is only one config file `/etc/zrepl/zrepl.yml` or `/usr/local/etc/zrepl.yml` or `--config whatever.yml`.

I guess these are oversights of 1643198713aa9e7763b057111da417808e1352ea :
Any invocation of the `|mainconfig|` Sphinx macro should be replaced by `/etc/zrepl/zrepl.yml` or similar. No more mention of main config file.

IIRC you were working on docs anyway, could you fix this (in a separate commit, same PR is fine as long as the commit contains `refs #127`)?
