### ISSUE TITLE
DOCS - describe "interval" and "grid" parameters

### ISSUE THREAD

**Issue by woodsb02** [zrepl/zrepl#13]
I was initially confused between the interaction between the "interval" parameters and the "grid" pruning parameters. I think I won't be the only one asking these questions, so it should be added to your documentation site. Some questions I had:
- What happens if I define an source interval of 10m, a source grid with 4x15m, and a pull grid with 3x20m?
- What is the difference between the source interval and pull interval? What happens if the source interval is different from the pull interval? I assume it would be normal to have the source interval quite frequent (e.g. 10m), and much less frequent on the pull job (e.g. 24h)?
- For the grid parameters, what is the difference between 1x24d vs 24x1d
- What does the (keep=all) setting do in the grid parameter?
- For the interval parameter, I don't seem to be able to set "1d"?

**Comment by problame** [comment]
Do you think the changes in `ea6f023` are enough of an explanation? I have some visualizations in the talk from the dev summit (https://docs.google.com/presentation/d/1EmmeEvOXAWJHCVnOS9-TTsxswbcGKmeLWdY_6BH4w0Q/edit?usp=sharing) but am not sure whether it is wise to include pixel graphics in the source tree.

**Comment by woodsb02** [comment]
Nice explanation! I think that nicely answers bullets 1, 3 & 4. I get it the grid now!

But I think bullets 2 & 5 also require documenting?

I actually still don’t understand if I should set the interval on the backup-srv to 10m or 1d... because I am guessing a bit at how the setting behaves on the backup-srv, and also because I don’t want to have the second pull start before the first is finished.

**Comment by problame** [comment]
So depending on the job type, the interval means different things (like what happens after each interval). I'm currently writing the docs for job types, where this stuff is answered.

I was hoping that this was clarified in this line... https://github.com/zrepl/zrepl/blame/ea6f02368b95c262a55b6e94450838bc3a03da9a/docs/content/configuration/prune.md#L11

**Comment by woodsb02** [comment]
That line certainly helps, but the jobs documentation will be the final fix which allows the user to understand how all of these timing parameters interact and work in different contexts.

**Comment by problame** [comment]
Is the job documentation added in a4963ce a sufficient answer to bullet 2?

**Comment by problame** [comment]
Regarding bullet 5, this moved to a separate issue.

**Comment by woodsb02** [comment]
Love this documentation - it is well written and easily understood. Thanks!
