### ISSUE TITLE
MacOS: /var/run/zrepl directory doesn't survive reboots

### ISSUE THREAD

**Issue by JMoVS** [zrepl/zrepl#130]
It looks to me like the /var/run/zrepl directory doesn't properly survive a reboot (on every reboot, it's gone...) and one needs admin-rights to create it. I think a wiser choice, especially if later integrated with homebrew would be to use some directory in /usr/local for this. Is this directory configurable currently?

**Comment by problame** [comment]
https://zrepl.github.io/configuration/misc.html

Currently, zrepl is *documented* to be always run as root. Non-root sinks are possible if the OS supports delegation, but not documented yet.

On Linux and FreeBSD, the init systems / rc scripts. take care of creating the tempdir. (Linux systemd tempfiles, need to push that systemd unit definition ref #117  ).

AFAIK, OS X has launchd, and I guess there is a mechanism to run a pre-start command in launchd.

My stance on the whole runtime directory is that it's the job of the init system / service manager to set up as documented in the link above.

We could discuss different default paths for OS X, though.

**Comment by JMoVS** [comment]
Yes, OS X has launchd which I sometimes used in the past as well, I got it to (begrudingly) create the folder as well but zrepl is now complaining that the folder *must not be* world-accessible, whereas launchd creates it with 0744 permissions. AFAIK, there is no designed-for way to run a command pre full-command but to use bash to run both commands, which is a bit hackey.

I do get it to create the directory as "working directory" and redirect standard out and standard error into log-files there.

http://www.launchd.info/

**Comment by JMoVS** [comment]
I think similar to znapzend installed via homebrew on MacOS (homebrew would likely be the most prominent way of installing zrepl), I think it'd be nice to also go with thr `/usr/local/var/run/zrepl` path as an option for Mac OS

**Comment by JMoVS** [comment]
I think that's best addresses by providing a default configuration file that uses the different folder
