### ISSUE TITLE
repl: replication cursors per destination

### ISSUE THREAD

**Issue by problame** [zrepl/zrepl#154]
Currently, we have a single replication cursor per filesystem.
As documented in https://github.com/zrepl/zrepl/pull/153/commits/c2b05954e971e262b76b4bb3b22d182a99355e67 (docs -> jobs -> multi machine & more than 2 machines), this prohibits replicating the filesystem to multiple destinations because the jobs would use the same replication cursor.

We should have a cursor per receiver, i.e. per remote zrepl job.
We have client identities and job names, but those can be changed by the user in the config, and the effects of renaming the job are not obvious. Further, including the GUID in the config is not an option because users tend to copy-paste configs (and thus also the GUIDs, which wouln't be so unique then).

The idea is the follwing:

* Introduce a GUID per zrepl instance (e.g. /var/lib/zrepl/instance-id)
* Introduce a GUID per zrepl job
  * `/var/lib/zrepl/job-ids/job-name'
  * By default, a job doesn't have a GUID. Users have to run `zrepl config guid create JOBNAME` to create one, and `zrepl config guid rename OLDJOBNAME NEWJOBNAME` to change a job's name.
  * Jobs that do not find their GUID should fail to start. `zrepl configcheck` should fail as well, but parsing the config should work.
* When connecting to a remote host / job, get the remote job's GUID and use it for the replication cursor.
* Sinks use `${root_fs}/${sender_job_id}` instead of `${root_fs}/${client_identity}`
  * Migration tool necessary?
  * Usability: dataset names become ugly. And we don't have symlinks. Ideas?
* Collisions are very unlikely, and if they occur, the consequences are fairly minor because only the bookmark name is affected.

**FAQ**

* Why not GUID per client-identity instead of per job?
  * Because a client identity can be used by multiple jobs, and is generally variable if the transport configuration changes (that is a whole other problem of the client identity model).
  * We should likely change sinks to use `${root_fs}/${sender_job_id}`.

**Comment by JMoVS** [comment]
why should this be per job and not per client-identity?

**Comment by problame** [comment]
I added the FAQ entry, see above ;)

**Comment by JMoVS** [comment]
if we change it to per job-id, I think we at that point should either put it in 0.1 or offer a transition tool,  but in general, FAQ clears it up ;-)

**Comment by problame** [comment]
We implemented replication cursors and last-received-holds in zrepl 0.3 We use the config's job-id, not GUIDs, which is suboptimal but was more straight forward at the time.
