### ISSUE TITLE
config supposedly has overlapping root_fs

### ISSUE THREAD

**Issue by JMoVS** [zrepl/zrepl#160]
Hi,

I'm testing out rc4 but I don't see where in my config I have overlapping root fs-es:

```
global:
      logging:
       - type: "stdout"
         level: "error"
         format: "human"
      control:
        sockpath: /usr/local/var/run/zrepl/control
      serve:
        stdinserver:
          sockdir: /usr/local/var/run/zrepl/stdinserver
jobs:
  - type: sink
    name: "local_sink"
    root_fs: "zfssnaps/encRoot"
    serve:
      type: local
      listener_name: localsink

  - type: push
    name: "backup_system"
    connect:
      type: local
      listener_name: localsink
      client_identity: SergeantPepperSenior
    filesystems: {
      "ocean<": true,
      "ocean/Users/justin/Library/ApplicationSupport/MobileSync": false,
      "zweischock/temp<": true
    }
...
```

these are the only 2 jobs I have

**Comment by problame** [comment]
Commit https://github.com/zrepl/zrepl/commit/7a7b00a0c96cffab210062c358fc344435f0c58c contains the fix (see above). You can use the binary builds from the CI to check that it works. Note that the commit is based on the cleanup branch, which contains a lot of changes: those changes are mostly formatting fixes and some minor error handling mistakes discovered by linters. Note that the now correctly handled error conditions were unlikely to be triggered, and thus should not be noticable for you. (see #159 for the branch that above commit is based on).

**Comment by JMoVS** [comment]
ok, I just tried the cleanup branch and the issue is gone. 👏🏼
