### ISSUE TITLE
number of concurrent zfs dry send invocations is unbounded

### ISSUE THREAD

**Issue by problame** [zrepl/zrepl#161]
Hi, I was testing the above snapshot last week (freebsd) and it indeed solves a lot of problems that we had with a previous version (no more checksum errors after a few GB). But after a manual `zrepl signal wakeup` of a push job, I saw dozens (?) of `zfs send` jobs showing up in `htop` at the same time driving up the load and eventually crashing the server. Is this a deliberate behaviour that it starts so many sends at once?

_Originally posted by @Debilski in https://github.com/zrepl/zrepl/pull/139#issuecomment-476162102_

**Comment by problame** [comment]
Do you have multiple sending jobs on the system where you observed the concurrent `zfs send` processes?
Could you please post configuration on both sides?

**Comment by Debilski** [comment]
No problem, here is the config for the data server that crashed,

    jobs:
    - name: prod_to_backups
      type: push
      connect:
        type: tls
        address: "172.29.8.101:8888"
        ca: /usr/local/etc/zrepl/backups.crt
        cert: /usr/local/etc/zrepl/data.crt
        key:  /usr/local/etc/zrepl/data.key
        server_cn: "backups"
      filesystems: {
        "MAIN/data1<": true,
        "MAIN/data2<": true,
      }
      snapshotting:
        type: periodic
        prefix: zrepl_
        interval: 240m
      pruning:
        keep_sender:
        - type: not_replicated
        - type: last_n
          count: 100
        # keep all snapshots that were not created by zrepl
        - type: regex
          regex: "^(hourly|daily|weekly|monthly|postinst|manual).*"
        keep_receiver:
        - type: grid
          grid: 1x1h(keep=all) | 24x1h | 30x1d | 6x30d
          regex: "^zrepl_"

And here for the backup system.

    jobs:
    - name: sink
      type: sink
      serve:
        type: tls
        listen: ":8888"
        ca: "/usr/local/etc/zrepl/data.crt"
        cert: "/usr/local/etc/zrepl/backups.crt"
        key: "/usr/local/etc/zrepl/backups.key"
        client_cns:
          - "data"
      root_fs: "STORE/zrepl/pull"

I am currently trying to replicate it on another server. I am not sure, I am allowed to use the new snapshot on the original server at this time, just to find out if it crashes again. :)

My situation was, that I just had a full replication of a few TB finished, so zrepl was busy doing that for a day or so and did not do send any other full or incremental snapshots for the other defined sub zfilesystems. After the full replication had finished, I restarted zrepl (to make sure it did not get stuck in the next TB full replication but to have it do a few incremental backups before that) only to have the system freeze completely after 30 seconds or so.

**Comment by Debilski** [comment]
Hi, I don’t see where I can download the newest version (or do I have to compile it myself)? With the older rc, I get the following when I run `dtrace` (I don’t have much experience with dtrace though).

    $ dtrace -n 'proc:::exec-success { printf("%Y", walltimestamp); trace(curpsinfo->pr_psargs); }'


    4  67642                none:exec-success 2019 Mar 26 15:19:07  zrepl signal wakeup prod_to_backups
    0  67642                none:exec-success 2019 Mar 26 15:19:07  zfs list -H -p -o name -r -t filesystem,volume
    0  67642                none:exec-success 2019 Mar 26 15:19:09  zfs list -H -p -o name,guid,createtxg,creation -r-d 1 -t bookmark,snapshot -s createtxg data1/backups/b01
    3  67642                none:exec-success 2019 Mar 26 15:19:09  zfs list -H -p -o name,guid,createtxg,creation -r-d 1 -t bookmark,snapshot -s createtxg data1/backups/b02
    4  67642                none:exec-success 2019 Mar 26 15:19:09  zfs list -H -p -o name,guid,createtxg,creation -r-d 1 -t bookmark,snapshot -s createtxg data1/backups
    3  67642                none:exec-success 2019 Mar 26 15:19:09  zfs list -H -p -o name,guid,createtxg,creation -r-d 1 -t bookmark,snapshot -s createtxg data1/backups/b03
    4  67642                none:exec-success 2019 Mar 26 15:19:09  zfs list -H -p -o name,guid,createtxg,creation -r-d 1 -t bookmark,snapshot -s createtxg data1/other
    5  67642                none:exec-success 2019 Mar 26 15:19:10  zfs send -n -v -P -i data1/backups/b01@zrepl_20190326_113002_000 data1/backups/b01@zrepl_20190326_115002_000
    2  67642                none:exec-success 2019 Mar 26 15:19:10  zfs send -n -v -P -i data1/backups/b01@zrepl_20190326_131003_000 data1/backups/b01@zrepl_20190326_133002_000
    0  67642                none:exec-success 2019 Mar 26 15:19:10  zfs send -n -v -P -i data1/backups/b01@zrepl_20190326_121003_000 data1/backups/b01@zrepl_20190326_123003_000
    7  67642                none:exec-success 2019 Mar 26 15:19:10  zfs send -n -v -P -i data1/backups/b01@zrepl_20190326_123003_000 data1/backups/b01@zrepl_20190326_125002_000
    6  67642                none:exec-success 2019 Mar 26 15:19:10  zfs send -n -v -P -i data1/backups/b01@zrepl_20190326_125002_000 data1/backups/b01@zrepl_20190326_131003_000
    1  67642                none:exec-success 2019 Mar 26 15:19:10  zfs send -n -v -P -i data1/backups/b01@zrepl_20190326_111002_000 data1/backups/b01@zrepl_20190326_113002_000
    2  67642                none:exec-success 2019 Mar 26 15:19:10  zfs send -n -v -P -i data1/backups/b01@zrepl_20190326_115002_000 data1/backups/b01@zrepl_20190326_121003_000
    7  67642                none:exec-success 2019 Mar 26 15:19:10  zfs send -n -v -P -i data1/backups/b01@zrepl_20190326_135003_000 data1/backups/b01@zrepl_20190326_141003_000
    3  67642                none:exec-success 2019 Mar 26 15:19:10  zfs send -n -v -P -i data1/backups/b01@zrepl_20190326_133002_000 data1/backups/b01@zrepl_20190326_135003_000
    1  67642                none:exec-success 2019 Mar 26 15:19:10  zfs send -n -v -P -i data1/backups/b02@zrepl_20190326_135002_000 data1/backups/b02@zrepl_20190326_141003_000              
    6  67642                none:exec-success 2019 Mar 26 15:19:10  zfs send -n -v -P -i data1/backups/b02@zrepl_20190326_113003_000 data1/backups/b02@zrepl_20190326_115003_000     
    2  67642                none:exec-success 2019 Mar 26 15:19:10  zfs send -n -v -P -i data1/backups/b02@zrepl_20190326_111003_000 data1/backups/b02@zrepl_20190326_113003_000
    6  67642                none:exec-success 2019 Mar 26 15:19:10  zfs send -n -v -P -i data1/backups/b02@zrepl_20190326_121002_000 data1/backups/b02@zrepl_20190326_123003_000
    3  67642                none:exec-success 2019 Mar 26 15:19:10  zfs send -n -v -P -i data1/backups/b02@zrepl_20190326_131002_000 data1/backups/b02@zrepl_20190326_133003_000              
    1  67642                none:exec-success 2019 Mar 26 15:19:10  zfs send -n -v -P -i data1/backups/b02@zrepl_20190326_115003_000 data1/backups/b02@zrepl_20190326_121002_000     
    5  67642                none:exec-success 2019 Mar 26 15:19:10  zfs send -n -v -P -i data1/backups/b02@zrepl_20190326_125003_000 data1/backups/b02@zrepl_20190326_131002_000
    6  67642                none:exec-success 2019 Mar 26 15:19:10  zfs send -n -v -P -i data1/backups/b02@zrepl_20190326_123003_000 data1/backups/b02@zrepl_20190326_125003_000
    3  67642                none:exec-success 2019 Mar 26 15:19:10  zfs send -n -v -P -i data1/backups/b02@zrepl_20190326_133003_000 data1/backups/b02@zrepl_20190326_135002_000
    5  67642                none:exec-success 2019 Mar 26 15:19:10  zfs send -n -v -P -i data1/backups/b01@zrepl_20190326_111002_000 data1/backups/b01@zrepl_20190326_113002_000
    4  67642                none:exec-success 2019 Mar 26 15:19:10  zfs send -i data1/backups/b01@zrepl_20190326_111002_000 data1/backups/b01@zrepl_20190326_113002_000
    1  67642                none:exec-success 2019 Mar 26 15:19:10  zfs send -n -v -P -i data1/backups@zrepl_20190326_111002_000 data1/backups@zrepl_20190326_113002_000
    5  67642                none:exec-success 2019 Mar 26 15:19:10  zfs send -n -v -P -i data1/backups@zrepl_20190326_135003_000 data1/backups@zrepl_20190326_141002_000
    7  67642                none:exec-success 2019 Mar 26 15:19:10  zfs send -n -v -P -i data1/backups@zrepl_20190326_131003_000 data1/backups@zrepl_20190326_133002_000
    2  67642                none:exec-success 2019 Mar 26 15:19:10  zfs send -n -v -P -i data1/backups@zrepl_20190326_115003_000 data1/backups@zrepl_20190326_121003_000
    3  67642                none:exec-success 2019 Mar 26 15:19:10  zfs send -n -v -P -i data1/backups@zrepl_20190326_113002_000 data1/backups@zrepl_20190326_115003_000
    4  67642                none:exec-success 2019 Mar 26 15:19:10  zfs send -n -v -P -i data1/backups@zrepl_20190326_121003_000 data1/backups@zrepl_20190326_123002_000
    5  67642                none:exec-success 2019 Mar 26 15:19:10  zfs send -n -v -P -i data1/backups@zrepl_20190326_125002_000 data1/backups@zrepl_20190326_131003_000
    3  67642                none:exec-success 2019 Mar 26 15:19:10  zfs send -n -v -P -i data1/backups@zrepl_20190326_123002_000 data1/backups@zrepl_20190326_125002_000
    0  67642                none:exec-success 2019 Mar 26 15:19:10  zfs send -n -v -P -i data1/backups@zrepl_20190326_133002_000 data1/backups@zrepl_20190326_135003_000
    0  67642                none:exec-success 2019 Mar 26 15:19:10  zfs send -n -v -P -i data1/backups/b03@zrepl_20190326_113003_000 data1/backups/b03@zrepl_20190326_115002_000
    6  67642                none:exec-success 2019 Mar 26 15:19:10  zfs send -n -v -P -i data1/backups/b03@zrepl_20190326_135003_000 data1/backups/b03@zrepl_20190326_141003_000
    7  67642                none:exec-success 2019 Mar 26 15:19:10  zfs send -n -v -P -i data1/backups/b03@zrepl_20190326_115002_000 data1/backups/b03@zrepl_20190326_121002_000
    1  67642                none:exec-success 2019 Mar 26 15:19:10  zfs send -n -v -P -i data1/backups/b03@zrepl_20190326_125003_000 data1/backups/b03@zrepl_20190326_131002_000
    2  67642                none:exec-success 2019 Mar 26 15:19:10  zfs send -n -v -P -i data1/other@zrepl_20190326_113003_000 data1/other@zrepl_20190326_115003_000
    4  67642                none:exec-success 2019 Mar 26 15:19:10  zfs send -n -v -P -i data1/other@zrepl_20190326_135002_000 data1/other@zrepl_20190326_141003_000
    5  67642                none:exec-success 2019 Mar 26 15:19:10  zfs send -n -v -P -i data1/other@zrepl_20190326_115003_000 data1/other@zrepl_20190326_121003_000
    3  67642                none:exec-success 2019 Mar 26 15:19:10  zfs send -n -v -P -i data1/other@zrepl_20190326_121003_000 data1/other@zrepl_20190326_123002_000

the list goes on for a little while. I am not sure here if zfs is just super fast or if the jobs are indeed running at the same time.

**Comment by problame** [comment]
> Hi, I don’t see where I can download the newest version (or do I have to compile it myself)? 
In the artifacts tab, navigate to `/go/src/github.com/zrepl/zrepl/artifacts/release` and pick the binary for your platform. Go binaries are statically linked, hence just copy the binary to /usr/local/bin or sth.

The dtrace output seems fine: it's all incremental steps, don't think they are running in parallel.

I'll try to replicate your problem, but please try the binary builds from the CI and report back.

**Comment by Debilski** [comment]
> I'll try to replicate your problem, but please try the binary builds from the CI and report back.

I would. But I don’t find them. 😐

**Comment by problame** [comment]
> > Hi, I don’t see where I can download the newest version (or do I have to compile it myself)?
> 
> In the artifacts tab, navigate to `/go/src/github.com/zrepl/zrepl/artifacts/release` and pick the binary for your platform. Go binaries are statically linked, hence just copy the binary to /usr/local/bin or sth.

(Sry for the initial formatting, editing things to clarify this was my response to your problem)

**Comment by problame** [comment]
>  But after a manual zrepl signal wakeup of a push job, I saw dozens (?) of zfs send jobs showing up in htop at the same time driving up the load and eventually crashing the server. 

Ah, how many datasets are you replicating?
The `zfs send -n` commands are used to estimated the send size (-n is a dry run), and is run in parallel per FS.
I suppose I could limit the number of concurrent `zfs send -n` (it is always limited to 1 for `zfs send` ATM, but even this will change once we land #140 ).

**Comment by Debilski** [comment]
> > > Hi, I don’t see where I can download the newest version (or do I have to compile it myself)?
> > 
> > 
> > In the artifacts tab, navigate to `/go/src/github.com/zrepl/zrepl/artifacts/release` and pick the binary for your platform. Go binaries are statically linked, hence just copy the binary to /usr/local/bin or sth.
> 
> (Sry for the initial formatting, editing things to clarify this was my response to your problem)

Ah, now I got it. I needed to make an account on CircleCI. Hopefully I will have time to test it more thoroughly tomorrow.

**Comment by problame** [comment]
Do you have a number of concurrent `zfs send -n` processes that you'd find acceptable on your system?
I really have no idea what a good value is, because it depends on the system configuration, IO & CPU budgets for replication, etc.

**Comment by problame** [comment]
@Debilski please try the build in #167 
In addition to CircleCI, we now publish CI artifacts for public download: See the `zrepl/publish-ci-artifacts` GitHub Commit status in the PR.

**Comment by Debilski** [comment]
So far I couldn’t replicate the problem with the newer build; but since I’m not really sure what the original problem was, it could also be that it is only becoming critical after some days of running when a certain amount of snapshots have accumulated. I will have an eye on it.

**Comment by Debilski** [comment]
Just had another crash again after it had finished the initial replication (with an error message for the base folder but otherwise complete for all 200+ child zfs) with the build from #167 and I switched over to the new version from #162. The only thing I saw was that in prometheus I had a log activity of 19000 and 4065 goroutines just before the crash. I could watch `zrepl status` sync a few filesystems for a minute or two (each zfs had 45 or so snapshots to sync) and then it froze.

**Comment by problame** [comment]
> Just had another crash again
> ...
> and then it froze.

Could you please be more specific about what froze and what crashed here?

Did the OS / your SSH session freeze?
The barrier implemented in #167 was meant to limit the number of zfs processes to 4, given you have exactly 2 jobs configured in your deployment.
This artificial limitation was meant to solve the system overload / IO thrashing problem you encountered.

Or did the zrepl status command output freeze?
see #119 for that

Either way, the log output would probably be most valuable. Should be in `/var/log/messages` on FreeBSD.

**Comment by Debilski** [comment]
The complete OS froze and it was impossible to interact either via ssh or virtual console (server is not on-location). I didn’t wait indefinitely long before rebooting, though. I think I’m really going to setup up a 50*200 snapshots mirror system on-location that I can more easily test.

Here is what I see in `/var/log/messages` (Not 100% sure if the i/o timeouts are from before or after the `zrepl wakeup`).

    Apr  4 20:30:00 dataserver zrepl[20839]: 2019-04-04T20:30:00+02:00 [ERRO][_control]: control handler io error err="write unix /var/run/zrepl/control->: i/o timeout"
    Apr  4 20:30:02 dataserver zrepl[20839]: 2019-04-04T20:30:02+02:00 [ERRO][_control]: control handler io error err="write unix /var/run/zrepl/control->: i/o timeout"
    Apr  4 20:30:05 dataserver zrepl[20839]: 2019-04-04T20:30:05+02:00 [ERRO][_control]: control handler io error err="write unix /var/run/zrepl/control->: i/o timeout"
    Apr  4 20:30:08 dataserver zrepl[20839]: 2019-04-04T20:30:08+02:00 [ERRO][_control]: control handler io error err="write unix /var/run/zrepl/control->: i/o timeout"
    Apr  4 20:30:09 dataserver zrepl[20839]: 2019-04-04T20:30:09+02:00 [ERRO][_control]: control handler io error err="write unix /var/run/zrepl/control->: i/o timeout"
    Apr  4 20:30:31 dataserver kernel: swap_pager: indefinite wait buffer: bufobj: 0, blkno: 772077, size: 4096
    Apr  4 20:37:51 dataserver syslogd: kernel boot file is /boot/kernel/kernel
    Apr  4 20:37:51 dataserver kernel: ---<<BOOT>>---

**Comment by problame** [comment]
So, have a look at 32dd456ac6e30a96701154ca146b2f06a2402dfd

You can set environment variables

* `ZREPL_ENDPOINT_MAX_CONCURRENT_SEND=1`
* `ZREPL_ENDPOINT_MAX_CONCURRENT_RECV=1`
* `ZREPL_REPLICATION_MAX_CONCURRENT_SIZE_ESTIMATE=1`

On the sides where this makes sense, or just on both sides.
I guess you'll have to fiddle with the rc script on FreeBSD, maybe @woodsb02 is willing to help out / make that generally easier.

Does setting these variables help?

**Comment by Debilski** [comment]
Thanks for the updates. The environment variables certainly have an effect but I couldn’t yet test them on the problematic server. (Likely not going to happen this week either.)

However, looking more at the code and doing a bit of my own debugging (not much experience with go, so I am not sure if this is relevant at all), I figure that the `zfs list` is called concurrently in https://github.com/zrepl/zrepl/blob/32dd456ac6e30a96701154ca146b2f06a2402dfd/zfs/mapping.go#L62 right?

Could it be possible that this stalls the system, if it tries to run 200 `zfs list` at the same time? I am still trying to replicate it with a test system but the caching seems to be more performant on that system and I’m not seeing much currently. It’s only a wild guess, of course.

**Comment by problame** [comment]
You are a bit too deep in the call stack:

https://github.com/zrepl/zrepl/blob/000d8bba6656e19ed00f57b9c3d2b1b9baf3f757/replication/logic/replication_logic.go#L274

is not bound by the semaphore that we used for the size estimate in

https://github.com/zrepl/zrepl/blob/000d8bba6656e19ed00f57b9c3d2b1b9baf3f757/replication/logic/replication_logic.go#L349

**Comment by Debilski** [comment]
Ah, yeah, I noticed that too at some point. So as an update from my side on this issue: We have experienced the swap_pager error in another circumstance now, unrelated to zrepl, and are now in the process of upgrading the hardware (maybe it is simply a failure on the swap drive), which may or may not fix the problem for us. We’ll start more zrepl tests once the new hardware has arrived.

**Comment by problame** [comment]
https://github.com/zrepl/zrepl/pull/259/commits/6e33d848a9bc3ccb7baadfaeedaa31d1fcbec86e in https://github.com/zrepl/zrepl/pull/259 binds the `ListFilesystemVersions` to the step queue, you might want to give that specific patch, the PR, or the to-be-released 0.3 a shot.
Please report back any other parallel-replication related issues, we're planning to add knobs for parallel replication in one of the next releases!

**Comment by problame** [comment]
zrepl 0.3 has been released and includes the aforementioned patch.
