### ISSUE TITLE
FreeBSD Port out of date

### ISSUE THREAD

**Issue by ole-db** [zrepl/zrepl#172]
Hi,

the Port is still on v0.0.3. https://svnweb.freebsd.org/ports/head/sysutils/zrepl/
Please update the FreeBSD Port to v0.1.1

Thanks

**Comment by Cka3o4Huk** [comment]
I really want to port it, but has lack of go-based porting. Working on it.

**Comment by problame** [comment]
@woodsb02 is the port maintainer, he is aware of the update.

**Comment by Cka3o4Huk** [comment]
@problame , @woodsb02 
I have working version of port, but question is upgrade. Is there any automatic upgrade process from version 0.0.3 to version 0.1.1?

**Comment by Cka3o4Huk** [comment]
By the way, here is link to port update: 
https://github.com/Cka3o4Huk/fbsd-ports-addons/commit/9c76ecc57abbbb1f9e375946e13add34b793cfda

**Comment by problame** [comment]
There is a migration command for the placeholder property, search `[MIGRATION]` in the [Changelog](https://zrepl.github.io/changelog.html).
This should probably be in the UPDATING / pkg-message.

There is no automatic config-rewriting, and the migration command only works with the new config format, thus it's not possible to have some post-install hook (which as a user, I also wouldn't want to exist in the first place).

**Comment by Cka3o4Huk** [comment]
@problame , 

I will appreciate if you can provide appropriate wording for UPDATING & pkg-message, because I'm newbie to zrepl. :) I or woodsb02 will commit update.

Thanks!

**Comment by problame** [comment]
I think the current pkg-message is ok, it seems to be a copy & paste of the changelog's first paragraph.
I'd also mention the migration command for the placeholder property:

    The `zrepl:placeholder` property now uses on|off as values instead of hashes of the dataset path.
    This permits renames of the sink filesystem without updating all placeholder properties.
    If you update from 0.0.3, make sure your config is valid using `zrepl configcheck`,
    then run `zrepl migrate 0.0.X:0.1:placeholder`.

I would also recommend dropping a link to the changelog + a strong recommendation to read it completely. Either use the spinx-rendered file in the port workdir or the web-version ( https://zrepl.github.io/v0.1.1/changelog.html ) (no guarantee on the stability of that link).

**Comment by Cka3o4Huk** [comment]
For reference: 
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=237667
https://reviews.freebsd.org/D20095

**Comment by dpetrov67** [comment]
See this also:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=229445

**Comment by problame** [comment]
The Phabricator review was closed & merged.
