### ISSUE TITLE
arm64 build support

### ISSUE THREAD

**Issue by hydro-b** [zrepl/zrepl#180]
There is no arm64 build (GOARCH=arm64) in the build.Dockerfile / Makefile as of yet. I hacked these files (attached as zip
[arm64_build.zip](https://github.com/zrepl/zrepl/files/3244569/arm64_build.zip)
) to build _just_ that on a arm64 pine64 SBC.

The amd64 builds fail, obviously, on arm64. It would be nice if discovery of arch would be done automatically, and the variables changed accordingly: i.e. only build arm64 on arm64. Nowadays there is docker cross build support, so you might even be able to builld arm64 on x86_64 for example.

**Comment by problame** [comment]
Would you please convert your modifications to the Dockerfile / Makefile into a pull request?

**Comment by hydro-b** [comment]
Sure, will do as soon as I have some spare time to make a proper PR.
