### ISSUE TITLE
Build fails on FreeBSD i386 - rpc/dataconn/timeoutconn/timeoutconn.go

### ISSUE THREAD

**Issue by woodsb02** [zrepl/zrepl#184]
zrepl version: 0.1.1
OS: FreeBSD 11.2 or 12.0
Architecture: i386 only
Note: this build error is not seen on amd64 architectures

Excerpt of build error:
```
# github.com/zrepl/zrepl/rpc/dataconn/timeoutconn
rpc/dataconn/timeoutconn/timeoutconn.go:167:4: cannot use uint64(len(buffers[i])) (type uint64) as type uint32 in field value
rpc/dataconn/timeoutconn/timeoutconn.go:272:22: cannot use uint64(curVecNewLength) (type uint64) as type uint32 in assignment
```

Full build log error:
http://beefy10.nyi.freebsd.org/data/112i386-default/503555/logs/zrepl-0.1.1.log

Links to problematic code:
https://github.com/zrepl/zrepl/blob/master/rpc/dataconn/timeoutconn/timeoutconn.go#L167
https://github.com/zrepl/zrepl/blob/master/rpc/dataconn/timeoutconn/timeoutconn.go#L272

**Comment by problame** [comment]
Thanks for the report, would you mind testing the commit posted above on both amd64 and i386?
Please report back, will merge it then.

**Comment by woodsb02** [comment]
That appears to have fixed the build errors. To be clear, I haven't performed runtime testing.

Build status of zrepl 0.1.1 with patch applied from 6ecd1eb:
- [x] FreeBSD 13-CURRENT amd64
- [x] FreeBSD 12.0 amd64
- [x] FreeBSD 12.0 i386
- [x] FreeBSD 11.2 amd64
- [x] FreeBSD 11.2 i386

**Comment by problame** [comment]
Runtime testing is definitely necessary, will try to do that *on amd64* sometime this week.
At the very least, the tests covered by `make tests` should pass on all platforms.

The modified code path is exercised (too lightly!) in https://github.com/zrepl/zrepl/blob/3f5027e281c5635592b68fa3fb7dadf2b770818b/rpc/dataconn/timeoutconn/timeoutconn_test.go

**Comment by problame** [comment]
Sorry for the late update: I did runtime testing on `freebsd amd64` using my personal zrepl deployment, no issues observed. No hardware / VMs for i386, though.
Do you have test hardware for i386?

**Comment by woodsb02** [comment]
Sorry, I don’t have any hardware / VMs for i386 runtime testing either.

**Comment by problame** [comment]
The change has been merged to master, closing this one.
We don't provide pre-built binaries though.
If a future reader of this issue is interested, please open a PR that extends the `make release` target.

**Comment by Smithx10** [comment]
Look's like this is happening on Illumos also.
```
arch@9d46dd2d-1178-ce83-cbc4-d396e4a24060 ~/g/s/g/z/zrepl Γ¥»Γ¥»Γ¥» GOOS=illumos go build -v .                                                                                                                                                                                   Γ£ÿ 130 master
github.com/zrepl/zrepl/rpc/dataconn/timeoutconn
# github.com/zrepl/zrepl/rpc/dataconn/timeoutconn
rpc/dataconn/timeoutconn/timeoutconn.go:167:4: cannot use &buffers[i][0] (type *byte) as type *int8 in field value
rpc/dataconn/timeoutconn/timeoutconn.go:260:4: undefined: syscall.SYS_READV
rpc/dataconn/timeoutconn/timeoutconn.go:297:23: cannot use (*byte)(unsafe.Pointer(uintptr(unsafe.Pointer((*iovecs)[0].Base)) + uintptr(left))) (type *byte) as type *int8 in assignment
```

**Comment by problame** [comment]
@Smithx10 indeed, that'll fix it. I'll add i386 builds for freebsd & linux in that branch, too.
