### ISSUE TITLE
pull job hangs when stepping begins

### ISSUE THREAD

**Issue by dgrechka** [zrepl/zrepl#185]
When I start the pull job it performs the preparation phase well, but then stuck in the stepping (e.g. 0 B/s transfer speed)

Like this:
![image](https://user-images.githubusercontent.com/5637547/59277839-8ad23f00-8c69-11e9-812e-77db45db9617.png)

In the daemon output I see:
```
...
2019-06-11T16:53:58+03:00 [DEBG][cube_active_system]: initiate dry run send request invocation="1" subsystem="repl"
2019-06-11T16:53:58+03:00 [DEBG][cube_active_system]: initiate dry run send request invocation="1" subsystem="repl"
2019-06-11T16:53:58+03:00 [DEBG][cube_active_system]: initiate dry run send request invocation="1" subsystem="repl"
2019-06-11T16:53:58+03:00 [DEBG][cube_active_system]: filesystem planning finished invocation="1" subsystem="repl" filesystem="data/active_system/db/mail"
2019-06-11T16:54:26+03:00 [DEBG][cube_active_system]: grpc state change invocation="1" subsystem="rpc" grpc_state="CONNECTING"
2019-06-11T16:54:26+03:00 [DEBG][cube_active_system]: ClientHandshake url="doesn't matter done by dialer" connType="*net.TCPConn" subsystem="rpc.ctrl" invocation="1"
2019-06-11T16:54:26+03:00 [DEBG][cube_active_system]: grpc state change invocation="1" subsystem="rpc" grpc_state="READY"
```

Why this could happen?

I have following source job configuration:
```
jobs:
 - name: pull_source_active_system
   type: source
   serve:
     type: tcp
     listen: "10.0.0.1:10123"
     clients: {
       "10.0.3.8": "nas_uz"
     }
   filesystems: {
     "data/active_system<": true
   }
   snapshotting:
     type: manual
```
on FreeBSD 11.2-RELEASE-p9 zrep 0.1.1 installed via pkg

-----

and the corresponding pull job
```
jobs:
- name: cube_active_system
  type: pull
  connect:
    type: tcp
    address: "cube.ku.grechka:10123"
  root_fs: "data/backups/cube"
  pruning:
    keep_sender:
      - type: regex
        regex: ".*"
    keep_receiver:
      - type: regex
        regex: ".*"
  interval: manual
```
on FreeBSD 11.2-STABLE FreeBSD 11.2-STABLE. zrepl-freebsd-amd64 v0.1.1 downloaded from github release page

**Comment by problame** [comment]
Is there really no more log output on the pull-side? i.e., no more log output after 
```
2019-06-11T16:54:26+03:00 [DEBG][cube_active_system]: grpc state change invocation="1" subsystem="rpc" grpc_state="READY"
```
?

Also, what about the source-side logs? Could you please enable debug logging on the source side and provide log output from the time when replication gets stuck?

Finally: could you please run `ps aux | grep zfs` on both sides after the system gets stuck and report the results?

**Comment by dgrechka** [comment]
Hi, thank you!

After enabling logs on source side and restarting the source side zrepl daemon, the situation changed on the pull side. I've got the following on the pull side:
<img width="741" alt="Capture" src="https://user-images.githubusercontent.com/5637547/59280664-9b38e880-8c6e-11e9-89c8-992d2ef53b65.PNG">

I've restarted the source side daemon once again and everything begin to work.
![image](https://user-images.githubusercontent.com/5637547/59280830-e4893800-8c6e-11e9-98de-b73bbdf55e7d.png)



So the issue is not reproducible anymore.

Shell we close it?

**Comment by problame** [comment]
refs #179 where things also seem to get stuck

One question about `data/backups/cube`: what is the `mountpoint` property of that dataset?

**Comment by dgrechka** [comment]
It's just a regular path:
```
root@nas[/mnt/data/bin]# zfs get mountpoint data/backups/cube
NAME               PROPERTY    VALUE                   SOURCE
data/backups/cube  mountpoint  /mnt/data/backups/cube  default
```

And yes, initially there were no more log output after
```
2019-06-11T16:54:26+03:00 [DEBG][cube_active_system]: grpc state change invocation="1" subsystem="rpc" grpc_state="READY"
```

**Comment by problame** [comment]
OK, that's different from all the setups I know, where `mountpoint=none` on the `root_fs` .

We don't enforce this ATM, but we should, it's the reason for the error I see in the zrepl status output:
```
cannot receive incremental stream: destination ... has been modified
```
The modifications are the mountpoint directories that ZFS automatically creates for each received child filesystem because the `mountpoint` != `none`.

**Comment by problame** [comment]
Would you mind destroying the receive-side filesystems, leave `mountpoint=/mnt/data/backups/cube` on the `root_fs` and try to reproduce the problem?
And then, the same thing with `mountpoint=/mnt/data/backups/cube`?

**Comment by dgrechka** [comment]
Aha! I've got the issue again simply by killing receive side daemon, restarting it and waking poll job.

Stuck again in the very beginning:
![image](https://user-images.githubusercontent.com/5637547/59292922-b1eb3980-8c86-11e9-9733-c4b2f8ebabd2.png)

Here is source side logs:
[source_side_logs.txt](https://github.com/zrepl/zrepl/files/3277730/source_side_logs.txt)
 
Poll side logs:
```
2019-06-11T20:20:12+03:00 [DEBG][cube_active_system]: initiate dry run send request invocation="1" subsystem="repl"
2019-06-11T20:20:12+03:00 [DEBG][cube_active_system]: initiate dry run send request invocation="1" subsystem="repl"
2019-06-11T20:20:12+03:00 [DEBG][cube_active_system]: initiate dry run send request invocation="1" subsystem="repl"
2019-06-11T20:20:13+03:00 [DEBG][cube_active_system]: initiate dry run send request invocation="1" subsystem="repl"
2019-06-11T20:20:13+03:00 [DEBG][cube_active_system]: initiate dry run send request invocation="1" subsystem="repl"
2019-06-11T20:20:13+03:00 [DEBG][cube_active_system]: filesystem planning finished invocation="1" subsystem="repl" filesystem="data/active_system"
2019-06-11T20:20:40+03:00 [DEBG][cube_active_system]: grpc state change invocation="1" subsystem="rpc" grpc_state="CONNECTING"
2019-06-11T20:20:41+03:00 [DEBG][cube_active_system]: ClientHandshake connType="*net.TCPConn" subsystem="rpc.ctrl" url="doesn't matter done by dialer" invocation="1"
2019-06-11T20:20:41+03:00 [DEBG][cube_active_system]: grpc state change grpc_state="READY" invocation="1" subsystem="rpc"
2019-06-11T20:22:01+03:00 [DEBG][cube_active_system]: grpc state change invocation="1" subsystem="rpc" grpc_state="CONNECTING"
2019-06-11T20:22:01+03:00 [DEBG][cube_active_system]: ClientHandshake subsystem="rpc.ctrl" url="doesn't matter done by dialer" connType="*net.TCPConn" invocation="1"
2019-06-11T20:22:01+03:00 [DEBG][cube_active_system]: grpc state change grpc_state="READY" invocation="1" subsystem="rpc"
2019-06-11T20:24:12+03:00 [DEBG][cube_active_system]: grpc state change invocation="1" subsystem="rpc" grpc_state="CONNECTING"
2019-06-11T20:24:12+03:00 [DEBG][cube_active_system]: ClientHandshake invocation="1" subsystem="rpc.ctrl" url="doesn't matter done by dialer" connType="*net.TCPConn"
2019-06-11T20:24:12+03:00 [DEBG][cube_active_system]: grpc state change invocation="1" subsystem="rpc" grpc_state="READY"
```

Output of `ps aux | grep zfs` is
```
root@nas[/mnt/data/bin]# ps aux | grep zfs
root          15   0.0  0.0      0    272  -  DL   16:31     0:08.77 [zfskern]
root        3678   0.0  0.0   9012   4936  -  Is   16:32     0:00.00 /usr/sbin/zfsd
root       14195   0.0  0.0   6704   2676  0  S+   20:26     0:00.00 grep zfs
root       13888   0.0  0.0   7832   3800  1  I+   20:20     0:00.00 zfs recv data/backups/cube/data/active_system/db/mail
```

**Comment by dgrechka** [comment]
The output of `ps aux | grep zfs` on sender side is
```
root@cube:~ # ps aux | grep zfs
root        44   0.0  0.0      0    256  -  DL   29Apr19     37:50.59 [zfskern]
root      1408   0.0  0.0   8464   1684  -  Is   29Apr19      0:00.01 /usr/sbin/mountd -r /etc/exports /etc/zfs/exports
root     44670   0.0  0.1   7788   3380  -  I    20:09        0:00.05 zfs send -i data/active_system/db/mail@2019-02-01 data/active_system/db/mail@2019-03-0
root     44674   0.0  0.1   7788   3392  -  I    20:09        0:00.14 zfs send -i data/active_system/db/asterisk@2019-02-01 data/active_system/db/asterisk@2
root     44676   0.0  0.1   7788   3392  -  I    20:09        0:00.06 zfs send -i data/active_system/db@2019-02-01 data/active_system/db@2019-03-01
root     44679   0.0  0.1   7788   3392  -  I    20:09        0:00.05 zfs send -i data/active_system/backup@2019-02-01 data/active_system/backup@2019-03-01
root     44681   0.0  0.1   7788   3392  -  D    20:09        0:00.02 zfs send -i data/active_system/db/mysql@2019-02-01 data/active_system/db/mysql@2019-03
root     55186   0.0  0.1   7788   3412  -  D    20:20        0:00.01 zfs send -i data/active_system/db/mail@2019-02-01 data/active_system/db/mail@2019-03-0
root     69214   0.0  0.1   6660   2440  0  S+   20:32        0:00.00 grep zfs
```

**Comment by dgrechka** [comment]
My hypothesis is the following.

After first receive job failure with 
```cannot receive incremental stream: destination ... has been modified```

there remain stale `zfs send` processes on sender side (see `ps aux | grep zfs` output of sender in my previous message) and perhabs sender side daemon enters some abnormal state.

The subsequent attempts to wake up poll job result in stuck transfer, as the sender daemon remains in state of sending previous transfers.

**Comment by problame** [comment]
The hypothesis seems sensible.
To verify it, run the following commands on both sides of the replication setup:

```
zrepl pprof on 127.0.0.1:12345
go tool pprof -svg /usr/local/bin/zrepl http://127.0.0.1:12345/debug/pprof/goroutine
```

and upload the generated profileXXX.svg files here.

**Comment by problame** [comment]
I still need the SVGs from pprof to verify, but I think I found a candidate:

https://github.com/zrepl/zrepl/blob/5b97953bfb099d523c9158c533315162f54f4847/zfs/zfs.go#L822

    // streamCopier always fails before or simultaneously with Wait
    // thus receive from it first

The underlying assumption was / is that once ZFSRecv (aka Wait here) exits, the `streamCopier.WriteStreamTo` also fails with a pipe error.
And in fact, we [close our reference to the read-end of the pipe right after starting ZFSRecv](https://github.com/zrepl/zrepl/blob/5b97953bfb099d523c9158c533315162f54f4847/zfs/zfs.go#L796).

And, as soon as `zfs recv` is dead, its reference to the read-end should also be dead. Which, according to [`man 7 pipe`](http://man7.org/linux/man-pages/man7/pipe.7.html) implies that
> If all file descriptors referring
       to the read end of a pipe have been closed, then a write(2) will
       cause a SIGPIPE signal to be generated for the calling process

And basically [the same on FreeBSD](https://www.freebsd.org/cgi/man.cgi?pipe(2)), albeit a bit more general

>  A pipe that has had an end	closed is considered widowed.  Writing on such
     a pipe causes the writing process to receive a SIGPIPE signal.

Note that SIGPIPE, afaik, is mapped to a broken pipe error in Go. (This should still be confirmed).

After doing the pprof profiles as described above, you could try the following:

1. Start both sides with environment variable `ZREPL_ZFS_DEBUG=1` set (e.g. `export ZREPL_ZFS_DEBUG=1` in the rc.d script). This will yield debug output on stderr (i.e. not in the debug log). The FreeBSD rc script uses `daemon` to capture the output in a file AFAIK.

2. In a separate experiment, set `mountpoint=none` on the `root_fs` on the pull-side, destroy all filesystems under `root_fs` and retry replication with `mountpoint=none`, which should avoid the `destination ... has been modified` error.

**Comment by dgrechka** [comment]
Here are the generated SVGs (github prevents posting of raw svg, so I put them in zip):

[poll_n_source_profiles.zip](https://github.com/zrepl/zrepl/files/3278386/poll_n_source_profiles.zip)

**Comment by problame** [comment]
Thanks. Please try to wake up the pull job a few more times, maybe let it sit for another 60min or so, and produce another set of SVGs.

Also, could you please include the output of

```
curl http://127.0.0.1:12345/debug/pprof/goroutine?debug=1
```
for each side?

**Comment by dgrechka** [comment]
curl obtained outputs:
[source.txt](https://github.com/zrepl/zrepl/files/3278470/source.txt)
[poll.txt](https://github.com/zrepl/zrepl/files/3278471/poll.txt)

**Comment by dgrechka** [comment]
When I issue more wakeup signals it tells me `already woken up`

**Comment by problame** [comment]
Could you please provide `ps aux | grep zfs` for the source and pull side (without restarting, i.e. should match with the state of source.txt and poll.txt above)

**Comment by dgrechka** [comment]
Source side:
```
root@cube:~ # ps aux | grep zfs
root        44   0.0  0.0      0    208  -  DL   29Apr19     38:00.74 [zfskern]
root      1408   0.0  0.0   8464   1684  -  Is   29Apr19      0:00.01 /usr/sbin/mountd -r /etc/exports /etc/zfs/exports
root     66691   0.0  0.1   7788   3332  -  I    22:15        0:00.07 zfs send data/active_system/jails/syncjail@2019-06-11
root     66834   0.0  0.1   7788   3332  -  I    22:17        0:01.05 zfs send data/active_system/jails/syncjail@2019-06-11
root     86020   0.0  0.1   7788   3376  -  D    22:32        0:00.01 zfs send data/active_system/jails/syncjail@2019-06-11
root     75378   0.0  0.1   6660   2532  0  S+   00:06        0:00.00 grep zfs
```

Poll side:
```
root          15   0.0  0.0      0    272  -  DL   16:31     0:14.13 [zfskern]
root        3678   0.0  0.0   9012   4936  -  Is   16:32     0:00.01 /usr/sbin/zfsd
root       23937   0.0  0.0   6704   2676  0  S+   00:11     0:00.00 grep zfs
root       19718   0.0  0.0   7832   3800  1  I+   22:32     0:00.00 zfs recv data/backups/cube/data/active_system/jails/syncjail
```

And profile SVG and debug captured by curl (recaptured all of them including `ps aux | grep zfs` right after each other within one minute, in case something changed):
[profiles&curl_debug.zip](https://github.com/zrepl/zrepl/files/3278580/profiles.curl_debug.zip)

**Comment by problame** [comment]
The zip seems to only contain the `poll.txt` file.

**Comment by dgrechka** [comment]
Sorry.
Here the full one:
[profiles&curl_debug.zip](https://github.com/zrepl/zrepl/files/3278613/profiles.curl_debug.zip)

**Comment by problame** [comment]
There is only one goroutine in the zfs send code on the source side, despite there being 3 zfs send processes.

That is odd, we should observe one goroutine per zfs send.

Two of the zfs send processes are in state `I`, one is in state `D`.
They are not zombies, that would be `Z`.

Other idea: https://www.freebsd.org/cgi/man.cgi?procstat `procstat kstack $(pidof zfs)` to see where the zfs process got stuck in the kernel...

Apart from that, my next step would be to mock the `zfs recv` error in my dev setup.

**Comment by problame** [comment]
Is this bug still reproducible?

**Comment by dgrechka** [comment]
Let me check once again.

**Comment by problame** [comment]
Any results?

**Comment by problame** [comment]
Closing this due to lack of response.
