### ISSUE TITLE
ZVOL issues

### ISSUE THREAD

**Issue by mdtancsa** [zrepl/zrepl#201]
I have 2 FreeBSD systems, one RELENG_11 (sender) and RELENG_12 (receiver).  It seems when I try and send a zfs volume, an error is triggered on the receiver/sink end 
The sender has the following test volume
0{sendera}# zfs list zroot/volumetest
NAME               USED  AVAIL  REFER  MOUNTPOINT
zroot/volumetest  7.07M   274G  74.6K  -

When zrepl sends this to the releng12 box, I get the following error 

Jul 18 10:19:04 backup4 kernel: g_dev_taste: make_dev_p() failed (gp->name=zvol/zbackup1/zrepl/tor/sendera.sentex.ca/zroot/volumetest@zrepl_20190718_141903_000, error=63)

The error 63 I think implies the name is too long? However, the snapshot actually does get created, and I have names that are longer, just not zvols.  
On the sink side (the releng12 box getting the snapshots), the rootfs is
root_fs: "zbackup1/zrepl/tor"
But for some reason, the name= shows zvol/zbackup1 in the error message ? 

zbackup1/zrepl/tor/sendera.sentex.ca/zroot/volumetest@zrepl_20190718_141903_000                                           0      -  89.5K  -
zbackup1/zrepl/tor/sendera.sentex.ca/zroot/volumetest@zrepl_20190718_144903_000                                           0      -  89.5K  -

zbackup1/zrepl/tor/sendera.sentex.ca/zroot/chyves/guests/shellresi/logs@zrepl_20190718_054903_000                         0      -   351K  -

the sink has no zrepl error messages in the logs. The sender has the following
Jul 18 10:19:03 sendera zrepl[32642]: job=me_to_backup4 msg="start replication" invocation=3 
Jul 18 10:19:03 sendera zrepl[32642]: job=me_to_backup4 subsystem=repl msg="start planning" invocation=3 
Jul 18 10:19:04 sendera zrepl[32642]: job=me_to_backup4 subsystem=repl msg=conflict conflict="no common snapshot or suitable bookmark between sender and receiver:\n  sorted sender versions:\n    @zrepl_20190718_141903_000\n  sorted receiver versions:\n" filesystem=zroot/volumetest invocation=3 
Jul 18 10:19:04 sendera zrepl[32642]: job=me_to_backup4 subsystem=repl msg="automatically resolved" invocation=3 filesystem=zroot/volumetest resolution="start replication at most recent snapshot @zrepl_20190718_141903_000" 
Jul 18 10:19:04 sendera zrepl[32642]: job=me_to_backup4 subsystem=repl msg=conflict filesystem=zroot/testfilesystem conflict="no common snapshot or suitable bookmark between sender and receiver:\n  sorted sender versions:\n    @zrepl_20190718_141903_000\n  sorted receiver versions:\n" invocation=3 
Jul 18 10:19:04 sendera zrepl[32642]: job=me_to_backup4 subsystem=repl msg="automatically resolved" invocation=3 resolution="start replication at most recent snapshot @zrepl_20190718_141903_000" filesystem=zroot/testfilesystem 
Jul 18 10:19:04 sendera zrepl[32642]: job=me_to_backup4 subsystem=rpc.data msg="ReqRecv returns" invocation=3 
Jul 18 10:19:28 sendera zrepl[32642]: job=me_to_backup4 msg="start pruning sender" invocation=3 
Jul 18 10:19:29 sendera zrepl[32642]: job=me_to_backup4 msg="finished pruning sender" invocation=3 
Jul 18 10:19:29 sendera zrepl[32642]: job=me_to_backup4 msg="start pruning receiver" invocation=3 
Jul 18 10:19:31 sendera zrepl[32642]: job=me_to_backup4 msg="finished pruning receiver" invocation=3 
Jul 18 10:19:31 sendera zrepl[32642]: job=me_to_backup4 msg="wait for wakeups" 
Jul 18 10:49:03 sendera zrepl[32642]: job=me_to_backup4 msg="start replication" invocation=4 
Jul 18 10:49:03 sendera zrepl[32642]: job=me_to_backup4 subsystem=repl msg="start planning" invocation=4 
Jul 18 10:49:04 sendera zrepl[32642]: job=me_to_backup4 subsystem=rpc.data msg="ReqRecv returns" invocation=4 
Jul 18 10:49:19 sendera zrepl[32642]: job=me_to_backup4 msg="start pruning sender" invocation=4 
Jul 18 10:49:20 sendera zrepl[32642]: job=me_to_backup4 msg="finished pruning sender" invocation=4 
Jul 18 10:49:20 sendera zrepl[32642]: job=me_to_backup4 msg="start pruning receiver" invocation=4 
Jul 18 10:49:23 sendera zrepl[32642]: job=me_to_backup4 msg="finished pruning receiver" invocation=4 
Jul 18 10:49:23 sendera zrepl[32642]: job=me_to_backup4 msg="wait for wakeups" 

which I think is normal in that I created a new dataset zroot/testfilesystem

  type: push
  connect:
    type: tls

**Comment by mdtancsa** [comment]
OK, some more data. This seems to be some ZFS issue and sending volumes.  zrepl aside, if on one server I do
zfs send -Rv zroot/volumetest@zrepl_20190718_185346_000 | nc 10.151.9.3 1000
and on the other server
nc -l 1000 | zfs recv -vF zroot/12345678901234567890123456

I get the kernel error/warning on the recv side...
g_dev_taste: make_dev_p() failed (gp->name=zvol/zroot/12345678901234567890123456a@zrepl_20190718_185346_000, error=63)

If I shorten it to 
g_dev_taste: make_dev_p() failed (gp->name=zvol/zroot/12345678901234567890123456@zrepl_20190718_185346_000, error=63)
no error/warning
The other odd thing is, is that the volume is there just fine. I thought it might be something in /dev/zvol that limits it, but that seems OK too ?
# ls -l /dev/zvol/zroot/12345678901234567890123456a 
crw-r-----  1 root  operator  - 0x124 Jul 18 15:41 /dev/zvol/zroot/12345678901234567890123456a
# 
I will ask on the FreeBSD list to see if anyone has an idea what it might be and what issue / error I am bumping into.

**Comment by mdtancsa** [comment]
OK, a work around to silence the error/warning messages.  
zfs set volmode=none <volume at issue>
on the sink server fixes the problem for me, ot at least works around the issue, which is sort of not really an issue.  I wonder if this could be a configurable feature in zrepl.yml at some point, or at least a footnote in the docs somewhere

**Comment by problame** [comment]
I'll ref this to #70 because we explore the idea of GUIDs for filesystems there.
If we used filesystem GUIDs below root_fs, i.e. replicate into a flat root_fs & store the hierarchy information elsewhere, the problem you encountered could be avoided by statically asserting that `/dev/zvol/$root_fs/<GUID_LENGTH>` is always shorter than the maximum device path name.
