### ISSUE TITLE
transport: tcp: Allow for clients: {"*"}  or {"10.24.0.0/16"} 

### ISSUE THREAD

**Issue by Smithx10** [zrepl/zrepl#235]
Scenario:

I have a service that  I want to back up on a non routable network using zrepl and tcp.  I'd like to accept any client on that network that would like to replicate datasets.  (the services come up and down adhoc)  

Is this possible?

Thank You,
Bruce Smith

**Comment by problame** [comment]
The purpose of `clients` is to map IP addresses (which might change when the network is renumbered, etc) to client identities.
Client identities are used by receving-sides to map all filesystems received from the push source to `$root_fs/$client_identity/$push_src_fs_name`.
Would you just use the IP addresses as client identities?

**Comment by Smithx10** [comment]
@problame 

I'd imagine the IP Address would work as a default,  or perhaps the Pusher could provide a an identifier.  If a conflict occurs we could append an ever growing int.  bob, bob1, bob2, bob3 etc...

I think in this scenario,  the server is really there to just accept filesystems.  We could probably do the same with TLS except not use anything from the certificates as an identifier.  I think currently CN is being used.  

I'd imagine this decoupling will allow for future features like policy to be implemented easier. https://www.openpolicyagent.org/  Is something we are using internally that might make sense down the road for controlling / creating policy outside of ZREPL itself.

**Comment by problame** [comment]
>  perhaps the Pusher could provide a an identifier. If a conflict occurs we could append an ever growing int. bob, bob1, bob2, bob3 etc...
> I think in this scenario, the server is really there to just accept filesystems. We could probably do the same with TLS except not use anything from the certificates as an identifier. I think currently CN is being used.

The difference between client-provided identities and identities-in-CN is that in the latter case the client cannot spoof their CN, yet be mobile (have different IPs).

> I'd imagine this decoupling will allow for future features like policy to be implemented easier. https://www.openpolicyagent.org/ Is something we are using internally that might make sense down the road for controlling / creating policy outside of ZREPL itself.

OPA seems like an interesting idea, but zrepl is intended as a free-standing / mostly self-contained solution on top of ZFS.
Bringing in OPA infrastructure ( or something like policykit for that matter ) will probably not happen - in essence, most of `zrepl.yml` _is_ policy definition already.

**Comment by problame** [comment]
> I'd imagine the IP Address would work as a default, or perhaps the Pusher could provide a an identifier. If a conflict occurs we could append an ever growing int. bob, bob1, bob2, bob3 etc...

* IP address as default is ~2h of implementation and manual testing work - very feasible, but not high on my priority list right now.
* Client-provided identities would require a protocol change (acceptable before 1.0) and should be considered for all transports (i.e. separation of auth & client identities)

**Comment by Smithx10** [comment]
A simple  * * PR has been opened to perhaps implement this.  https://github.com/zrepl/zrepl/pull/265
