### ISSUE TITLE
ssh+stdinserver does not work with @privileged SystemCallFilter

### ISSUE THREAD

**Issue by zoni** [zrepl/zrepl#237]
On setting up zrepl for the first time, I had a lot of difficulty getting replication going using ssh + stdinserver. All the logs would give me was:

```
zrepl[12230]: [redacted][rpc.ctrl]: cannot connect err="ssh exited unexpectedly with exit status 0" invocation="1"
```

Running SSH the way zrepl would call it would successfully connect and show output from the stdinserver on the remote end. I eventually ended up debugging this by calling `strace -f -p <zrepl pid>`, finding the PID of the forked ssh process (potential future reader: look for the `execve` syscall) and then filtering down to just the calls from that SSH process.

That led me to seeing the ssh process was being forcibly terminated. (I unfortunately no longer have the original strace output so I can't look up the exact lines anymore)

I tracked this down to the systemd `SystemCallFilter` configuration shipped for Ubuntu/Debian (this is on Ubuntu 18.04, for what it's worth). By default this is:

```
SystemCallFilter=~ @mount @cpu-emulation @keyring @module @obsolete @privileged @raw-io @debug @clock @resources
```

Removing `@privileged` was required to successfully replicate. I've done so with:

```
# /etc/systemd/system/zrepl.service.d/override.conf
[Service]
SystemCallFilter=
SystemCallFilter=~ @mount @cpu-emulation @keyring @module @obsolete @raw-io @debug @clock @resources
```

I would suggest removing `@privileged` from the list by default and can make a PR for that if desired.

Alternatively, this could be documented with steps to turn it off for those users wanting to use ssh+stdinserver so `@privileged` can remain by default (presumably this works for people using the plain TCP transports?) but that seems a little too much friction for new users in my opinion. Would be happy to make documentation for that as well though, if this route is desired.

**Comment by problame** [comment]
Thanks for tracking this one down and providing this first-class bug report!
It is quite possible that I never tested the service definition for ssh transport.
It should work for TCP.

The general guideline is that the default service configuration should work for any transport supported by zrepl.

Let's collect some information about the systems using `lsb_release -a && uname -a && systemd --version`

**SSH Transport Works on...**

```
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
Linux zrepl-dev-debian-2 4.19.0-6-cloud-amd64 #1 SMP Debian 4.19.67-2 (2019-08-28) x86_64 GNU/Linux
systemd 241 (241)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid
```

**SSH Transport Doesn't Work On...**

**Comment by zoni** [comment]
The system this was failing on prior to removing the `@privileged` has:

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
Linux hostname_redacted 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
systemd 237
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid
```

-------

For completeness sake, it also has a few ssh_config items that affect this setup, though I really don't see this having an impact on the issue described here:

```
Host zrepl-ams1
	ControlPath /run/zrepl/%l-%r@%h:%p
	ControlPersist 10800
	ProxyCommand pv --quiet --buffer-size 64M --rate-limit 10M | nc redacted 4444

Host *
	ExitOnForwardFailure yes
	ServerAliveCountMax 2
	ServerAliveInterval 30
	ControlPath ~/.ssh/master/%l-%r@%h:%p
	ControlMaster auto
	ControlPersist 900
```

Relevant parts from zrepl config:

```
jobs:
  - name: redacted
    type: push
    connect:
      type: ssh+stdinserver
      host: zrepl-ams1
      user: root
      port: 4444
      identity_file: /root/.ssh/zrepl
    filesystems: [..]
    snapshotting: [..]
    pruning: [..]
```

**Comment by problame** [comment]
Hum, I can't find anything related to `kill` or `SystemCallFilter` in the [systemd changelog](https://github.com/systemd/systemd/blob/master/NEWS).

The source code that expands the filter group `@privileged` didn't change much between 237 and 241:

```
cs@cslap:[~/ext/systemd]: git show v237:src/shared/seccomp-util.c | grep -A 35 SET_PRIVI > 237
cs@cslap:[~/ext/systemd]: git show v241:src/shared/seccomp-util.c | grep -A 35 SET_PRIVI > 241
cs@cslap:[~/ext/systemd]: git show v241:src/shared/seccomp-util.c | grep -A 35 SET_PRIVI > 241
cs@cslap:[~/ext/systemd]: diff -u 237 241
--- 237	2019-10-25 23:16:10.248508715 +0200
+++ 241	2019-10-25 23:16:17.203342731 +0200
@@ -13,7 +13,9 @@
                 "bpf\0"
                 "capset\0"
                 "chroot\0"
+                "fanotify_init\0"
                 "nfsservctl\0"
+                "open_by_handle_at\0"
                 "pivot_root\0"
                 "quotactl\0"
                 "setdomainname\0"
@@ -26,11 +28,9 @@
                 "setresuid32\0"
                 "setreuid\0"
                 "setreuid32\0"
-                "setuid\0"
+                "setuid\0"      /* We list the explicit system calls here, as @setuid also includes setgid() which is not necessarily privileged */
                 "setuid32\0"
                 "vhangup\0"
         },
         [SYSCALL_FILTER_SET_PROCESS] = {
                 .name = "@process",
-                .help = "Process control, execution, namespaceing operations",
-                .value =
```

So, is it dependent on kernel / libseccomp version?

Side Note: nice idea with the `ControlPath` option ;)

**Comment by zoni** [comment]
> So, is it dependent on kernel / libseccomp version?

Perhaps that. The one other thing I can think of right now is the version of ssh doing something differently between my Ubuntu machines and your Debian instance.

For what it's worth:

```
$ ssh -V       
OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017
```

> Side Note: nice idea with the ControlPath option ;)

Thank you. I'm also rather pleased with the use of `pv` in `ProxyCommand` to throttle the upload and keep it from hogging all available bandwidth without having to learn how to do traffic shaping with `tc`. :grinning:

**Comment by problame** [comment]
**Doesn't work on**
```
root@zrepl-u-1910-1:[/etc/zrepl/ssh]: lsb_release -a && uname -a && systemd --version
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 19.10
Release:        19.10
Codename:       eoan
Linux zrepl-u-1910-1 5.3.0-19-generic #20-Ubuntu SMP Fri Oct 18 09:04:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
systemd 242 (242)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
```

**Comment by problame** [comment]
Update for eoan: It seems like the problem **is not @privileged** but instead the `go-netssh` package which we use for the ssh transport: it seems to not handle ssh exits during the handshake correctly:

I fixed this in https://github.com/problame/go-netssh/tree/problame/fix-zrepl237-and-go-modules but have trouble with Go modules in the zrepl repo ATM.

You can test the change by adding 
```
replace github.com/problame/go-netssh => github.com/problame/go-netssh 7a8da6e19884213c209ab57da964af7320145be8
```

to zrepl's `go.mod` and rebuild using `make GO_MOD_READONLY=""` => `artifacts/zrepl`

If you remove the `known_hosts` entry from the push side and re-add `@privileged`, and use the updated zrepl package, does it work on bionic? (it does on eoan).
I suppose it worked on buster because I had the sink host in `known_hosts` already.

**Comment by problame** [comment]
Allright, go module issues resolved, commit  `ff79668` should fix your issue.
Steps to test:

- Remove the `override.conf`, i.e. use the package-provided systemd file
- `systemctl daemon-reload`
- Remove the lines for the target SSH server from your `known_hosts` file
- ( Also check for IPv4 and IPv6 addresses of that server, not just its hostname)
- Download the go1.13-built zrepl binary for linux-amd-64
- `systemctl stop zrepl`
- Copy the binary to /usr/bin/zrepl
- `chmod +x /usr/bin/zrepl`
- `systemctl restart zrepl`
- Run `zrepl version` to confirm you are running `ff79668`
- Verify that the zrepl error log contains a meaningful error message, along the lines of 'Host key verification failed`.

To download the go1.13-built zrepl binary, click on the status button next to the commit above and click on the `zrepl/publish-ci-artifacts` status: ![image](https://user-images.githubusercontent.com/956573/67673453-64901000-f97a-11e9-87f3-8288d272d7fb.png)

**Comment by zoni** [comment]
Major props on all the proactive effort here so far. The past days/week have been crazy hectic at work including multiple active incidents, so I've not had the time nor energy to look into this further yet.

I will try to run through this over the weekend, assuming I've mentally recovered a bit by then. Either way I'll keep you posted.

**Comment by problame** [comment]
Have you had a chance to test commit ff79668 ?

**Comment by problame** [comment]
Just completed the test procedure myself:
On Ubuntu 18.04, the fix still results in `transport: Error while dialing ssh terminated without stderr output (bad system call)`, **both with and without an entry in the `known_hosts` file**

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
Linux zrepl-ubuntu-1810-02 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
systemd 237
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid
```

Kernel command line:

```
[ 3869.869832] audit: type=1326 audit(1573943612.631:28): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=21753 comm="ssh" exe="/usr/bin/ssh" sig=31 arch=c000003e syscall=117 compat=0 ip=0x7f1d99361f10 code=0x0
```

=> 117 is the setresuid syscall:

```
#/usr/src/linux-headers-4.15.0-66-generic/arch/x86/include/generated/asm/syscalls_64.h
__SYSCALL_64(117, sys_setresuid, )
```

**Comment by problame** [comment]
Update: when building the [upstream `openssh-portable` from source](https://salsa.debian.org/ssh-team/openssh/tree/master/debian) (using autotools), the error doesn't occur.

**Comment by problame** [comment]
We'll deactivate the `@privileged` filter for now and issue a 0.2.1 with updated packages soon.
0.2.1 will also include the bumped go-netssh with better error reporting.
Sorry for the long delay!
