### ISSUE TITLE
Backup to aws glacier

### ISSUE THREAD

**Issue by timaebi** [zrepl/zrepl#243]
AWS glacier provides cheap storage for large amounts of data, which are not frequently accessed. A perfect place to store backups.

Since it is agnostic to what data is stored in it, I thought about directly storing zfs snapshots in a glacier vault. Would that fit in the scope of this project, or is it to different from the core business of zrepl? I thought about an additional transport mode. Or is there another place where it would fit better?

**Comment by problame** [comment]
The value users would be getting from zrepl would be snapshot management and pruning.
However, since there's no ZFS running on the glacier side, we can't do remote pruning of snapshots - we'd always need to do full sends.
I have a few ideas how to fix that, but that will not be part of zrepl.
