### ISSUE TITLE
zrepl status - Cannot scroll on long output

### ISSUE THREAD

**Issue by tdschmidl** [zrepl/zrepl#245]
Hi and good afternoonm,

sorry for opening again an issue - but maybe somebody else might encounter this as well:
When you have approx <50 datasets to replicate and want to watch the progress via `zrepl watch` you cannot scroll the output and get maybe relevant information cut here:
E.g. you miss the `Pruning Sender:` or `Pruning Receiver:` blocks

Is there any workaround for except `zrepl watch --raw`? Piping or redirecting the output will not work I guess due termbox-golang is used, right? https://github.com/zrepl/zrepl/blob/master/client/status.go

**Comment by citrus-it** [comment]
In case it's useful, I have a small script for watching what's in progress, using --raw and the `jq` utility.
Not perfect but I find it useful:

```
        zrepl status --raw | jq '
def roundit: .*100.0|round/100.0;
.[] | select(.type == "push") |
.push.Replication.Attempts[0].Filesystems |
.[]? | select(.State != "done") |
(.Info.Name, ((.Steps[0].Info.BytesReplicated * 100 / .Steps[0].Info.BytesExpected) | roundit))
        ' | paste - -
```

**Comment by problame** [comment]
> Is there any workaround for except zrepl watch --raw? Piping or redirecting the output will not work I guess due termbox-golang is used, right? https://github.com/zrepl/zrepl/blob/master/client/status.go

Yes, exactly. There is no workaround. #220 tracks potential alternative frameworks that allow for scrollable views, etc.
But there's definitely the use-case of getting a pretty-printed version of the report (basically what `zrepl status` does ATM), but for consumption on stdout.

At this point, we could probably get away with just rendering a big `string` in `zrepl status` and wrap that into something equivalent to `watch`, but in-process (i.e. reset cursor to upper left of terminal and redraw).
But the long-term goal is to have the status UI be more interactive, allowing features such as dynamic pause & resume, priority boosting, ....

The  to have the dataset tree foldable / searchable  and also be able to boost the priority of a dataset interactively.

**Comment by Thoro** [comment]
Yep, real problem, I got here 164 datasets ...

**Comment by candlerb** [comment]
I was expecting that `zrepl status | less` or `zrepl status | cat` would give me the full output.  Perhaps zrepl status could make a call to `isatty()`, and if it returns false, dump the full output one-time ?

**Comment by problame** [comment]
FWIW I just rebased https://github.com/zrepl/zrepl/pull/297 (new status UI) onto my `problame/develop` branch, the CI builds should be available within a few minutes. Feel free to play around with the `zrepl status-v2` subcommand and report feedback in the PR.
