### ISSUE TITLE
zfs: replication cursor: get bookmark txg: exit status 1

### ISSUE THREAD

**Issue by lapo-luchini** [zrepl/zrepl#249]
I just configured 6 FreeBSD "push" hosts and the 4 that use FreeBSD 12+ are all working perfectly, while the 2 that still use FreeBSD 11.1 give me this error just after the first "full" snap is sent (and then never send and incremental anymore):

```zfs: replication cursor: get bookmark txg: exit status 1```

I read in issue #1 that `zfs list -o guid,createtxg` is supported since 10.3 and I verified manually that it works on those hosts. I tried RTFS but I know Go too little and I don't understand what else can lead to that error. Any suggestion to continue debugging the issue?

**Comment by lapo-luchini** [comment]
Upgrading from the `zrepl-0.1.1` official package to a personally compiled `zrepl-0.2.1` binary, the error changes to:

```
zfs: replication cursor: get bookmark txg: zfs: set replication cursor: get snapshot createtxg: zfs exited with error: exit status 1                                                         
stderr:                                                                                                                                                                                      
cannot open 'z/data#zrepl_replication_cursor': invalid dataset name
```

Manual querying shows that the problem is creating the bookmarks, not reading them:
```
% freebsd-version
12.1-RELEASE-p1
% zfs list -t bookmark -r z
NAME                                      USED  AVAIL  REFER  MOUNTPOINT
z/home#zrepl_replication_cursor              -      -      -  -
```
while
```
% freebsd-version
11.1-RELEASE-p6
% zfs list -t bookmark -r z
no datasets available
```

**Comment by lapo-luchini** [comment]
Alas, FreeBSD 11.1 had `zfs bookmark` verb, but is unable to `zfs get` on it (even if I created it manually). 😢
```
% zfs get guid z/data#zrepl_replication_cursor
cannot open 'z/data#zrepl_replication_cursor': invalid dataset name
```
Given this, do you think there's any way to support FreeBSD 11.1?

**Comment by problame** [comment]
I suppose this is similar to #230 
FreeBSD 11.1 is EOL since July, 2017 according to https://www.freebsd.org/releases/
Upgrading to 11.3 (which is still supported) should solve your issues.

You can also hack around this by creating a proxy shell script that is in PATH and intercepts the replication cursor ZFS commands and emulates newer system behavior.

**Comment by lapo-luchini** [comment]
Yeah, I was hoping to have a full remote backup before attempting the upgrade, but will do the other way around.
BTW: there's also a different problem which seems more complex to emulate:
`could not parse zfs send -n output: no match for info line (regex1 ^(full)\t()([^\t]+@[^\t]+)\t([0-9]+)$) (regex2 ^(incremental)\t([^\t]+)\t([^\t]+@[^\t]+)\t([0-9]+)$)`

**Comment by problame** [comment]
Interesting, that's the dry-run zfs send output, used for size estimation.
