### ISSUE TITLE
Support for `armhf` architecture (e.g. ARMv7 32-bit)

### ISSUE THREAD

**Issue by awehrfritz** [zrepl/zrepl#271]
Are there any plans to support (i.e. provide binaries for) the `armhf` architecture (ARMv7 32-bit) on Debian/Ubuntu?

I just added the [Debian/Ubuntu APT repositories](https://zrepl.github.io/installation.html#debian-ubuntu-apt-repositories) and realised that it does not have packages for the `armhf` architecture.

I was looking into using `zrepl` on my [Helios4 NAS](https://wiki.kobol.io/helios4/intro/), which is based on a Marvell Armada 388 SoC with a ARM Cortex-A9 CPU (ARMv7 32-bit). ZFS (0.7.12) is working quite nicely on that system, and I would expect that there isn't much of a reason why `zrepl` wouldn't work their either.

**Comment by problame** [comment]
Opened a PR to produce the binary artifact.
Could you try the binary build from the CI? Just click on the green checkmark and download from zrepl-ci-artifacts:

![image](https://user-images.githubusercontent.com/956573/74100341-32bc4700-4b2e-11ea-9be7-981338ce7134.png)

**Comment by problame** [comment]
(also, I suppose you could download the amd64 debs manually, install them using dpkg, and then just replace the `/usr/bin/zrepl` binary with the `zrepl-linux-arm` one from the CI)

**Comment by awehrfritz** [comment]
Thanks @problame for addressing this issue right away!

I downloaded the binary from PR #272 (my) yesterday evening and tested it on my Helios4. The binary seems to work (i.e. prints the help), but I haven't gotten around to setup `zrepl` properly (couldn't find a easy way to put a simple config file, something like doing just local snapshots a zfs pool).

I don't have time to play with setting this up in the next couple of days, but I reckon this should be fine now from my end now.
