### ISSUE TITLE
Support unencrypted raw sends

### ISSUE THREAD

**Issue by InsanePrawn** [zrepl/zrepl#276]
I guess this borders on #182. 

As discussed in https://github.com/zrepl/zrepl/pull/259#issuecomment-584615614, I think we need the ability to use `send -w` on unencrypted datasets, if only for `-L` to circumvent zfsonlinux/zfs#6224, but it's also useful for skipping de- and recompression, amongst other things.

As I said there:
I suggest splitting up the two features: an option for raw sends, and an option for enforcing encryption.
Encryption implies raw, raw doesn't imply encryption
=> encryption=on + raw=off is a config error, encryption=(off|unset) + raw=(on|off|unset) is fine.
encryption=off + raw=off is the default anyway.

(If whoever implements this feels super nice, one could check whether `send` supports `-w` and substitute with `-Lce` for unencrypted sends, but I consider this very optional. All these flags are available in the now slowly aging ZoL 0.7 series. If you're running 0.6 in the year 2020, just don't turn 'raw' on in zrepl I guess; oooor we could go the extra mile and try to check for those feature flags being enabled on the pool and passing the enabled subset to `send`.)

**Comment by problame** [comment]
How about less truth-table headaches?

```
  send:
    encrypted: true | false 
    large_block: true | false
    comrpessed: true | false
    embed: true | false
```

* if `encrypted == true`: enforce  that the filesystem is encrypted and send with `w`, runtime fail for the filesystem otherwise
* else if `large_block == compressed == embed == true` and `-w` is available: set `-w`
* else
  * if `large_block: true`: set `-L`
  * if `compressed: true` set `-c`
  * if  `embed: true` set `-e`

**Comment by problame** [comment]
At this point, we might as well just throw in `props: true | false` for #24 as well

**Comment by InsanePrawn** [comment]
>     * else if `large_block == compressed == embed == true` and `-w` is available: set `-w`
> 
>     * else
>       
>       * if `large_block: true`: set `-L`
>       * if `compressed: true` set `-c`
>       * if  `embed: true` set `-e`

Absolutely fine with me!
For now my only request was access to `-w` without the encryption logic, but a fuller solution is preferred of course.
Although it's a little more to type/read than `raw: true` :man_shrugging:

**Comment by problame** [comment]
TBH, I don't really like the `-w` flag's different semantics depending on whether the dataset is encrypted or not. I have a TODO to submit a ZoL PR that adds a `zfs send --encrypted` flag that does the checks zrepl does in one go.
