### ISSUE TITLE
Retry with bookmark when From snap disappears from sender before repl

### ISSUE THREAD

**Issue by InsanePrawn** [zrepl/zrepl#314]
Basically a race between decoupled replication and pruning.
Can also happen with the To snapshot, but that requires replanning, which the From bookmark does not, if it exists.
For a first solution, I'd be okay if only the bookmark fallback happens within the same job run.
Long term we may or may not want datasets to dynamically re-plan, this goes back to backups vs 'continuous' replication use cases.

**Comment by problame** [comment]
Special case of #349
