### ISSUE TITLE
Different snapshot rules despite common transfer config

### ISSUE THREAD

**Issue by MoritzFago** [zrepl/zrepl#315]
I have a database dataset that has a lot of change over time. If I Snapshot it regularly, it fills up my small VM. So I tried to Blacklist it in the source job and do a separate snapshot task for it. Unfortunately the pull job doesn‘t pull it and also doesn‘t prune it. Is this currently possible?
OS: freenas 11.3 zrepl 0.2.1

**Comment by problame** [comment]
Could you please post your configuration files of both sides (secrets redacted!).

> Unfortunately the pull job doesn‘t pull it and also doesn‘t prune it

Any logs would be appreciated, but it could as well be just a config error.

**Comment by 3nprob** [comment]
@MoritzFago Does #600 capture your use-case?

**Comment by problame** [comment]
Closing this due to lack of response from @MoritzFago . As far as I can tell, the setup should work. Safely only with Replication Guarantees, i.e., zrepl 0.3 or newer.
