### ISSUE TITLE
Status UI: Pruner misses first dataset

### ISSUE THREAD

**Issue by InsanePrawn** [zrepl/zrepl#319]
Found while testing #313, might affect earlier versions:
zrepl status UI is lacking the lowest dataset in the pruner status UI, i.e. it's not listed, the overall progress bar doesn't include it and UI seems 'stuck' while it's pruning that dataset as expected.
The snapshotter UI does correctly include the lowest dataset.

Found on a snap job.

**Comment by InsanePrawn** [comment]
After finishing trying to prune the dataset, the dataset appears and its numbers are apparently included in the overall counts. All other datasets appear to be displayed immediately.

[This wasn't immediately visible before I cleared a couple hundred holds that would overflow the UI with pruning errors]

**Comment by problame** [comment]
There are certainly UI bugs in the status UI.

Was the entire status UI 'stuck' or just the pruner part?

**Comment by problame** [comment]
(In general, I would like to see some form of #297 get into master pretty quickly in order to addrss the 'lost line' bug in the current status UI)

**Comment by InsanePrawn** [comment]
> in order to addrss the 'lost line' bug in the current status UI)

Sounds like my bug. The UI isn't literally stuck, it just _looks_ stuck while zrepl is working on the 'invisble' dataset

> (In general, I would like to see some form of #297 get into master pretty quickly

I'd hate to see the new UI rushed out prematurely to fix that kind of bug, but I'd understand 'postponing' a bug fix if it turns out to be too complex in favor of working on the new UI. Maybe I'll find some time to do some work on the new UI myself soon(TM).

**Comment by problame** [comment]
Huh, that's odd. Is it the dataset with the 100s of snapshots with holds? Could you monitor CPU Utilization, or even better, use the new activity tracing feature, to investigate what's going on?

**Comment by problame** [comment]
>I'd hate to see the new UI rushed out prematurely to fix that kind of bug, but I'd understand 'postponing' a bug fix if it turns out to be too complex in favor of working on the new UI. Maybe I'll find some time to do some work on the new UI myself soon(TM).

To clarify: I'd ship both in 0.3, the new one as subcommand `status-v2`.

**Comment by InsanePrawn** [comment]
> Huh, that's odd. Is it the dataset with the 100s of snapshots with holds?

Formerly, yes, but the issue persists across pruning and zrepl restarts

> Could you monitor CPU Utilization, or even better, use the new activity tracing feature, to investigate what's going on?

I looked at the logs and as far as I can tell it's pruning the 'hidden' dataset as usual, the pruning UI just doesn't acknowledge its existence - it doesn't appear in the list and contribute to the total progress/number of snaps until it's done pruning.
The snapper UI is unaffected and works correctly apparently.

**Comment by InsanePrawn** [comment]
Couldn't reproduce anymore - closing for now, especially that status-v2 is merged.
