### ISSUE TITLE
Transport rate limiting

### ISSUE THREAD

**Issue by candlerb** [zrepl/zrepl#339]
I have some 100TB raidz filesystems which I currently replicate with syncoid, using ssh-hpn with encryption disabled so as not to be a bottleneck.

If I let them run at full speed they achieve ~550MiB/sec, but put so much load on the source server that they impact client performance (and sometimes crash the HBA!)  But if I limit them to 200MiB/sec then everything is fine.

With syncoid I specify `--source-bwlimit=200m`

zrepl would be a much cleaner replacement, as its native TCP transport removes the need for ssh-hpn, but I still need some way to limit the bandwidth.

The workarounds I can think of are:

- at the sender side, point at a TCP proxy on localhost which implements rate limiting
- using iptables rate limiting

**Comment by problame** [comment]
> zrepl would be a much cleaner replacement, as its native TCP transport removes the need for ssh-hpn, but I still need some way to limit the bandwidth.

zrepl should definitely provide this feature out of the box.
That being said, doing proper traffic shaping (even just rate limiting) is often trickier than one would imagine.

### Impl Advice

* we already have an interceptor that does the byte-counting for tracking replication progress:

  https://github.com/zrepl/zrepl/blob/master/replication/logic/replication_logic.go#L593-L603

Implement a similar interface for rate-limiting and use an existing implementation that wraps a net.Conn. Quick search (didn't evaluate any of them, that'll be the implementor's job):

* look at what popular go tools are using to limit download speeds
  * docker / containerd.io image downloader
  * there must be some `wget` rewrites in Go...
* https://pkg.go.dev/github.com/google/martian/trafficshape?tab=doc
* https://pkg.go.dev/github.com/juju/ratelimit?tab=doc+ own impl of `net.Conn` (

---

> I have some 100TB raidz filesystems which I currently replicate with syncoid, using ssh-hpn with encryption disabled so as not to be a bottleneck.
> 
> If I let them run at full speed they achieve ~550MiB/sec, but put so much load on the source server that they impact client performance (and sometimes crash the HBA!) But if I limit them to 200MiB/sec then everything is fine.

Load as in IO or load as in CPU? I'm curious about the CPU load you would experience with zrepl's TCP transport.

> 
> The workarounds I can think of are:
> 
>    *  at the sender side, point at a TCP proxy on localhost which implements rate limiting
>    * using iptables rate limiting

I suppose you mean using `iptables + tc` like [so](https://wiki.archlinux.org/index.php/Advanced_traffic_control#Using_tc_+_iptables) ?

**Comment by candlerb** [comment]
The problem appears to be load on the disk subsystem with very high levels of zfs send/recv, starving out other clients.  However I can see other use cases for people wanting background replication not to hog all available network bandwidth.

And yes, it was iptables tc/qdisc I was thinking of.

**Comment by problame** [comment]
OK.

**I guess there should be limits for both senders and receivers**, because it could just as well be the case that we don't want a `sink` to be overrun by a very fast `push` job.

Do you think it would be necessary to adjust the bandwidth limit during replication? Or would a daemon restart be acceptable for such a config change?

**Comment by candlerb** [comment]
Given that we now have resume, a restart would be acceptable - but being able to control it via zrepl command to the daemon would be a nice feature.  I can imagine increasing the rate overnight and reducing it again in the morning, for instance.

**Comment by oninoshiko** [comment]
(I've just started testing zrepl a couple weeks ago, and using it for real a couple days ago, so take that into account)

> Given that we now have resume, a restart would be acceptable - but being able to control it via zrepl command to the daemon would be a nice feature. I can imagine increasing the rate overnight and reducing it again in the morning, for instance.

This is a big deal for us. While resume works, live adjustment would be ideal. The exact scenario of slowing it during peak usage periods (particularly for large initial transfers) has already been discussed. That said, doing this in two phases makes sense to me: controlled by config & restart, then adding a daemon command.

I think config for the active side is pretty straight forward (just add a "rate: 10m"  to the yaml config). 

Receivers, not so much. Is the receiver limit a per rule limit or a per connection limit? I think a per-rule limit makes the most sense, then it would divide that equally among connections. If you want to have one that's got a different limit, make a different rule for it.

**Comment by problame** [comment]
> hink config for the active side is pretty straight forward (just add a "rate: 10m" to the yaml config).
> 
> Receivers, not so much. Is the receiver limit a per rule limit or a per connection limit? I think a per-rule limit makes the most sense, then it would divide that equally among connections. If you want to have one that's got a different limit, make a different rule for it.
> 

The rate limiters I found in my [implementation advice above](https://github.com/zrepl/zrepl/issues/339#issuecomment-647455603) are basically transparent wrappers around `net.Conn`. If we want to support a more global form of rate limitng, i.e.
* a global, evenly distributed rate limited among all incoming sends for a `sink`
* parallel replication (=multiple simultaneous TCP connections per sender-receiver-job pair)
then things get way more complicated (in essence we'd need to implement HTB or something similar).

**Comment by problame** [comment]
I'm working on this.

**Comment by problame** [comment]
I just published the PR: https://github.com/zrepl/zrepl/pull/506

**Comment by problame** [comment]
@candlerb, could you give the PR a shot? It's basically zrepl 0.4, very low risk to try in production. See the PR's initial comment for instructions.

**Comment by candlerb** [comment]
Sorry, I'm afraid I've stopped using zrepl in production; syncoid works much better for my use case (especially in avoiding stuck replication)
