### ISSUE TITLE
zrepl makes resumable send off bookmark even though it shouldn't which then fails subsequent attempts

### ISSUE THREAD

**Issue by JMoVS** [zrepl/zrepl#352]
I had on my external media disk around 30GB of new media, and due to active snapshotting only never snapshots than the one on the destination. zrepl correctly found that it could resume from the bookmark and started doing so.

My config contains the option "guarantee_incremental", which means there shouldn't be any resumability used. The source and destination are long paired, so it's about an incremental send based off of a snapshot.

Now as zrepl snapshots this disk every 10m, it constantly produces new snapshots. What happened though is that initially it started with an incremental send from the bookmark to the destination. When I checked back some time later, I instead saw the error `(step 0/0, 0 B/0 B) resumable send cli support feature check failed: context canceled     `.

I then checked the dataset on the destination and found that there was a resumable send token on the dataset. After I manually deleted that token with `zfs recv -A`, a new attempt worked again - until it failed in the same way.

My current workaound is to switch to guarantee_resumability until the big transfer is done and then switch back to guarantee_incremental.

**Comment by problame** [comment]
> My config contains the option "guarantee_incremental", which means there shouldn't be any resumability used.

That's not what the flag is about. It's just about what is being guaranteed, i.e. with `guarantee_incremental`, you will be guaranteed that incremental replication is always possible through the use of bookmarks, but not that an interrupted replication is always resumable, because that would require a zfs hold on the `to` snapshot of an active replication step, which is what `guarantee_resumability` does.

> Now as zrepl snapshots this disk every 10m, it constantly produces new snapshots. What happened though is that initially it started with an incremental send from the bookmark to the destination. When I checked back some time later, I instead saw the error (step 0/0, 0 B/0 B) resumable send cli support feature check failed: context canceled .

> I then checked the dataset on the destination and found that there was a resumable send token on the dataset. After I manually deleted that token with zfs recv -A, a new attempt worked again - until it failed in the same way.

> My current workaound is to switch to guarantee_resumability until the big transfer is done and then switch back to guarantee_incremental.

The incremental send you are talking about: is it `zfs send -nvt TOKEN`...? Or `zfs send -t TOKEN`?

**Comment by JMoVS** [comment]
ok, still. zrepl worked again when I cleared the resumable send token from the receiver.

`zfs send -nvt TOKEN` is only a dry run and not a real send. All I observed was that zrepl correctly attempted to send incremental based on a bookmark, failed and then failed to clear the resumable state on the receiver, thereby preventing a new send from happening.

**Comment by problame** [comment]
Please send zrepl debug logs, including a rough timestamp of when the error occurred in the logs.

**Comment by problame** [comment]
Also, you didn't answer the question: is it an actual send or a dry sen

**Comment by JMoVS** [comment]
I cannot really reproduce the issue right now also because of lack of time, and it also didn't occur again (but I also don't have the same large amount of data that triggered it last time - likely because replication took longer than the snapshotting interval).
