### ISSUE TITLE
flaky platform tests on fast systems / systems without other pool + panic in ReceiveForceIntoEncryptedErr

### ISSUE THREAD

**Issue by johnramsden** [zrepl/zrepl#358]
# Summary

What should be done about platform test failures? I received the following test failures on Arch Linux:

```
FAILED TESTS:
  github.com/zrepl/zrepl/platformtest/tests.ReplicationIncrementalCleansUpStaleAbstractionsWithCacheOnSecondReplication
  github.com/zrepl/zrepl/platformtest/tests.ReplicationIncrementalCleansUpStaleAbstractionsWithoutCacheOnSecondReplication
  github.com/zrepl/zrepl/platformtest/tests.ReplicationIncrementalDestroysStepHoldsIffIncrementalStepHoldsAreDisabledButStepHoldsExist
  github.com/zrepl/zrepl/platformtest/tests.ReplicationStepCompletedLostBehavior__GuaranteeIncrementalReplication
  github.com/zrepl/zrepl/platformtest/tests.ReplicationStepCompletedLostBehavior__GuaranteeResumability
```

How can I help to debug these?

**Comment by problame** [comment]
```
[ERRO][repl][syFD$vjvk$vjvk.Azou]: conflict filesystem="zreplplatformtest/rootds/sender" conflict="no common snapshot or suitable bookmark between sender and receiver:\n  sorted sender versions:\n    @1\n    #2\n    #zrepl_CURSOR_G_5cb6bea94b64307f_J_other-job\n    #zrepl_CURSOR_G_5cb6bea94b64307f_J_sender-job\n    @2\n    #zrepl_CURSOR_G_1e26d06640b203d5_J_sender-job\n    @3\n    @4\n    @5\n  sorted receiver versions:\n    @3\n"
```

That seems pretty odd, `@3` should have been identified as common ancestor.

**Comment by problame** [comment]
I'm pretty sure the failures are due to https://github.com/zrepl/zrepl/issues/346, working on that now.

**Comment by problame** [comment]
The

```
panic: end task: 1 active child tasks: end task: task still has active child tasks

goroutine 1 [running]:
github.com/zrepl/zrepl/daemon/logging/trace.WithTask.func1.1(0xc000020680, 0xc000080f00)
	/home/cs/zrepl/zrepl/daemon/logging/trace/trace.go:221 +0x2f7
github.com/zrepl/zrepl/daemon/logging/trace.WithTask.func1()
	/home/cs/zrepl/zrepl/daemon/logging/trace/trace.go:237 +0x38
main.HarnessRun(0x7ffe0b49ad3a, 0x11, 0x7ffe0b49acf2, 0x1a, 0xc800000, 0x7ffe0b49ad19, 0x16, 0x1, 0x0, 0x0, ...)
	/home/cs/zrepl/zrepl/platformtest/harness/harness.go:168 +0xe54
main.main()
	/home/cs/zrepl/zrepl/platformtest/harness/harness.go:41 +0x2ef

```

is not related to #346

**Comment by problame** [comment]
@johnramsden could you try the head of branch `problame/develop` ? I believe I fixed both the flaky tests and the panic in that branch.

**Comment by johnramsden** [comment]
It was running on a system with an existing pool as the root file system. 

`problame/develop` passed all tests [zrepl.platformtest.develop.log](https://github.com/zrepl/zrepl/files/5114909/zrepl.platformtest.develop.log). 

```
make test-platform-bin && make test-platform 
``` 

So only the tests were affected? If the `problame/develop` tests pass, I should assume the Arch Linux platform is good?

Thanks @problame

**Comment by problame** [comment]
Please invoke the tests directly using the `artifacts/platformtest-linux-amd64` binary instead of the `test-platform` makefile target.
The Makefile adds an intermediary mock `zfs` command to the mix.

> So only the tests were affected?
>  If the problame/develop tests pass, I should assume the Arch Linux platform is good?

Yes, and it wasn't specific to Arch.

**Comment by johnramsden** [comment]
All good [zrepl.platformtest.develop.log](https://github.com/zrepl/zrepl/files/5115049/zrepl.platformtest.develop.log)
