### ISSUE TITLE
Update from grafana 7.1.3 to 7.1.4 breaks Failed replication metric

### ISSUE THREAD

**Issue by jwittlincohen** [zrepl/zrepl#363]
After upgrading from grafana 7.1.3 to 7.1.4 on my Debian Buster system with zrepl 0.3-rc2 (patched for zfs send -Lce support), Grafana reported "No Data" for the Failed replication field.  I also see the following potentially relevant output in syslog.  No errors are reported when I install 7.1.3.

`Aug 23 17:05:10 storage-server grafana-server[25212]: t=2020-08-23T17:05:10-0400 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=1 orgId=1 uname=admin path=/api/datasources/proxy/1/api/v1/query_range remote_addr=192.168.1.2 referer="http://192.168.1.200:3000/d/etQuvBnGz/zrepl-0-3-new?orgId=1&refresh=5s&var-prom_job_name=prometheus&var-zrepl_job_name=$__all&from=now-7d&to=now" error="http: proxy error: context canceled"
Aug 23 17:05:10 storage-server grafana-server[25212]: t=2020-08-23T17:05:10-0400 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=1 orgId=1 uname=admin path=/api/datasources/proxy/1/api/v1/query_range remote_addr=192.168.1.2 referer="http://192.168.1.200:3000/d/etQuvBnGz/zrepl-0-3-new?orgId=1&refresh=5s&var-prom_job_name=prometheus&var-zrepl_job_name=$__all&from=now-7d&to=now" error="http: proxy error: context canceled"
Aug 23 17:05:10 storage-server grafana-server[25212]: t=2020-08-23T17:05:10-0400 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=1 orgId=1 uname=admin path=/api/datasources/proxy/1/api/v1/query_range remote_addr=192.168.1.2 referer="http://192.168.1.200:3000/d/etQuvBnGz/zrepl-0-3-new?orgId=1&refresh=5s&var-prom_job_name=prometheus&var-zrepl_job_name=$__all&from=now-7d&to=now" error="http: proxy error: context canceled"
Aug 23 17:05:10 storage-server grafana-server[25212]: t=2020-08-23T17:05:10-0400 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=1 orgId=1 uname=admin path=/api/datasources/proxy/1/api/v1/query_range remote_addr=192.168.1.2 referer="http://192.168.1.200:3000/d/etQuvBnGz/zrepl-0-3-new?orgId=1&refresh=5s&var-prom_job_name=prometheus&var-zrepl_job_name=$__all&from=now-7d&to=now" error="http: proxy error: context canceled"
Aug 23 17:05:10 storage-server grafana-server[25212]: t=2020-08-23T17:05:10-0400 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/1/api/v1/query_range status=502 remote_addr=192.168.1.2 time_ms=101 size=0 referer="http://192.168.1.200:3000/d/etQuvBnGz/zrepl-0-3-new?orgId=1&refresh=5s&var-prom_job_name=prometheus&var-zrepl_job_name=$__all&from=now-7d&to=now"
Aug 23 17:05:10 storage-server grafana-server[25212]: t=2020-08-23T17:05:10-0400 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/1/api/v1/query_range status=502 remote_addr=192.168.1.2 time_ms=63 size=0 referer="http://192.168.1.200:3000/d/etQuvBnGz/zrepl-0-3-new?orgId=1&refresh=5s&var-prom_job_name=prometheus&var-zrepl_job_name=$__all&from=now-7d&to=now"
Aug 23 17:05:10 storage-server grafana-server[25212]: t=2020-08-23T17:05:10-0400 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/1/api/v1/query_range status=502 remote_addr=192.168.1.2 time_ms=63 size=0 referer="http://192.168.1.200:3000/d/etQuvBnGz/zrepl-0-3-new?orgId=1&refresh=5s&var-prom_job_name=prometheus&var-zrepl_job_name=$__all&from=now-7d&to=now"
Aug 23 17:05:10 storage-server grafana-server[25212]: t=2020-08-23T17:05:10-0400 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/1/api/v1/query_range status=502 remote_addr=192.168.1.2 time_ms=63 size=0 referer="http://192.168.1.200:3000/d/etQuvBnGz/zrepl-0-3-new?orgId=1&refresh=5s&var-prom_job_name=prometheus&var-zrepl_job_name=$__all&from=now-7d&to=now"
Aug 23 17:05:10 storage-server grafana-server[25212]: t=2020-08-23T17:05:10-0400 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=1 orgId=1 uname=admin path=/api/datasources/proxy/1/api/v1/query_range remote_addr=192.168.1.2 referer="http://192.168.1.200:3000/d/etQuvBnGz/zrepl-0-3-new?orgId=1&refresh=5s&var-prom_job_name=prometheus&var-zrepl_job_name=$__all&from=now-7d&to=now" error="http: proxy error: context canceled"
Aug 23 17:05:10 storage-server grafana-server[25212]: t=2020-08-23T17:05:10-0400 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/1/api/v1/query_range status=502 remote_addr=192.168.1.2 time_ms=4 size=0 referer="http://192.168.1.200:3000/d/etQuvBnGz/zrepl-0-3-new?orgId=1&refresh=5s&var-prom_job_name=prometheus&var-zrepl_job_name=$__all&from=now-7d&to=now"
Aug 23 17:05:26 storage-server grafana-server[25212]: t=2020-08-23T17:05:26-0400 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/1/api/v1/metadata status=405 remote_addr=192.168.1.2 time_ms=1 size=19 referer="http://192.168.1.200:3000/d/etQuvBnGz/zrepl-0-3-new?editPanel=50&viewPanel=50&orgId=1&refresh=5s&var-prom_job_name=prometheus&var-zrepl_job_name=$__all&from=now-7d&to=now"
Aug 23 17:05:40 storage-server grafana-server[25212]: t=2020-08-23T17:05:40-0400 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/1/api/v1/metadata status=405 remote_addr=192.168.1.2 time_ms=2 size=19 referer="http://192.168.1.200:3000/d/etQuvBnGz/zrepl-0-3-new?editPanel=50&viewPanel=50&orgId=1&refresh=5s&var-prom_job_name=prometheus&var-zrepl_job_name=$__all&from=now-7d&to=now"
Aug 23 17:08:49 storage-server grafana-server[15491]: t=2020-08-23T17:08:49-0400 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=1 orgId=1 uname=admin path=/api/datasources/proxy/1/api/v1/query_range remote_addr=192.168.1.2 referer="http://192.168.1.200:3000/d/etQuvBnGz/zrepl-0-3-new?orgId=1&refresh=5s&var-prom_job_name=prometheus&var-zrepl_job_name=$__all&from=now-15m&to=now" error="http: proxy error: context canceled"
Aug 23 17:08:49 storage-server grafana-server[15491]: t=2020-08-23T17:08:49-0400 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/1/api/v1/query_range status=502 remote_addr=192.168.1.2 time_ms=36 size=0 referer="http://192.168.1.200:3000/d/etQuvBnGz/zrepl-0-3-new?orgId=1&refresh=5s&var-prom_job_name=prometheus&var-zrepl_job_name=$__all&from=now-15m&to=now"
Aug 23 17:08:49 storage-server grafana-server[15491]: t=2020-08-23T17:08:49-0400 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=1 orgId=1 uname=admin path=/api/datasources/proxy/1/api/v1/query_range remote_addr=192.168.1.2 referer="http://192.168.1.200:3000/d/etQuvBnGz/zrepl-0-3-new?orgId=1&refresh=5s&var-prom_job_name=prometheus&var-zrepl_job_name=$__all&from=now-15m&to=now" error="http: proxy error: context canceled"
Aug 23 17:08:49 storage-server grafana-server[15491]: t=2020-08-23T17:08:49-0400 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/1/api/v1/query_range status=502 remote_addr=192.168.1.2 time_ms=0 size=0 referer="http://192.168.1.200:3000/d/etQuvBnGz/zrepl-0-3-new?orgId=1&refresh=5s&var-prom_job_name=prometheus&var-zrepl_job_name=$__all&from=now-15m&to=now"
Aug 23 17:11:15 storage-server grafana-server[16011]: t=2020-08-23T17:11:15-0400 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=1 orgId=1 uname=admin path=/api/datasources/proxy/1/api/v1/query_range remote_addr=192.168.1.2 referer="http://192.168.1.200:3000/d/etQuvBnGz/zrepl-0-3-new?orgId=1&refresh=5s&var-prom_job_name=prometheus&var-zrepl_job_name=$__all&from=now-30m&to=now" error="http: proxy error: context canceled"
Aug 23 17:11:15 storage-server grafana-server[16011]: t=2020-08-23T17:11:15-0400 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/1/api/v1/query_range status=502 remote_addr=192.168.1.2 time_ms=23 size=0 referer="http://192.168.1.200:3000/d/etQuvBnGz/zrepl-0-3-new?orgId=1&refresh=5s&var-prom_job_name=prometheus&var-zrepl_job_name=$__all&from=now-30m&to=now"
`

After uninstalling grafana 7.1.4 and installing the prior 7.1.3 release, the Failed replication field now showed all my jobs as "ALL OK."  I've included photos of the output with 7.1.4 and 7.1.3 below:

![IMG_5616](https://user-images.githubusercontent.com/9561645/90989231-12eaee80-e567-11ea-8302-31d9b2c26aca.PNG)
![IMG_5617](https://user-images.githubusercontent.com/9561645/90989232-13838500-e567-11ea-9d1e-341c15fac381.PNG)

**Comment by jwittlincohen** [comment]
I saw that at least one of the commits between 0.3.0-rc2 and 0.3.0 related to the grafana dashboard.  Therefore, I rebuilt zrepl from master and added support for -Lce.  Same behavior.  Works fine with 7.1.3.  "No Data" for Failed replication with 7.1.4.

**Comment by problame** [comment]
Did you check whether re-selecting the Prometheus data source on 7.1.4 fixes the problem? Was it just the 'Failed replications' metric or all metrics exposed by zrepl? (The log lines metric should always have some spikes per replication invocation).

**Comment by jwittlincohen** [comment]
Yeah, I selected the Prometheus data source.  All the other metrics
reported correctly on 7.1.4.  It was just the Failed Replications metric
that showed No Data.

**Comment by problame** [comment]
I can confirm the issue.

**Comment by problame** [comment]
There is a button that says **Migrate to Stat panel**.
If you click it, the panel works again.

**Comment by problame** [comment]
![image](https://user-images.githubusercontent.com/956573/91224115-e7f8ca00-e721-11ea-9ff4-9c4a2448d81d.png)

**Comment by problame** [comment]
@schulzh How old is this new 'Stat' panel type? I.e., could we export a new .json from Grafana 7.1.4, commit it to the zrepl repo and have it still work on ~1.5 to 2 year old Grafana installs? (I want to avoid maintaining two Grafana dashboard versions in parallel.)

**Comment by problame** [comment]
Actually, the Grafana feature "repeat-by-variable" seems to be broken in 7.1.4.

To me it seems like this is a regression in Grafana.
I can't re-create the panel myself either.

@schulzh any ideas about this / could you take this issue upstream?

**Comment by jwittlincohen** [comment]
It appears this issue was fixed by https://github.com/grafana/grafana/pull/27151

The Failed Replication metric is now working with 7.1.5.
