### ISSUE TITLE
armhf package missing from Debian repo

### ISSUE THREAD

**Issue by awehrfritz** [zrepl/zrepl#364]
Following the installation instruction (https://zrepl.github.io/installation/packages.html and https://zrepl.github.io/installation/apt-repos.html), fails eventually with an `E: Unable to locate package zrepl` error.

It appears the [Debian repo](https://zrepl.cschwarz.com/apt/debian/pool/main/z/zrepl/) is missing the respective package, even though the package is available via [GitHub](https://github.com/zrepl/zrepl/releases/download/v0.3.0/zrepl_0.3.0_armhf.deb).

Could you please include the armhf architecture in the Debian repo?

**Comment by problame** [comment]
Done, thanks for the reminder! 
Please report back whether it works for you.

**Comment by awehrfritz** [comment]
Repo is down at the moment:
```
W: Failed to fetch https://zrepl.cschwarz.com/apt/debian/dists/buster/InRelease  Cannot initiate the connection to zrepl.cschwarz.com:443 (2a01:4f8:150:33d3:1::6). - connect (101: Network is unreachable) Could not connect to zrepl.cschwarz.com:443 (176.9.31.194), connection timed out
```

**Comment by awehrfritz** [comment]
OK, the repo seems to work again.

Also installing zrepl via the repo on armhf works now.

**Comment by problame** [comment]
Repo downtime was due to Hetzner outage.
