### ISSUE TITLE
[Feature request] Provide packages/build instructions for the major Linux distributions

### ISSUE THREAD

**Issue by awehrfritz** [zrepl/zrepl#366]
This is a feature request out of the frustration that has been piling up when trying to get `zrepl` installed on my Fedora Linux laptop as well as a Helios4 NAS running Debian Buster (with an Armbian ARMv7 kernel).

Little bit of background to elaborate on this request: The installation instruction for Fedora provided in the [docs](https://zrepl.github.io/installation/packages.html) refer to a Fedora [copr repo](https://copr.fedorainfracloud.org/coprs/poettlerric/zrepl/) which contains an outdated version. I then had a quick look at the spec file to update the package and realised that the spec file is more of a hack, required patches already for the outdated version, and would not work for the latest `zrepl` version. I then had an attempt to rewrite the spec from scratch following the latest Fedora [go packaging guidelines](https://docs.fedoraproject.org/en-US/packaging-guidelines/Golang/), but I could not get it to work. Eventually, I looked at the [Makefile](https://github.com/zrepl/zrepl/blob/master/Makefile) (and [lazy.sh](https://github.com/zrepl/zrepl/blob/master/lazy.sh)) just to realise that this is all quite involved. I have no experience with Go, and thus cannot judge whether this is normal or not for Go, but I am working with with huge C++/Fortran projects (>1M lines of code) which are by far easier to build than this.

I understand that it is an additional effort to generate packages for downstream Linux distributions, but I believe it would make it at the same time much easier for the users to adopt the software. Also considering that a reasonably small Go-project like this really does not require much in terms of packaging, but apparently a lot of effort to get it compiled (simply judging by the convoluted Makefile). Furthermore, with services like Fedora's [copr](https://copr.fedorainfracloud.org/coprs/), openSUSE's [Open Build Service](https://build.opensuse.org/) and Ubuntu's [ppa](https://launchpad.net/ubuntu/+ppas) one can target already the vast majority of Linux users in an easy way (the .spec file for Fedora/RedHat and openSUSE/SUSE would probably even very similar).

I understand that `zrepl` itself is simply a binary and thus quite easy to distribute, but it comes in handy to have things like systemd service and bash-completion files installed in the appropriate places together with the binary itself, hence this feature request.

In the meantime, I resorted on my Fedora laptop to a simple shell script which pulls the binary and systemd-service file from GitHub and generates the bash-completion file on the fly. This is obviously not really how things should be done in the 21st-century, but it turns out that's the easiest way to get the latest `zrepl` version installed on Fedora.

**Comment by awehrfritz** [comment]
In case it helps any, the original Fedora .spec file from the copr repo mentioned above is here: https://github.com/poettler-ric/fedora-spec/blob/master/zrepl/zrepl.spec

My poor attempts to fix this are here: https://github.com/awehrfritz/zrepl-rpm/blob/5c93b743c72d97f26e8fbd14cf5ea38c73502115/zrepl.spec

**Comment by problame** [comment]
For starters, there is https://github.com/zrepl/debian-binary-packaging which I use to generate the .deb packages.

I think #350  (Makefile `install` target) is a prerequisite to a simpler packaging workflow because the various helper scripts (e.g. deb-helper) would automatically use that target.

After we have `make install`, I guess the main issue is dependency management.
ATM, we let the Go toolchain do the work.
Would you like to change that?

**Comment by awehrfritz** [comment]
Thanks for your swift response @problame - much appreciated! My apologies if my early statements came off a bit harsh, I was simply frustrated since nothing but a good 'ole shell scripted worked.

> For starters, there is https://github.com/zrepl/debian-binary-packaging which I use to generate the .deb packages.

It indeed seems you have the Debian/Ubuntu (and derivatives) covered with this. I personally keep my Debian usage to a minimum (i.e. Armbian) and have always preferred rpm-based distributions. One reason for that is package management, rpm is just such a nice package format and Fedora's `dnf` the best package management tool I have come across so far in 15+ years of using Linux.


> I think #350 (Makefile `install` target) is a prerequisite to a simpler packaging workflow because the various helper scripts (e.g. deb-helper) would automatically use that target.

This sounds useful. Thanks for pointing this out!


> After we have `make install`, I guess the main issue is dependency management.
> ATM, we let the Go toolchain do the work.
> Would you like to change that?

I guess my biggest issue with the current build process is indeed dependency management. This was actually also the first breaking point when I wrote a clean and up-to-date spec-file for Fedora copr. As said, I have virtually no experience in working with Go, but from what I understood so far most Go dependencies are source code only and Fedora's copr can handle those easily, see [Dependencies](https://docs.fedoraproject.org/en-US/packaging-guidelines/Golang/#_dependencies) in the Fedora docs. It seems the culprit here was the stuff that happens in [lazy.sh](https://github.com/zrepl/zrepl/blob/master/lazy.sh), which leads to an "unusual" Go build and cannot be mapped to the typical `%gobuild` macros typically used in rpm-based distributions.

Maybe I went about this the wrong way when trying to follow the Go packaging guidelines, and maybe it would be easier to just accept that `zrepl` is more complicated to build and rely on whatever you decide to implement for `make` and `make install`.

I guess what would help is a clarification on what is done in [lazy.sh](https://github.com/zrepl/zrepl/blob/master/lazy.sh) and why that cannot be induced directly in the Makefile. This seems to be the major source of my tribulations. Though it seems the [Arch Linux package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=zrepl) gets away without using nay of this.

**Comment by awehrfritz** [comment]
Just a quick follow up on this issue: I had another look at this and have a better understanding of the Go's (quite convoluted) dependency handling.

Anyway, once I figured where the problem is, the fix was easy. I put this all in one [spec file](https://github.com/awehrfritz/zrepl-rpm/blob/master/zrepl.spec) which works for a whole range of distributions. I tested this on [Fedora's copr build service](https://copr.fedorainfracloud.org/) and in my project ([awehrfritz/zrepl](https://copr.fedorainfracloud.org/coprs/awehrfritz/zrepl/)) are now packages for:
- epel-8-x86_64
- fedora-31-x86_64
- fedora-32-x86_64
- fedora-33-x86_64
- fedora-rawhide-x86_64
- opensuse-leap-15.2-x86_64

I should note that this spec file also works for opensuse-leap-15.1-x86_64, however, since this is "near end of life" I did not enable the build. Also, I didn't bother to get this working with epel-6-x86_64 or epel-7-x86_64 as it would require further hacks/if-then-else constructs and make the spec file even more complex than it already is.

@problame: I would like to add the [zrepl.spec](https://github.com/awehrfritz/zrepl-rpm/blob/master/zrepl.spec) file to the zrepl repository as it required some hacks to get zrepl installed in an standard conform way. Since this is prone to fail with future changes in zrepl, I believe this should be maintained in the same repository as the Makefile itself. I propose to put this to a subdirectory, e.g. `rpm` or `packaging/rpm`.

**Comment by problame** [comment]
This .spec file looks somewhat like I had in mind for when we have the `make install` target.

I played around with the .spec and built it on my Fedora 31 Workstation. What I found missing:
- [ ] How to obtain `~/rpmbuild/SOURCES/zrepl-0.3.0.tar.gz`
  I used ` git archive --prefix zrepl-0.3.0/ HEAD > ~/rpmbuild/SOURCES/zrepl-0.3.0.tar.gz`
- [ ] Generate HTML documentation using sphinx (`make docs`)
 That adds a bunch of build dependencies, also 'documented' in lazy.sh.

> @problame: I would like to add the zrepl.spec file to the zrepl repository as it required some hacks to get zrepl installed in an standard conform way. Since this is prone to fail with future changes in zrepl, I believe this should be maintained in the same repository as the Makefile itself. I propose to put this to a subdirectory, e.g. rpm or packaging/rpm.

All for it, I think integrating the rpm build into the CI would be beneficial as well, in order to ensure that we don't break package builds during development.

Would you be willing to work on this and open a PR?
- [ ] Add a `make rpm` target that takes care of
  - generating the tarball `git archive --prefix zrepl-0.3.0/ HEAD > ~/rpmbuild/SOURCES/zrepl-0.3.0.tar.gz` (can we put it in a tmpdir and tell rpmbuild to look for sources there?)
  - invoking `rpmbuild`
  - copying the generated artifact to `artifacts/`
- [ ] Create the .config/circleci.yml job for RPM builds.
  AFAIK, you could just use the Fedora Docker image, build the RPM in there, then use that RPM on all RPM-like platforms. Right? (We should probably add `CGO_ENABLED=0` to the Makefile for that)

**Comment by poettler-ric** [comment]
@awehrfritz would you mind updating the installation [instruction](https://zrepl.github.io/installation/packages.html) to refer to your repository? I then officially would retire my copr zrepl repository.

**Comment by poettler-ric** [comment]
@awehrfritz keep in mind most people are using CentOS 7 (which is also the reason why "the spec file is more of a hack").

**Comment by awehrfritz** [comment]
@poettler-ric I see your point with RHEL/CentOS 7 as the distribution is indeed still quite relevant in an enterprise environment, and it's probably reasonable to include those "hacks" eventually. One of the reasons why I held off with adding additional complexity to the spec file was your bug report in #367. I think we should first fix that and then add RHEL/CentOS 7 as a build target.

@problame I will need to give this some though and get back to you. I think sorting out the `make rpm` part is reasonably straight forward. What I have no idea about is circleci.

> AFAIK, you could just use the Fedora Docker image, build the RPM in there, then use that RPM on all RPM-like platforms. Right? 

Well, I guess that could be an option. Though I have never done it that way. But I guess one of the advantages of using Go is that the binaries are standalone and thus portable. Hosting a private rpm repo is not too difficult, as far as I can tell it mainly requires a .repo file and the rpms it self.

> (We should probably add `CGO_ENABLED=0` to the Makefile for that)

I don't understand what `CGO_ENABLED=0` does.

**Comment by problame** [comment]
> I don't understand what CGO_ENABLED=0 does.

It makes the Go compiler produce a static binary. Otherwise, at least for linux, it produces a binary that links all the _Go_ code statically but otherwise still links against ld-linux (not libc though)
