### ISSUE TITLE
last_n: support `regex` field

### ISSUE THREAD

**Issue by problame** [zrepl/zrepl#373]
Originally mentioned in https://github.com/zrepl/zrepl/issues/292#issuecomment-683689530

**Comment by problame** [comment]
@Ranlvor I just pushed a commit that implements this feature. It should show up above this message. Please test it and report back (I recommend to test with a `snap` job that doesn't match production `filesystems`).

**Comment by Ranlvor** [comment]
Just tested it and the result looks good. It works as expected.
