### ISSUE TITLE
binary release process: find a way to issue updated binary releases

### ISSUE THREAD

**Issue by problame** [zrepl/zrepl#374]
Originating from discussion in https://github.com/zrepl/zrepl/pull/369#issuecomment-683450959

Proposal for release procedure:

** Code Release

- Create Git Tag `$SRC_VERSION`
- Goto **Binary Release**

** Binary Release for source version `$SRC_VERSION`
- Determine Go semver, e.g. for Go 1.15.3 => GO_VERSION=1.15.3
- Create Git Tag `$SRC_VERSION-go$GO_VERSION`
- CI destructures the Git Tag => SRC_VERSION is redundant, GO_VERSION is used to select the Go compiler version / Go docker image
- CI builds a release in Docker (`make release` in Docker)
- CI builds deb and rpm in Docker

@awehrfritz comments?

**Comment by awehrfritz** [comment]
Sounds overall reasonable to me. Not that I would have much experience with this though.

The only thing I am not quite understanding is the reasoning behind destroying the `$SRC_VERSION-go$GO_VERSION` tag. Wouldn't it make sense to keep that for reference?

**Comment by problame** [comment]
Destructuring, not destroying: https://riptutorial.com/python/example/14981/destructuring-assignment

**Comment by problame** [comment]
It turns out it's much simpler to do the following:

* create a branch `releases/0.6.1-2` off the release tag
* that branch will never be merged
* make a commit there that bumps the package epoch
* git tag
* release pipeline run + publish GH release as usual

Close this issue after documenting the procedure in README.md
