### ISSUE TITLE
zrepl protocol version mismatch

### ISSUE THREAD

**Issue by hydro-b** [zrepl/zrepl#376]
Since I upgraded both the source and sink servers to zrepl 0.3.0 I get this error:

accept error subsystem="transportmux" errType="*versionhandshake.HandshakeError" err="protocol versions do not match: ours is 1, theirs is 5"
^^ pull_source (zfs 0.8.3, now 0.8.4 but same issue on x86_64)

Sep  2 07:39:22 rp4 zrepl[3534]: [pull_servers][rpc.data][0W/s$bREN$G3mV$G3mV.Xdf7]: ping failed err="protocol versions do not match: ours is 5, theirs is 1"
Sep  2 07:39:22 rp4 zrepl[3534]: [pull_servers][rpc.ctrl][0W/s$bREN$G3mV$G3mV.Xdf7]: ping failed err="rpc error: code = Canceled desc = context canceled"

^^ pull_servers (zfs 0.8.3, arm64)

**Comment by problame** [comment]
Did you restart the daemons on both sides?

**Comment by hydro-b** [comment]
Yes, I'm sure (I double check my logs). But ... look at this:

On pull_servers node:
```
/usr/bin# ./zrepl version
client: zrepl version=v0.3.0 GOOS=linux GOARCH=arm64 Compiler=gc
server: zrepl version=v0.3.0 GOOS=linux GOARCH=arm64 Compiler=gc
Connecting to pull_source with telnet: 0000000056 ZREPL_ZFS_REPLICATION PROTOVERSION=0001 EXTENSIONS=0000
```

On pull_source:
```
/usr/bin# ./zrepl version
client: zrepl version=v0.3.0 GOOS=linux GOARCH=amd64 Compiler=gc
server: zrepl version=v0.1.1-3-g234a327 GOOS=linux GOARCH=amd64 Compiler=gc
WARNING: client version != daemon version, restart zrepl daemon
```
So that's the issue. But how? Because I installed zrepl from your repo:
```
apt policy zrepl
zrepl:
  Installed: 0.3.0
  Candidate: 0.3.0
  Version table:
 *** 0.3.0 500
        500 https://zrepl.cschwarz.com/apt/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     0.2.1 500
        500 https://zrepl.cschwarz.com/apt/ubuntu bionic/main amd64 Packages
     0.2.0-1 500
        500 https://zrepl.cschwarz.com/apt/ubuntu bionic/main amd64 Packages
     0.2.0 500
        500 https://zrepl.cschwarz.com/apt/ubuntu bionic/main amd64 Packages
```

I removed the zrepl binary in /usr/bin and reinstalled the package (apt install zrepl --reinstall), but still the same issue. The binary contains both the client and server functionality, right?

**Comment by problame** [comment]
The server is running as the systemd zrepl.service which is installed by the Debian package.  Debian package updates do update the binary but don't update th daemon. That's a general rule for all debian packages except for those where the maintainers put special maintainer scripts in place to do it for you.

Learn more about how zrepl works

**Comment by hydro-b** [comment]
> The server is running as the systemd zrepl.service which is installed by the Debian package. Debian package updates do update the binary but don't update th daemon. That's a general rule for all debian packages except for those where the maintainers put special maintainer scripts in place to do it for you.
> 
> Learn more about how zrepl works

Sure, that never can hurt.

But It wasn't the problem here however. I installed zrepl here before it was shipped as a debian package, and also had my own systemd unit file for it (proably copy pasted from the documentation). The location of the binary was /usr/local/bin/zrepl. The zrepl package puts the binary in /usr/bin/zrepl. That binary wasn't used. After removing the zrepl unit file from "/etc/systemd/system/zrepl" and re-enabling the "vendor" unit file it all works as expected.

Thanks for your comment as it did remind me to check the unit file of the service.
