### ISSUE TITLE
installing plugin on TrueNAS stalls

### ISSUE THREAD

**Issue by Zixim** [zrepl/zrepl#393]
leaving all settings to their defaults, all i get is a progress window stating 
```
Install
20.00%
Initial validation complete
```
![image](https://user-images.githubusercontent.com/7814664/95650454-1c62f280-0ae4-11eb-8d91-fc6b8ff8d2bf.png)
It doesn't move...

**Comment by problame** [comment]
Cc @johnramsden

**Comment by Zixim** [comment]
ehh...my bad, hadn't first created the dataset to be delegated.
