### ISSUE TITLE
"zrepl test placeholder" panics for non-existent datasets

### ISSUE THREAD

**Issue by candlerb** [zrepl/zrepl#406]
```
root@brian-kit:~# zrepl test placeholder --dataset tgt/zrepl
IS_PLACEHOLDER	DATASET	zrepl:placeholder
no	tgt/zrepl
root@brian-kit:~# zrepl test placeholder --dataset tgt/zrepl/foo/bar
IS_PLACEHOLDER	DATASET	zrepl:placeholder
panic: placeholder state inconsistent: filesystem tgt/zrepl/foo/bar must exist in this context

goroutine 1 [running]:
github.com/zrepl/zrepl/client.runTestPlaceholder(0xdd2420, 0xc0003769c0, 0x121e5c0, 0xc00000e9a0, 0x0, 0x2, 0x4, 0x3)
	/src/client/testcmd.go:174 +0x6f9
github.com/zrepl/zrepl/cli.(*Subcommand).run(0x121e5c0, 0xc00034c000, 0xc00000e9a0, 0x0, 0x2)
	/src/cli/cli.go:105 +0xe2
github.com/spf13/cobra.(*Command).execute(0xc00034c000, 0xc00000e960, 0x2, 0x2, 0xc00034c000, 0xc00000e960)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.2/command.go:760 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x1220620, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.2/command.go:846 +0x2fe
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.2/command.go:794
github.com/zrepl/zrepl/cli.Run()
	/src/cli/cli.go:152 +0x2d
main.main()
	/src/main.go:24 +0x25

```

Looking at the [source code](https://github.com/zrepl/zrepl/blob/master/client/testcmd.go#L173), it looks like this was done intentionally. However I think it's confusing: panics should be reserved for internal errors and software bugs.

In this case, the user supplied bad data, and I think it should be reported as such - i.e. a simple error message on stderr plus a non-zero exit code.

**Comment by InsanePrawn** [comment]
> However I think it's confusing: panics should be reserved for internal errors and software bugs.
> In this case, the user supplied bad data, and I think it should be reported as such - i.e. a simple error message on stderr plus a non-zero exit code.

Fully agree in this case. I think the `else` branch above the referenced `for` loop might be the place to check for existence and exit 1 gracefully, since we're checking a single dataset.

To make matters worse:
```
~ % zrepl help test placeholder

[...]

Flags:
      --dataset string   dataset path (not required to exist)
```


I'll see if I can open a small PR for this in the next days, unless someone beats me to it.

**Comment by problame** [comment]
I certainly won't beat you to it, but please fix it anyways ;)
Your proposed fix seems reasonable.
