### ISSUE TITLE
send/recv properties: handle zfs vs. zvol-only properties

### ISSUE THREAD

**Issue by problame** [zrepl/zrepl#430]
Overriding or inheriting properties specific to zvols errors on `zfs receive` currently.
https://github.com/openzfs/zfs/issues/11416

Zrepl currently has no special handling for the type of dataset to be transmitted.
So for the time being, one has to make separate jobs for zvols and filesystems or not override those specific properties.

Properties known to conflict:
- `mountpoint` on zvols (-x and -o fail with `cannot receive new filesystem stream: property 'mountpoint' does not apply to datasets of this type`)

**Comment by problame** [comment]
## "Fix" for 0.4

Add a doc comment that documents this problem.

## Long-term fix (needs someone to impl it)

### Variant 1:
- Screen-scrape `zfs recv` error for the property error that indicates `mountpoint` (might need larger peek buffer because user props take arbitrary amounts of space at the head of the stream)
- => if the error occurs, remove `mountpoint` from the override / inherit config
Pro: adheres to current trust model.
Con: ugly hack.

### Variant 2:
- replication learns about the sending side's dataset `type`
  - either through `SendRes` or through `ListFilesystems`
- relays that info to receiver
- receiver checks for `type == volume` and masks the `mountpoint` from inherit / override property set
Pro: "cleaner"
Con: Receiver has to trust sender (attack vector: sender could indicate `type == volume` but send a filesystem with `mountpoint=/` => hose the receiver's config.

(We could move the property overrides to the replication config so that this problem is a little more clear to the user. Or we could abandon the current trust model alltogether...)

**Comment by 0x3333** [comment]
This has been fixed in OpenZFS.

**Comment by problame** [comment]
Thanks, will update the comment in the docs.

**Comment by elliot-wood** [comment]
Hi! I'm still having trouble with this issue, as it appears the the fix in OpenZFS only applies to the inherit (`-x`) option, rather than the override option (`-o`), which still errors out when a non-applicable property is encountered.

In this case, I inherit the `mountpoint` property, which works fine for the zvols in my zrepl job thanks to the fix in OpenZFS.

However, I also override the `canmount` property to avoid clobbering / on the receiving system. For ZVOLs, this causes an error from the `zfs recv` process:
```
freebsd-root/var/vm-bhyve/home-assistant/disk0         STEP-ERROR (step 1/1, 8.5 MiB/8.9 GiB) server error: zfs exited with error: exit status 1
 stderr:
 cannot receive new filesystem stream: property 'canmount' does not apply to datasets of this type
```

**Comment by InsanePrawn** [comment]
I think the suggested usage for this is to have `mountpoint=none` set on the sink "root".
IIUC together with inheriting `mountpoint` down the tree this should solve your issue, @elliot-wood ?
