### ISSUE TITLE
[Feature request] Specify replication offsets

### ISSUE THREAD

**Issue by 3nprob** [zrepl/zrepl#433]
Scenario: Single centralized receiver (pull or sink) with large number of sources

Let's say we have a 10-30m snapshot interval, and overlapping receiver policies.

It would be desirable to have offsets for the intervals.

For example, consider a node with 30 pull jobs to separate hosts, with `interval: 30m` on each. It would be great to have functionality allowing their replication to be spread out over the interval, instead of all of them triggering simultaneously, in order to avoid contention and spikes.

I guess this has some simliraties to https://github.com/zrepl/zrepl/issues/92 but is effectively different

And BTW, thanks for a really great project <3

**Comment by InsanePrawn** [comment]
You might be interested in https://github.com/zrepl/zrepl/issues/397#issuecomment-766143183.
Would you want to hardcode offsets? Or a 'random' offset (within a specified interval) for each run, similar to e.g. [what systemd offers (see `AccuracySec`)](https://www.freedesktop.org/software/systemd/man/systemd.timer.html)?

**Comment by problame** [comment]
@3nprob thanks for the compliments!

If you find that neither #397 nor #92 satisfy your requirements please provide an example of how you would like the configuration to look like, e.g. by trimming down and anonymizing your existing config and extending it as you wish.

**Comment by 3nprob** [comment]
I think #397 looks like it covers it - missed that one, thanks :)
