### ISSUE TITLE
Multiple jobs on one filesystem

### ISSUE THREAD

**Issue by xofyarg** [zrepl/zrepl#439]
Hi, I found zrepl recently and wanted to give it a try. My use case is, to backup several devices to a central location(a NAS), and backup the NAS to an offline storage. I see in the docs, that it is not recommended to use multiple jobs on one filesystem. If I understand correctly, the NAS in my use case would have to have two jobs: a `sink` to receive backup from other devices, and a `push` to be able to make another copy of the data to offline storage. Since the second part is manual(run the job only after attaching to the offline disk), and I have full control of every device, I wonder is there a way to workaround it? Thanks.

**Comment by InsanePrawn** [comment]
This should work, make sure your second level job only replicates, `snapshotting: {type: manual}`

**Comment by InsanePrawn** [comment]
See also https://zrepl.github.io/configuration/overview.html#more-than-2-machines and especially https://zrepl.github.io/quickstart/backup_to_external_disk.html#quickstart-backup-to-external-disk

**Comment by xofyarg** [comment]
Thanks for the confirmation. The only issue for this kind of use case is the naming: S/H/J -> R1/sink1/job1/S -> R2/sink2/job2/R1/sink1/job1/S. Closing this and awaiting on #253

**Comment by problame** [comment]
@xofyarg please comment on the proposals made in that issue so that we get more user perspectives.
