### ISSUE TITLE
prometheus exporter: use better default port number & maybe consider registering it

### ISSUE THREAD

**Issue by lapo-luchini** [zrepl/zrepl#444]
Current documentation suggests using port `9091`, but that is the port that Prometheus server uses, I don't think that a good default to suggest for a single export client.

You could register a "default port" [in this page](https://github.com/prometheus/prometheus/wiki/Default-port-allocations), so that all `zrepl` installs can have a standard value to use.

**Comment by problame** [comment]
Thanks for the suggestion. I think a PR to the zrepl docs that suggests a better default port is a good first step.

**Comment by lapo-luchini** [comment]
OK, in the meanwhile I reserved [port 9811](https://github.com/prometheus/prometheus/wiki/Default-port-allocations/_compare/43e495dd251ee328ac0d08b58084665b5c0f7a7e...459195059b55b414193ebeb80c5ba463d2606951) on that page.
