### ISSUE TITLE
Infrequent offline storage replication use case - will incremental work

### ISSUE THREAD

**Issue by cebu23** [zrepl/zrepl#460]
I have a question regarding one of the sample use cases, https://zrepl.github.io/quickstart/backup_to_external_disk.html - this could definitely be a user brain fart / reading comprehension issue on my part, not an actual issue with zrepl.

My specific case is actually a bit inverted from the sample - I have an Xubuntu 20.04 system running zfs-on-linux 0.8.3 with multiple pools and zfs datasets.  For better protection against user errors, I've implemented the sample use case's fading snapshot scheme, just dropping the days of retention from 14 to 7:  e.g.  grid: 1x1h(keep=all) | 24x1h | 7x1d .

I have external removable USB drives that I use to take a periodic snapshot backup of the server - these are actually small compared to the server, so each drive receives only selected datasets, and I only keep one snapshot on them.  My process prior to zrepl was to manually snapshot the datasets (using the date as an identifier), run an incremental replication to each USB for the datasets it backs up, and then destroy (on server and USB) all snapshots prior to today.  

With zrepl I've setup push_usb_x jobs (where x identifies the target drive) using the sample use case as my guide, and matching sink jobs identifying the target root_fs of each drive.  With early testing, as expected, the first run of the job ran a full replication, and subsequent ones ran an incremental.  But it leaves me wondering two things:

1) In the push job, how can I setup the pruning of the receiver so that it keeps only the most current snapshot on the removable drive once replication has succeeded?  I don't need the USB drives to hold history (the server is doing that), I just need them at "most current" in case the server fails catastrophically, house  burns down, etc.  If it has to keep a few (for instance setting up a grid that preserves 1x1h(keep=all) | 1x1h | 1x1d to ensure the last day's worth of snapshots stay) that'd be OK, but I'm not sure that's the best/only solution?

2) If I don't do incremental replication for a while (e.g. away for a week, distracted, whatever) and it goes beyond the 7 days I've configured the server's snapjob to keep snapshots, will incremental replication still work?  It's not entirely clear to me from the zrepl and ZFS docs if zrepl would a bookmark or snapshot that would guarantee incremental replication could still work past that 7 day mark.  I'd prefer not to keep more snapshots on the source server; but I'd **really** prefer not to trigger another full replication.

Thanks!

**Comment by InsanePrawn** [comment]
Hi there,
1. Sounds like
    ```yaml
    keep_receiver: 
        - type: last_n
          count: 1
    ```
    https://zrepl.github.io/configuration/prune.html?policy-last-n#policy-last-n

2. I think you're looking for `guarantee_incremental`
    https://zrepl.github.io/configuration/replication.html?highlight=guarantee_incremental#protection-option

**Comment by cebu23** [comment]
Thanks InsanePrawn, that's exactly what I was looking for - somehow managed to overlook both when I was doing setup (perhaps 2am is not the best time to play with new things!)
