### ISSUE TITLE
very slow replication progress

### ISSUE THREAD

**Issue by Gibheer** [zrepl/zrepl#480]
Hi,

I am running zrepl 0.3.1 on FreeBSD 13 and over the last couple days I had some network issues. zrepl kept doing its thing and built up an impressive list of 65k snapshots (last month I had similar issues and went far beyond 300k snapshots).

Now my issue is, that zrepl takes 30min to investigate what it needs to do and then starts replication each snapshot after another, which takes around 1s per snapshot if I interpret `zrepl status` correctly.

The last time this happend, I threw all targets away, made one snapshot over all zfs partitions and made one big stream out of it. Would it be possible for zrepl to do the same?

I know there is the regex involved to select the snapshots to replicate. But from the starting point (the last successful snapshot) to the latest snapshot, you could build one incremental stream and replicate that and on the target throw any non matching snapshots away (maybe send the list of all snapshots to the target server and let it mark non matching snapshots to throw them away?).

This way the replication wouldn't be held up so much with small snapshots that might contain only a couple bytes of changes.

**Comment by problame** [comment]
I think this is a duplicate of #354 .
---
As a temporary solution, you can speed up replication as follows:
- Option 1: Destroy the snapshots on the sender. The replication cursor bookmark will ensure that replication still works.
- Option 2: Configure parallel replication https://zrepl.github.io/configuration/replication.html#concurrency-option
- Option 3: (can combine with 2) Relax the replication guarantees so that no holds are created https://zrepl.github.io/configuration/replication.html#protection-option

Option 2 is only available with zrepl 0.4. You can download the static binary from github and replace it on your file system until the FreeBSD package is updated.

**Comment by Gibheer** [comment]
Okay, I understand the reason behind the decision.
In my case, I only have two filesystem trees with a lot of partitions underneath:

```    filesystems: {
      "rpool/data<": true,
      "rpool/jails<": true,
    }
```
In such a case, wouldn't it be possible to hold on the target and make one incremental stream to push to the target? The docs don't mention a filesystem filter with a wildcard. That means it could be possible to interpret a filesystem tree the same as a single filesystem, wouldn't it?

**Comment by problame** [comment]
> In such a case, wouldn't it be possible to hold on the target a

What do you mean by that?
And is your response referring to my proposed workarounds or the discussion in #354 ?

**Comment by Gibheer** [comment]
You said, this would be a duplicate of #354, so I read the description of that issue.

The reason each snapshot is transported, as stated in #354, is that you can use `zfs hold` on the source and target snapshot to avoid removal.
Now what would happen if the root of a filesystem tree, as in my case, would be snapshot recursively? The first benefit would be, that you could use a single snapshot name to recursively mean all of them. You could send, delete all at once.
The same applies for hold and release.

In that case you could send all snapshots at once by holding the first and last snapshot recursively, send everything and then release everything again.

Does that make sense?

**Comment by Gibheer** [comment]
I need to read the actual code to maybe come up with a proposal on how that could work though.

**Comment by problame** [comment]
Yeah, all of this could be done, but doesn't fit to zrepl's model (which is per-filesystem).
In essence, zrepl re-implements most of `-I` and `-R` in a more flexible way.

**Comment by problame** [comment]
Did the workarounds help to get your setup back up to speed?

**Comment by Gibheer** [comment]
I didn't get around to try 0.4 yet, sorry. But I will try this week and reproduce the problem. Thank you for your time and the explanation :)

**Comment by Gibheer** [comment]
Sorry, I don't have time to investigate further :( I will close this for now and report back, when I had more time.

Thank you very much for the workarounds :)
