### ISSUE TITLE
Offsite Backup to Multiple External HDDs Possible?

### ISSUE THREAD

**Issue by rbugajewski** [zrepl/zrepl#487]
Assume you have a  ZFS storage pool that you need to back up to external HDDs. To reduce complexity let’s assume that there are two external HDDs for backups, only one is connected at the same time. The HDDs are rotating (no pun intended here!). The process has to be fully automatic, USB connect / disconnect should be the only manual intervention.

After reading [the guide in the official documentation](https://zrepl.github.io/quickstart/backup_to_external_disk.html#quickstart-backup-to-external-disk) I tried to use the example and modify it to our requirements. I also read the warnings about multiple jobs on one filesystem. My naïve approach was the following:

1. Keep the naming scheme the same, always import / export both HDDs at `/mnt/backup` via a hook.
2. Rotate HDDs approximately every two weeks.
3. Keep local snapshots for one month.

The idea was that `zrepl` would do just _the right thing_, but I think I tried to be a little too smart. By keeping local snapshots for one month, but rotating every two weeks I wanted to make sure that there is always a local anchor from which the other HDD can make incremental backups. It turns out that `zrepl` is smart, detects that it deals with another HDD, and refuses operation.

The only solution I can currently think of is to treat the HDDs as they are: as two separate entities with two different jobs. But I also have the requirement to be fully automatic. If I create different jobs, in the case of two HDDs, one job will always fail, because it won’t find the HDD.

What do you suggest in this case? Is my use case possible with `zrepl`?

**Comment by InsanePrawn** [comment]
Going for two jobs is the right approach currently.
You'll either have to live with one job failing or build some sort of machinery to trigger them manually, I'd recommend the first approach.

**Comment by rbugajewski** [comment]
Thanks.
