### ISSUE TITLE
notify mechanism when something goes wrong

### ISSUE THREAD

**Issue by almoondsllc** [zrepl/zrepl#493]
First of all, I really love zrepl!
I'm actually using zrep to backup my customer's data but I found zrepl more elegant solution.
Except the notification for snapshot, I think a notification for replication is missing, if I'm not wrong.
For example today a zrepl jobs failed (some zfs transfer interrupt and I fixed with a zfs receive -A <dataset> at receiver side).
How we can implement some notification with a general jobs fails? Thank you.

Regards,
Alessandro Marzini

**Comment by problame** [comment]
> First of all, I really love zrepl!

:pray: 

> For example today a zrepl jobs failed (some zfs transfer interrupt and I fixed with a zfs receive -A at receiver side).
How we can implement some notification with a general jobs fails? Thank you.

First of all, there's a Prometheus metric for failed replication jobs, it is visualized in the Grafana dashboard.

Second, @InsanePrawn and I have been thinking about a mechanism to wait for ongoing replication attempts from the command line ( https://github.com/zrepl/zrepl/tree/trigger-wait-reset-rearchitecture ). IIRC we didn't think about a way to report failure, though, that would have to be done using `zrepl status`, e.g., `zrepl status --raw | jq ...`.

Could you please provide a UX draft of the feature you are requesting? I.e., CLI or commented sample config.

**Comment by almoondsllc** [comment]
I found the hook system for snapshot jobs a good solution, is possible to implement also in push jobs?
https://zrepl.github.io/configuration/snapshotting.html#pre-and-post-snapshot-hooks?
I use zrepl to snapshot the customer server periodically and then like every night send a replication to a central server.
Thank you

**Comment by problame** [comment]
Do I understand correctly that you are triggering a push job from a post-snapshot hook? (via `zrepl signal`)
Neat idea, hadn't thought of that.

But I don't understand what part of the push job you'd want to hook into, and how it relates to this issue. Please elaborate on that.

**Comment by almoondsllc** [comment]
I'm not actually triggering anything, I'll try to explain better my goal in this scenario:
a) I've several zfs machine at customer location, let's call them "clients"
b) i've my zfs machine acting as server of backup
c) my server at point b) is also a openvpn server for clients of point a)

Now, I want to have this logic: 

- zfs machine of point a) do a regular snapshot, just a local snapshot on the local storage
- every night I want receive a replication from the zfs machines of point a) to my server of point b)

This to mainly to not interfer with the internet bandwith of the customer.
I understand that in the push job, the replication is triggering just after the snapshoting phase, so if I make an automatic 10m snapshot, I've a 10m automatic replication that is good in a world with fast connections :)

Plus, I want to have the ability to have a script (hook) also for replication phase, not only snapshotting.
And of course I want an elegant, clean , configuration file for zrepl.yaml.

Actually I think the best is having a "snap" job only for the regular snapshot, and a manual push job to trigger manually during the night.
I asked if is possible to have a hook also for the pre/post replication phase so I can check if the replication was sucessful

Thank you

**Comment by problame** [comment]
> Actually I think the best is having a "snap" job only for the regular snapshot, and a manual push job to trigger manually during the night.

Yes, that's the best configuration at this time. Your use case is pretty common and will be addressed in a future release.

**Comment by problame** [comment]
>  I asked if is possible to have a hook also for the pre/post replication phase so I can check if the replication was successful

And do what, then? 
My suggestion is that you implement some kind of monitoring tool that checks that replication actually works.

- Option 1: use zrepl's Prometheus + Grafana dashboard
- Roll your own. That can be simple, like, a cronjob on server `b)` that checks that the `creation` property of the most recent snapshot of each dataset is recent enough, e.g., less than 24h old.

Does that sound like a reasonable solution to you?

**Comment by almoondsllc** [comment]
I find the "roll your own" solution a perfect solution for a linux sysadmin :) so yeah I'll go with this solution to check on the receiving side if the last snapshot received is recent enough.
