### ISSUE TITLE
TrueNAS 12.2 w/ OpenZFS 2.0.0.-1: platformtest failure

### ISSUE THREAD

**Issue by problame** [zrepl/zrepl#500]
> I downloaded and ran the binary only to be drowned in logs flying by with no idea of what it was doing. Eventually, it hung on the line:
> ```2021-04-26T13:53:12-05:00 [DEBG][zfs.cmd][Uv38$g+Vq$g+Vq.FWqN]: start waiting cmd="zfs send zreplplatformtest/rootds/send er@a snapshot"```

_Originally posted by @sa7mon in https://github.com/zrepl/zrepl/issues/478#issue-868034191

**Comment by lapo-luchini** [comment]
I have this working on a recent TrueNAS in a iocage jail, thanks to this thread:
https://www.truenas.com/community/threads/zfs-recv-in-jail-cannot-receive-new-filesystem-stream-invalid-backup-stream.95655/

The basic problem is that iocage download a "normal" FreeBSD jail, which uses ZFS1, while the exterior FreeBSD used by TrueNAS has been hacket to use ZFS2.

This solved my problem:

```bash
cp /usr/local/sbin/zfs /mnt/tank/iocage/jails/zrepl/root/sbin/
cp /usr/local/lib/libzfs.so.4 /mnt/tank/iocage/jails/zrepl/root/usr/lib/
cp /usr/local/lib/libzfs_core.so.3 /mnt/tank/iocage/jails/zrepl/root/usr/lib/
cp /usr/local/lib/libnvpair.so.3 /mnt/tank/iocage/jails/zrepl/root/usr/lib/
cp /usr/local/lib/libuutil.so.3 /mnt/tank/iocage/jails/zrepl/root/usr/lib/
cp /usr/local/lib/libintl.so.8 /mnt/tank/iocage/jails/zrepl/root/usr/lib/
```

(As suggested [here](https://github.com/psy0rz/zfs_autobackup/issues/99#issuecomment-932536374).)

**Comment by lapo-luchini** [comment]
While TrueNAS upgrades to FreeBSD 13 (which will have ZFS2 by default in the jail too), we could add this to the [iocage page](https://github.com/zrepl/zrepl/blob/master/docs/installation/freebsd-jail-with-iocage.rst), maybe?

**Comment by problame** [comment]
@lapo-luchini good thought. Will you do it?
