### ISSUE TITLE
Debian Bullseye `apt` repository

### ISSUE THREAD

**Issue by lpulley** [zrepl/zrepl#513]
Seems like there is not currently a Debian Bullseye repository for `zrepl`.

https://zrepl.github.io/installation/apt-repos.html

https://zrepl.cschwarz.com/apt/debian/dists/

**Comment by problame** [comment]
Thanks for reporting this. I won't be able to update the repo until the weekend. In the meantime, please use the `buster` repos. The `.deb`'s are the same anyway.

**Comment by lpulley** [comment]
No problem at all, just thought to mention it. Thanks!

**Comment by problame** [comment]
Thanks, I appreciate it!

**Comment by problame** [comment]
Done.
