### ISSUE TITLE
Docs question: How to migrate Local FS while preserving backup state?

### ISSUE THREAD

**Issue by mattventura** [zrepl/zrepl#515]
I would like to migrate my local pool, which has a snapshot+push job, to a new local pool. I want to switch RAID levels, so just replacing individual drives in the pool isn't an option. I would like to have Zrepl start copying incrementally from the new pool as if nothing happened, rather than sending the entire pool's worth of data again. The docs don't seem to outline how to do this.

If I were to do something like this to migrate the pool:
```
# zpool create newpool disk1 disk2 ...
# zfs snapshot -r oldpool@foo
# zfs send -R oldpool@foo | zfs recv -u newpool
# zfs export oldpool
# (edit zrepl job to point to new names if needed)
```

`man zfs-send` doesn't mention that it will preserve bookmarks specifically, so would the `#zrepl_CURSOR_...` bookmark need to be manually recreated or sent separately?

For getting the pool name to match up, what is the best option? Rename the datasets on the receiver? Use `zpool import newname oldname` to rename it on the sender?

Is there anything else that would need to be done to migrate while preserving backup state? I would like to make sure this is possible before migrating to the new pool.

**Comment by problame** [comment]
> man zfs-send doesn't mention that it will preserve bookmarks specifically, so would the #zrepl_CURSOR_... bookmark need to be manually recreated or sent separately?

They are not sent. But if the most recent snapshot on the receiver is still present on the sender, replication should be able to resume without the bookmark.

> For getting the pool name to match up, what is the best option? Rename the datasets on the receiver? Use zpool import newname oldname to rename it on the sender?

Either rename the sender or receiver, it shouldn't matter.
I personally would rename the senders.

> Is there anything else that would need to be done to migrate while preserving backup state? I would like to make sure this is possible before migrating to the new pool.

I haven't done that operation before, please report on your experience, either in this issue, or ideally as a PR for the documentation (it doesn't have to be perfect).

Also: consider using zpool checkpoint on the receiver, if and only if, the receiver-pool is exclusively used as a sink for this one job. (Read up about it first though)

**Comment by mattventura** [comment]
Okay, I finally got around to testing this. Looks like `zfs send -R` and then renaming the sender works. `zrepl status` will show an error for pruning because the replication bookmark doesn't exist, but the issue goes away the next time it sees a new snapshot.

**Comment by problame** [comment]
Great to hear it worked. Would you like to write up some doc / guide for this? Not sure where we'd place it in the documentation, but if you write something up, we'll find a place for it.
Otherwise, please close this issue.

**Comment by mattventura** [comment]
Okay, here's my attempt at documenting it:

## Migrating Backup State

If you would like to migrate data from one zpool to another (for example, to change RAID levels or block size), while having zrepl pick up on the new pool right where it left off, you will need the name of the new pool to match that of the old pool. You can use the following steps as a reference, assuming that 'oldpool' is the existing pool and 'newpool' is the new pool:

1. Stop zrepl
2. Create the new pool: `zpool create newpool ...`
3. Take a snapshot of the old pool so that you have something that you can `zfs send`, i.e. `zfs snapshot -r oldpool@snap`
4. Send the data to the new pool: `zfs send -R oldpool@snap | zfs recv -F newpool`
5. Export the old pool: `zpool export oldpool`
6. Export the new pool: `zpool export newpool`
7. Import the new pool, while changing the name to match the old pool: `zpool import newpool oldpool`
8. (Optional) Change the name of the old pool to something different so that it does not conflict with the new pool: Use `zfs import` with no arguments to see the pool id, then `zpool import <id> oldoldpool && zpool export oldoldpool`. Or, dispose of the old pool by other means (such as `zpool destroy` or by removing the disks). 
9. Create a new snapshot: `zfs snapshot -r oldpool@snap2`
10. Start zrepl again and wake up jobs
11. Check `zrepl status` for errors. To verify that the backup is working, you could also write some junk data and ensure that `zrepl status` shows the correct amount of data being transferred.

**Comment by problame** [comment]
Thanks, created #525 for this.
