### ISSUE TITLE
Improve error detection in Prometheus metrics

### ISSUE THREAD

**Issue by lapo-luchini** [zrepl/zrepl#516]
Hi, I have a zrepl node which is exporting this:

`zrepl_replication_filesystem_errors{zrepl_job="backup"} 0`

but is actually been failing synchronizations for one month, the underlying problem might be related to #495 but I was thinking, in the meantime, it could be useful (and easy) to add a metric such as:

`zrepl_replication_filesystem_last_complete{zrepl_job="backup"} 1631543787665`

So that I can use a more resilient alerting such as "last complete was sent more than 24h ago".

**Comment by problame** [comment]
Yes, that sounds reasonable. Could you describe in what way the replications failed?

Also, cc #481

**Comment by lapo-luchini** [comment]
If a system to detect a stalled connection (i.e. `0.0 KiB` for 5 minutes, for example) was in place, the new metric I propose wouldn't be needed anymore and it would actually solve the problem |(and retry automatically later), not only give a metric to warn me to go and reset zrepl manually. 🤔
…but that's a whole different RFE (and, I guess, a lot more complex to implement).

**Comment by lapo-luchini** [comment]
Nice, thanks!
I'd like to continue that patch to add "per-filesystem" granularity, and potentially using the date of the last sent snapshot date (for that filesystem) instead of the date it was sent. I'll probably need some suggestions/help with that, though, as it gets more invasive of the existing code.
