### ISSUE TITLE
snapshots not storing ownership privilages

### ISSUE THREAD

**Issue by ctr0603** [zrepl/zrepl#523]
Hi Team,

Whenever we try to restore the snapshots other than root privileges are not getting stored
for example if i have a directory with owner and group permissions as prometheus after restoring the snapshot i am not the same owner and group permissions for the directory

**Comment by ctr0603** [comment]
I am sorry for not explaining properly
For example i have a Prometheus server  and i planned to take snapshots for /prometheus directory which has permissions as below
drwxr-xr-x    2  prometheus prometheus         2 Jul 25 05:50  /prometheus

Configured zrepl as per the documentation and started creating backup (snapshots) on a different machine

Now my primary server crashed and i tried to restore the backup (snapshot) every thing came fine but one thing i noticed is when i restore the backup (snapshot) i do not see the permissions as   
drwxr-xr-x    2  prometheus prometheus         2 Jul 25 05:50  /prometheus  

Also i noticed it not having root privilages it will have some random number as owner and group for the directory /prometheus
And i have to manually change permissions for /prometheus

Hoping i clearly explained

**Comment by ctr0603** [comment]
I am following https://zrepl.github.io/configuration/prune.html

**Comment by ctr0603** [comment]
is there any parameter that i can pass with zrepl to preserver uid & gid while doing snapshots

**Comment by problame** [comment]
> t) i do not see the permissions as
drwxr-xr-x 2 prometheus prometheus 2 Jul 25 05:50 /prometheus

And what were you expecting to see?

Sounds to me like you might need to re-create the prometheus user on the restored system?

**Comment by problame** [comment]
It seems to me like there is a lack/misunderstanding of how ZFS snapshots work.
For the record: ZFS snapshot replication always preserves the numeric user IDs as they were on the sender.
