### ISSUE TITLE
Pruning documenation has contradiction

### ISSUE THREAD

**Issue by callumgare** [zrepl/zrepl#524]
I'm trying to understand how the pruning config works and I notice that on https://github.com/zrepl/zrepl/blob/stable/docs/configuration/prune.rst#policy-not_replicated it states that it only makes sense to use the "not_replicated" type on source or push jobs. But as far as I can tell source jobs don't allow pruning to be specified. Pruning isn't listed on https://github.com/zrepl/zrepl/blob/stable/docs/configuration/jobs.rst#job-type-source and if I add a pruning section to a source job then configcheck complains:
```
callumgare@computer ~> sudo zrepl configcheck
could not parse config: yaml: unmarshal errors:
  line 31: field pruning not found in type config.SourceJob
```

Also you can currently add the "not_replicated" type to the keep_sender section of the pruning config for a pull job. It won't complain but it will silently stop any snapshots from being pruned from the sender. While you can workout that this is not supported behavior if you read the documentation carefully it's not an obvious error if you miss that in the documentation and it can make it tricky to debug why snapshots aren't being cleared when you expect them to be. So I'm suggesting configcheck should complain if it encounter this usage until/unless support for this is ever added.

**Comment by InsanePrawn** [comment]
> It states that it only makes sense to use the "not_replicated" type on source or push jobs. But as far as I can tell source jobs don't allow pruning to be specified. 

That is indeed a mistake in the docs.

> Also you can currently add the "not_replicated" type to the keep_sender section of the pruning config for a pull job.

I think this is what was meant in said docs.

> It won't complain but it will silently stop any snapshots from being pruned from the sender. While you can workout that this is not supported behavior if you read the documentation carefully [...] until/unless support for this is ever added.

Huh, this doesn't sound right, AFAICT this should already work. Can you reference the docs as to why that's unsupported?

**Comment by callumgare** [comment]
> Huh, this doesn't sound right, AFAICT this should already work. Can you reference the docs as to why that's unsupported?

Mmm, maybe I miss interpreting it but in the same section it says:
“It only makes sense to specify this rule on a sender (source or push job). The state required to evaluate this rule is stored in the replication cursor bookmark on the sending side.” (https://zrepl.github.io/configuration/prune.html#policy-not-replicated). A pull job isn’t a sender, right? It’s a receiver I’m assuming so the above seems to suggest that it wouldn’t “makes sense” to include it.

**Comment by problame** [comment]
I just pushed a commit (see above) that improves the docs to remove the confusion around where `keep: not_replicated` can be used.

> It won't complain but it will silently stop any snapshots from being pruned from the sender. While you can workout that this is not supported behavior if you read the documentation carefully [...] until/unless support for this is ever added.

I wont' have time to reproduce this tonight.
However, a few questions:
- Is there a replication cursor on the sender where this silent-no-pruning behavior occurs? Check with ` zrepl zfs-abstraction list --job JOBNAME` for the affected jobs on the sender (source?)
- Could you post your configs or at least general job combination? Just one source and one pull job? Or is some kind of local snapshotting involved?

**Comment by problame** [comment]
@callumgare any updates on this?

**Comment by callumgare** [comment]
> any updates on this?
@problame Sorry I never responded to this! Life got busy and I ended up changing my setup to use a push model rather than a pull as that seemed to be more of a "happy path" for my scenario. So unfortunately I can't really post my config or test anything. But the changes you've made look very helpful tho, thanks ❤️
