### ISSUE TITLE
docs: document how to migrate backup source

### ISSUE THREAD

**Issue by problame** [zrepl/zrepl#525]
Okay, here's my attempt at documenting it:

## Migrating Backup State

If you would like to migrate data from one zpool to another (for example, to change RAID levels or block size), while having zrepl pick up on the new pool right where it left off, you will need the name of the new pool to match that of the old pool. You can use the following steps as a reference, assuming that 'oldpool' is the existing pool and 'newpool' is the new pool:

1. Stop zrepl
2. Create the new pool: `zpool create newpool ...`
3. Take a snapshot of the old pool so that you have something that you can `zfs send`, i.e. `zfs snapshot -r oldpool@snap`
4. Send the data to the new pool: `zfs send -R oldpool@snap | zfs recv -F newpool`
5. Export the old pool: `zpool export oldpool`
6. Export the new pool: `zpool export newpool`
7. (Optional) Change the name of the old pool to something different so that it does not conflict with the new pool: Use `zpool import` with no arguments to see the pool id, then `zpool import <id> oldoldpool && zpool export oldoldpool`. Or, dispose of the old pool by other means (such as `zpool destroy` or by removing the disks). 
8. Import the new pool, while changing the name to match the old pool: `zpool import newpool oldpool`
9. Create a new snapshot: `zfs snapshot -r oldpool@snap2`
10. Start zrepl again and wake up jobs
11. Check `zrepl status` for errors. To verify that the backup is working, you could also write some junk data and ensure that `zrepl status` shows the correct amount of data being transferred.

_Originally posted by @mattventura in https://github.com/zrepl/zrepl/issues/515#issuecomment-937325193_

**Comment by altano** [comment]
@problame these docs assume that the new zpool is on the same client with the same client id (ip?), correct?

If the new zpool is on a separate machine with a different ip zrepl will write to a different dataset and replication will start over from scratch. Correct?

If so, is it simply a matter of renaming the dataset on the sink side to match the new client identity before resuming the sync, to get zrepl to use the existing replica?

**Comment by problame** [comment]
> client id (ip?), correct?

In general, client identity is dependent on transport. In `tcp`, you have an explicit mapping from IP to client identity, that you can update so that client identity remains the same. In `tls`, client identity is encoded in the client cert, without a mapping option (right now).

> If the new zpool is on a separate machine with a different ip zrepl will write to a different dataset and replication will start over from scratch. Correct?

I assume this is a push+sink setup. In that case, that'll only happen if you change the client identity. If you make it stay the same (use same tls cert, or use the same mapped client identity for the new IP), it should just work.

> If so, is it simply a matter of renaming the dataset on the sink side to match the new client identity before resuming the sync, to get zrepl to use the existing replica?

Yes, `zpool rename $root_fs/$old_client_identity $root_fs/$new_client_idenitity` should work as well.

**Comment by problame** [comment]
If this works for you, please open an update PR for the docs. If you don't know RST, just create an issue with markdown, I'll translate it.

**Comment by altano** [comment]
Ah, I didn't quite fully process that the `clients` part of the `serve` config is setting up the mapping. The documentation is a lot to take in :p (although it very clearly lays this out).

Let's say my old source machine's IP is `192.168.0.111` and the new one is `192.168.0.222`. For anyone following along, my understanding is that my options are (that while zrepl is stopped on both sides of the replication):

# Option A
On the sink side: `zpool rename $root_fs/$old_client_identity $root_fs/$new_client_idenitity`, or specifically in this case given: 
```
root_fs = zbackup
old_ip = 192.168.0.111
new_ip = 192.168.0.222
clients = { "192.168.0.0/24" = "main-*" }
```
then I do:
`zpool rename zbackup/main-192.168.0.111 zbackup/main-192.168.0.222`

# Option B
On the sink side,  change the existing zrepl config from†:

```
  services.zrepl.settings =
    {
      jobs = [
        {
          ...
          serve = {
            root_fs = "zbackup";
            clients = {
              "192.168.0.0/24" = "main-*";
            };
          };
        }
      ];
    };
```

```
  services.zrepl.settings =
    {
      jobs = [
        {
          ...
          serve = {
            root_fs = "zbackup";
            clients = {
              "192.168.0.111" = "main-192.168.0.222",
              "192.168.0.0/24" = "main-*";
            };
          };
        }
      ];
    };
```

I won't have the chance to test this out until my initial replication completes in ~1 week. I will report back when I attempt this.

Thanks for the *amazing* software. It's such a breathe of fresh air using zrepl after hitting bug after bug in zettarepl (the replication engine built into TrueNAS).

† (pardon my non-yml syntax, as I'm using NixOS my config is in the Nix Expression Language and not yml).

**Comment by problame** [comment]
Thanks for the compliments :)

Both options should work. I'd recommend going the rename route (Option A) as it leads to less confusion in the long run.
