### ISSUE TITLE
After update from 0.1.1 ro 0.4.0 can't migrate bookmarks

### ISSUE THREAD

**Issue by budachst** [zrepl/zrepl#532]
After updating our zrepl server/client from 0.1.1 to 0.4.0, no replication takes place, because v1 bookmarks are found.

`Oct 25 21:28:21 jupiter zrepl[18536]: job=jupiterData-to-jupiterBackup subsystem=endpoint span=Uv38$Qj/6$Qj/6.EV7T.LeLo.syha.ZxLk msg="found v1-replication cursor bookmarks, consider running migration 'replication-cursor:v1-v2' after successful replication with this zrepl version" bookmark=<[]endpoint.Abstraction>
Oct 25 21:28:21 jupiter zrepl: 2021-10-25T21:28:21+02:00 [WARN][jupiterData-to-jupiterBackup][endpoint][Uv38$Qj/6$Qj/6.EV7T.LeLo.syha.ZxLk]: found v1-replication cursor bookmarks, consider running migration 'replication-cursor:v1-v2' after successful replication with this zrepl version bookmark="[replication-cursor-bookmark-v1 jupiterData/dateng#zrepl_replication_cursor]"
Oct 25 21:28:21 jupiter zrepl: 2021-10-25T21:28:21+02:00 [ERRO][jupiterData-to-jupiterBackup][pruning][Uv38$Qj/6$Qj/6.EV7T.LeLo.syha]: : plan error, skipping filesystem prune_side="sender" fs="jupiterData/dateng" orig_err_type="*errors.fundamental" err="replication cursor bookmark does not exist (one successful replication is required before pruning works)"`

However, when I try to migrate the bookmarks from v1 to v2, I am getting this error for all ZFS:

`MIGRATION FAILED: no v2 replication cursor found for job "jupiterData-to-jupiterBackup" on filesystem "jupiterData/dateng"
INSPECT FILESYSTEM "jupiterData/easyjob"
identified owning job "jupiterData-to-jupiterBackup"
found v1 replication cursor:
&zfs.FilesystemVersion{
    Type:      "bookmark",
    Name:      "zrepl_replication_cursor",
    Guid:      0xbd33366c8749b577,
    CreateTXG: 0x111ce2c,
    Creation:  time.Time{
        wall: 0x0,
        ext:  63721125795,
        loc:  &time.Location{},
    },
    UserRefs: zfs.OptionUint64{},
}`

How can I tackle that?

**Comment by problame** [comment]
Hi @budachst , sorry for the delayed reply.

I'm surprised about "no replication takes place". Replication should take place, just not pruning.

**Comment by budachst** [comment]
Hi @problame, no worries. Yeah, well… it looks like the system got somewhat out of sync a rather long time ago. And now I am facing approx. 5 mio. snapshots in 358 ZFS, some of them having up to 14k snapshots. I checked the target and there were overlapping snaphots, but it looked like the planner in zrepl had a hard time to figure out which snaps could be used, so it tried to send  with the -n option almost any of the source snaps.

On a ZFS where it actually could sync up the source to the target it sent every single snapshot by itself and that was not at all practical in that situation. I thing the issue with me not understanding the advice to update the replication bookmarks was, that I didn't get that I'd need a successful replication of the source before being able to do so.

What I am currently doing is to have the source being simply snapshot/pruned bevor initiating a completely new sync to the target, as I will never be able to catch up with the source otherwise.

**Comment by problame** [comment]
Sounds like that's the best workaround for your situation.

Do you have a concrete proposal for a better error message?
If yes, then please post it here, or even better, open a PR to fix it.

If not, please close this issue.

**Comment by budachst** [comment]
Hi @problame, thanks  for confirming my strategy. As I am no programmer, I will close this issue.
