### ISSUE TITLE
 Error: exec: "zfs": executable file not found in $PATH

### ISSUE THREAD

**Issue by gremi-jr** [zrepl/zrepl#533]
Hi,

after I upgraded my FreeNAS 11 to 12 I got these error message in the status of both jobs.
<img width="1185" alt="grafik" src="https://user-images.githubusercontent.com/50887574/139672622-c86f91be-4bb5-484d-8b93-467bd2e04a86.png">

I already checked if the zfs command is in my $PATH. 
<img width="1185" alt="grafik" src="https://user-images.githubusercontent.com/50887574/139672926-f1fd1e31-a3f5-4937-b889-c91fba882078.png">

<img width="594" alt="grafik" src="https://user-images.githubusercontent.com/50887574/139673039-01da1773-8aa7-43f0-b997-0428138aed3d.png">

Do you know these issue or is there something I miss? could you help me?

Thanks in advance!

**Comment by problame** [comment]
If it's the binary in /use/local, then it's the OpenZFS 2.0 port, I think.
Are you sure that the zrepl daemon has the same PATH as your interactive shell? It seems like you are using zsh or similar, and the zrepl daemon won't use the paths specified in zshrc...

**Comment by problame** [comment]
> Sorry but is there a way on how to check which $PATH the daemon is using? Or any way on how to set it?

The daemon doesn't support this right now (I created #534 , see above).

You could modify the /usr/local/etc/rc.d/zrepl script to run printenv instead of `zrepl daemon`...

**Comment by gremi-jr** [comment]
So I added `printenv` to the top and got this output
```
freenas# service zrepl onestatus
PATH=/sbin:/bin:/usr/sbin:/usr/bin
PWD=/
HOME=/
zrepl is not running.
```
For testing I copied the zfs binary from `/usr/local/sbin` to `/usr/sbin` and it worked again. But I guess somehow add the PATH would be a better approach

**Comment by problame** [comment]
I think this is a case for the port maintainer. @lcook  ?

**Comment by problame** [comment]
Closing this. @gremi-jr please open a bug in FreeBSD Ports.
