### ISSUE TITLE
Include freebsd-armv7 in binary release targets

### ISSUE THREAD

**Issue by problame** [zrepl/zrepl#539]
>  FWIW, I am able to build zrepl without any issues for GOOS=freebsd GOARCH=arm GOARM=7 and GOOS=freebsd   GOARCH=arm64. And they even work for me :-)
So, you can add them to release targets if you'd like.
Those builds are actually cross-builds on a FreeBSD 13.0 amd64 host. Not sure if that matters.

_Originally posted by @avg-I in https://github.com/zrepl/zrepl/issues/495#issuecomment-976696810_

**Comment by avg-I** [comment]
And arm64 too.
It seems that it's not there in the makefile yet.
