### ISSUE TITLE
FreeBSD Port init script broken for FreeBSD 10.3

### ISSUE THREAD

**Issue by dl8bh** [zrepl/zrepl#54]
root@basilika:~ # service zrepl start
Starting zrepl.
daemon: illegal option -- S
usage: daemon [-cfr] [-p child_pidfile] [-P supervisor_pidfile] [-u user]
              command arguments ...
/usr/local/etc/rc.d/zrepl: WARNING: failed to start zrepl

root@basilika:~ # uname -a
FreeBSD basilika.example.com 10.3-RELEASE-p20 FreeBSD 10.3-RELEASE-p20 #0: Wed Jul 12 03:13:07 UTC 2017     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64

man daemon shows, that some of the commandline arguments used by the bundled init-script are added to daemon in later versions of freebsd.

**Comment by problame** [comment]
The distros provide the service manager scripts, thus the bug should be filed there:

https://bugs.freebsd.org/

Sorry for the late reply!

**Comment by dl8bh** [comment]
Thats what I realized afterwards and so I filed:

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=224844

Mal vom Namen und vom Projekt am KIT her geschlossen wünsch ich mal ein frohes neues Jahr auf Deutsch ;)

**Comment by problame** [comment]
Danke gleichfalls!
