### ISSUE TITLE
Can't connect to apt server

### ISSUE THREAD

**Issue by riesebie** [zrepl/zrepl#544]
It seems that the connection to zrepl.cschwarz.com:443 is refused:

````W: Failed to fetch https://zrepl.cschwarz.com/apt/debian/dists/buster/InRelease  Could not connect to zrepl.cschwarz.com:443 (176.9.31.194). - connect (111: Connection refused) Cannot initiate the connection to zrepl.cschwarz.com:443 (2a01:4f8:150:33d3:1::6). - connect (101: Network is unreachable)````

This is done by apticron on a daily use since weeks but failed first time today.

**Comment by InsanePrawn** [comment]
I'm able to browse https://zrepl.cschwarz.com/apt/debian/dists/buster/ using my desktop browser just fine right now, can you verify? Maybe it was just restarting for an upgrade or similar.

**Comment by riesebie** [comment]
Yep, it works again. Thanks
