### ISSUE TITLE
Release 0.4.1

### ISSUE THREAD

**Issue by 3nprob** [zrepl/zrepl#545]
Even if it contains nothing new apart from the fix for #463 in 4f9b63aa09d5010992f6c3e71a84be64cdcff176.

Perhaps the protocol change warrants a 0.5.0?

In either case I think there are many users unable to replicate their backlog of snapshots that would be very grateful to have this in their repos, or at least as a tagged release with forwards-compatability.

While the fix is in master, there's a risk of future complications when deploying arbitrary commits from yet-released tip.

**Comment by problame** [comment]
Just published https://github.com/zrepl/zrepl/releases/tag/v0.5.0-rc1 ; Sorry this took so long :)
