### ISSUE TITLE
[Question] Fan-out replication with 1 snapshot job and N source jobs?

### ISSUE THREAD

**Issue by chenxiaolong** [zrepl/zrepl#551]
I'm looking to implement fan-out replication as described on: https://zrepl.github.io/configuration/overview.html#overview-how-replication-works. Specifically, I have 3 hosts, (`A`, `B1`, `B2`), and I want to replicate from A to both B1 and B2.

Assuming, I have a setup like this:
* 1 snapshot job on `A` that does the snapshotting and pruning
* 1 source job on `A` + 1 pull job on `B1` that does not prune the sender
* 1 source job on `A` + 1 pull job on `B2` that does not prune the sender
* Datasets being sent to `B1` and `B2` are the same (not disjoint)

Would there any complications with this setup?

My understanding from the documentation is that datasets being replicated don't have to be disjoint as long as only one job does the pruning. I also understand that N pull jobs with 1 source job is not supported because the client identity name is not part of the zfs abstraction naming scheme. It _seems_ like N pull jobs, each with a corresponding unique source job, would work fine given that that the source job name is encoded in `zrepl zfs-abstraction list`. Is my understanding correct?

Thank you!

**Comment by problame** [comment]
(Disclaimer: I haven't tested this anywhere)
(Disclaimer 2: there are going to be some error-level log messages if the snapjob's pruner and the replication jobs race, but they should be safe to ignore)

> My understanding from the documentation is that datasets being replicated don't have to be disjoint as long as only one job does the pruning.

Yes.

> I also understand that N pull jobs with 1 source job is not supported because the client identity name is not part of the zfs abstraction naming scheme.

Correct. To expand this a little for future readers:
Pull jobs receive the source-side filesystems directly into `$root_fs`, so there's no client identity involved on the pulling = receiving side.
But: the replication cursor bookmark does not include the client identity of the pull job. So, multiple pull jobs would share the same replication cursor bookmark. Which will break incremental replication at some point.
That's a flaw in the design, and could be fixed.

> It seems like N pull jobs, each with a corresponding unique source job, would work fine given that that the source job name is encoded in zrepl zfs-abstraction list. Is my understanding correct?

Yes, spot-on.

---

Please report your experience, and maybe create a [quickstart guide variant](https://zrepl.github.io/quickstart.html#configuration-examples) for your use case. If you don't know RST, write in in markdown and make a PR, I'll format it.

**Comment by chenxiaolong** [comment]
I've submitted a PR to update the docs as suggested over at: https://github.com/zrepl/zrepl/pull/552
