### ISSUE TITLE
Prometheus metric to track daemon start time

### ISSUE THREAD

**Issue by lapo-luchini** [zrepl/zrepl#553]
In order to track upgrades/deploys (and the seldom unexpected restart) I'd like to add a "time of startup" (constant) metric.

I'd do a PR if you think it would be nice for everyone to have, I have two ideas in mind:

Right now:
```
zrepl_version_daemon{raw="v0.5.0-rc1",version_info="zrepl (…)"} 1
```

Option A (changes existing metric content, but should change nothing substantial for anyone, as current value had no meaning):
```
zrepl_version_daemon{raw="v0.5.0-rc1",version_info="zrepl (…)"} 1.6412323377629526e+09
```

Option B (add specific metric with specific value):
```
zrepl_version_daemon{raw="v0.5.0-rc1",version_info="zrepl (…)"} 1
zrepl_start_time 1.6412323377629526e+09
```

**Comment by problame** [comment]
I think `Option A`, plus renaming the metric to `zrepl_uptime` is fine.
We don't provide a stability guarantee for the Prometheus metrics.
You'll have to update the Grafana dashboard as part of the PR, though :)

**Comment by lapo-luchini** [comment]
Commit 67a1bbd98009b4bbcdc76ac5412aaafaaa076597 is just the bare minimum change to implement this and keep the Grafana dashboard identical as before.

But on the Grafana side it could make sense to make it retro-compatible, maybe, with a query like this? (or given the "no stability guarantee" you think this is unneeded?)
```PromQL
sgn(zrepl_uptime{job='$prom_job_name'}) or zrepl_daemon_version{job='$prom_job_name'}
```

And to improve it, adding a "uptime" panel like this:
```JSON
{"id":52,"gridPos":{"x":0,"y":0,"w":12,"h":8},"type":"stat","title":"Uptime","targets":[{"expr":"time() - zrepl_uptime{job=''}","legendFormat":"","interval":"","exemplar":false,"refId":"A","datasource":{"type":"prometheus","uid":"yPIW6BjGz"},"instant":true}],"options":{"reduceOptions":{"values":false,"calcs":["lastNotNull"],"fields":""},"orientation":"auto","textMode":"auto","colorMode":"value","graphMode":"area","justifyMode":"auto"},"fieldConfig":{"defaults":{"thresholds":{"mode":"absolute","steps":[{"color":"text","value":null}]},"mappings":[],"color":{"mode":"thresholds"},"unit":"s"},"overrides":[]},"pluginVersion":"8.3.3","datasource":null}
```
