### ISSUE TITLE
Include possibility for cron snapshotting

### ISSUE THREAD

**Issue by khenderick** [zrepl/zrepl#554]
Currently only `manual` and `periodic` are supported in the `snapshotting` > `type` section. I think it might make sense to for example introduce the type `cron`. In a new `cron` key, a user could configure something like `0 10 * * *` to take a snapshot every day at 10:00, and afterwards e.g. replicate it to another node.

Example:
```
jobs:
- type: push
  filesystems: {
    "<": true,
    "tmp": false
  }
  snapshotting:
    type: cron
    cron: 0 10 * * *
    prefix: zrepl_
    hooks: ...
```

The use case for which I would like to use this is to use a hook to take a backup from a non-zfs machine and download it to a local dataset. After the hook completes, the dataset is snapshotted and replicated. I want this to run on a specific time to make sure the backup has minimal impact on the non-zfs machine.

This ticket is similar to #397 but is not focused on replication only

**Comment by problame** [comment]
Thanks for opening this issue.
I think it's a good issue to get started with zrepl development.
Would you like to draw attention to this [in the discussion for zrepl 0.6](https://github.com/zrepl/zrepl/discussions/547)?

**Comment by problame** [comment]
I'm working on this
