### ISSUE TITLE
Send multiple snapshots together when they are very small

### ISSUE THREAD

**Issue by lapo-luchini** [zrepl/zrepl#555]
I have some servers which see little changes, but still create lots of very small snapshots and sending them takes up some considerable time. My first idea about it is that if I have in the plan detected a filesystem with 50 snapshots under 1MiB (or a configurable size?) each, to send them in batches (a single `zfs send -RI` should cover that, right?) and to take the accessory time cost only once every few snapshots.

Example given:
![image](https://user-images.githubusercontent.com/420454/148704126-6bf68701-9c77-4499-9961-8667b3a7c042.png)

**Comment by problame** [comment]
Use of `-R` or `-I` has been requested in the past.
The problem with these is that, down the road, features like [filtering which snapshots should be replicated](https://github.com/zrepl/zrepl/pull/459) will not be possible. Of course, it could be treated as an optimization for when no snapshot filtering is configured, but I'd rather build the snapshot filtering functionality first.

We first need some data to nail down where the wall clock time is spent.
My suspicion is that the main cost is the management of [zrepl's ZFS abstractions, i.e., replication cursor bookmarks and step holds](https://zrepl.github.io/configuration/overview.html#zfs-abstractions-managed-by-zrepl).

We have the [zrepl activity tracing infrastructure](https://github.com/zrepl/zrepl/blob/7d10a71cc0e80be813aeeea79525440ead744fd7/daemon/logging/trace/trace.go#L3) for this.
Please read through the block comment and capture an activity trace on the sender during a replication run.
Then feed it into the Chrome UI (`chrome://tracing`) and browse around.
Or send me the trace via e-mail, and I will take a look.

**Comment by problame** [comment]
(Also, parallel replication might help with throughput if you have many datasets).

**Comment by lapo-luchini** [comment]
> (Also, parallel replication might help with throughput if you have many datasets).

I have 10+ server replicating to a single disaster recovery node, I tried higher parallelism but I think that creates a bottleneck receiver-side.

I'll try activity tracing as soon as possible. :)

**Comment by problame** [comment]
In any way, I don't think zrepl will ever support using the -R or -I flag. 
Regarding -R, the recent addition of `-X` upstream allows excluding child datasets.

If `zfs send` will  support`-i`'s at some point, we can re-open this discussion.
