### ISSUE TITLE
FreeBSD / TrueNAS version 0.5

### ISSUE THREAD

**Issue by gador** [zrepl/zrepl#565]
Hello,

I upgraded my zrepl version on my main ubuntu maschine 
```
client: zrepl version=v0.5.0 go=go1.17.6 GOOS=linux GOARCH=amd64 Compiler=gc
server: zrepl version=v0.5.0 go=go1.17.6 GOOS=linux GOARCH=amd64 Compiler=gc
```

but it fails to sync to my TrueNAS backup system, due to its version being 0.4.

[The official port site is still using 0.4](freshports.org/sysutils/zrepl/). Is there a way to upgrade? Or is a release upgrade to 0.5 on the FreeBSD port side in the making?

Thanks for your work!

**Comment by problame** [comment]
> The official port site is still using 0.4. Is there a way to upgrade?

The official binary release from GitHub should work as a drop-in replacement for the binary installed by the port.

I think someone already opened a Bug in FreeBSD Bugzilla.
