### ISSUE TITLE
Feature Request: Implement (option) zfs-check like feature

### ISSUE THREAD

**Issue by gdevenyi** [zrepl/zrepl#584]
Given certain send/receive bugs in zfs, a tool exists to validate files in snapshots ( https://github.com/psy0rz/zfs_autobackup/wiki/zfs-check ) it might be worthwhile to implement such a feature to validate snapshots and send/recv.

**Comment by problame** [comment]
Have you used that tool? I find that wiki page a little confusing. Seems to me like an `rsync` dry run that compares the `.snapshot` of sender and receiver would do the job just fine?

**Comment by gdevenyi** [comment]
I haven't used it yet, I was waiting on the zfs-autoverify implementation (or another automated one)

You're right the original conception was an rsync warpper, https://github.com/psy0rz/zfs_autobackup/issues/110 I don't know why this was implemented instead, you'll have to ask the author.
