### ISSUE TITLE
zrepl status off-by-one counting error?

### ISSUE THREAD

**Issue by gdevenyi** [zrepl/zrepl#589]
Following up on #588 

I have a status lines like this:
` data/admin      DONE (step 2/1, 624 B/624 B)`

And my intuition is `step 2/1` is over-counting.

**Comment by ahjohannessen** [comment]
Had me wondering too, looking at that today.

**Comment by problame** [comment]
The culprit is probably

https://github.com/zrepl/zrepl/blob/b00b61e9677209790ec9a018036e24b8ae336d52/client/status/viewmodel/render.go#L230-L239

We want the `+ 1` only to happen while we're not done, because, if we're done, `.CurrentStep == len(rep.Steps)`

Will fix it.
