### ISSUE TITLE
wrong documentation

### ISSUE THREAD

**Issue by colttt** [zrepl/zrepl#609]
Hello,

I found some issues in the Documentation:
https://zrepl.github.io/usage.html#cli-overview said there is a `zrepl status -raw` but it doesn't exist, it should be `zrepl status --mode raw`. 

https://zrepl.github.io/configuration/overview.html#limitations the issue which is mentioned here is already solved.

Also, the key `keep_sender`, `keep_receiver`, and `listen_freebind` are not documented.

**Comment by problame** [comment]
Thanks for this bug report. The first to items are valid, and I'll address them. 

Regarding

> Also, the key keep_sender, keep_receiver, and listen_freebind are not documented.

These *are* documented, in the Pruning and TCP Transport sections, respectively.
Where else would you have expected them to be documented?
