### ISSUE TITLE
no common snapshot or suitable bookmark between sender and receiver resolution

### ISSUE THREAD

**Issue by LennyPenny** [zrepl/zrepl#627]
Hey, 
I recently had something like a data loss situation where my sender was completely lost. I restored from the receiver onto a new pool and it worked just fine. Awesome!

Now I want to start replicating to my receiver from the new pool again. However, I'm getting the error that `no common snapshot or suitable bookmark between sender and receiver`. This makes sense (I guess) as my receiver obviously only has snapshots from before the old pool died and my new pool only has snapshots from since I managed to restore it. 

What is the best way to deal with this situation? It would suck but do I need to just delete all data on the receiver so it can all start "fresh"? Or is there a way I can resolve this while being able to reuse the snapshots that are still on the receiver. 

BTW this is all using `encrypted = true`.

**Comment by problame** [comment]
> my new pool only has snapshots from since I managed to restore it.

How did you do the restore? If you want zrepl to resume replication after restore, the restore needs to be done using snapshots that are present on the backup.

> What is the best way to deal with this situation? It would suck but do I need to just delete all data on the receiver so it can all start "fresh"?

That would work, but you are without backup for a brief time. If the backup host has enough space, you could move the old datasets away using `zfs rename` (just rename whatever your current `root_fs` is). 

> Or is there a way I can resolve this while being able to reuse the snapshots that are still on the receiver.

See my first follow-up question about how you did the restore.

**Comment by LennyPenny** [comment]
> How did you do the restore?

`sudo zfs send -R oldtank/enc@zrepl_20220801_181541_000 | pv | sudo zfs receive tank/enc`
