### ISSUE TITLE
Possible to get an ARMv6 build?

### ISSUE THREAD

**Issue by jackmurray** [zrepl/zrepl#637]
I've got ZFS running on a raspberry pi 1b with an ARMv6 CPU - it runs pretty much fine, if a bit slow. I tried to install zrepl from the deb package but the binary there is built for ARMv7 and so can't execute. I was able to build zrepl manually (`make GOOS=linux     GOARCH=arm     GOARM=6`) and the resulting binary does execute on the pi.

What I'm not sure about however, is if it's possible to have a single deb package containing both binaries (or if it is, if that's actually advisable)? If not, would you be open to the possibility of having a separate package name containing the ARMv6 binary for those of us trying to squeeze the most out of old hardware?

**Comment by problame** [comment]
So, `dpkg —print-architecture` prints the same on your Pi 1 and newer ones?

How do other third party Apt repos handle this? Please provide examples

**Comment by jackmurray** [comment]
Yeah it's `armhf` on both a pi 1b and 2b (which reports `armv7l` from `uname -m`). I'm not really sure how other repos handle this - I'm not currently using any.

**Comment by problame** [comment]
Ok. Let me know if you find an example that we can copy.
I'm not willing to invest a huge amount of my time into this, but if there is a way, I can integrate it into the workflow.  
But we first need to understand what the right approach is.

**Comment by jackmurray** [comment]
So it sounds like the solution that Raspbian uses at least is to just build for the most common denominator i.e. armv6l: https://wiki.debian.org/RaspberryPi#Debian_and_Raspbian. So the _easiest_ thing to do here I think is to set `GOARM=6` instead of 7 and that should be runnable on all CPUs. Another solution would be to publish the `GOARM=6` build as a separate package name e.g. `zrepl-armv6l` so that you can specifically install that on a system that can't run armv7l.

All that said though, since nobody else has asked for this, it seems like a fairly big change to implement just for me, especially since I've already compiled myself a working binary. The best thing to do here might just be to close this issue; at least this information will be searchable if anyone else runs into this in future (which, given that armv6l is basically dead, is unlikely).

**Comment by problame** [comment]
Thanks for digging into this. I'll close the issue for now. To future readers: if you need a repo, please leave a comment here.
