### ISSUE TITLE
Local replication not possible due to various issues

### ISSUE THREAD

**Issue by se-jaeger** [zrepl/zrepl#670]
Hi, thanks for this awesome project!

Since a couple of weeks I'm trying to use `zrepl` to snapshot and backup my homeserver. However, there are various problems I'm facing.

###  **My use-case:**
- regularly snapshot my 2 local pools (`datapool` and `rpool`)
- local backups (replications) to external disk (both pools)
- using multiple external disks (so I can store them on different physical places)

### **Setup:**
- `snap` job using default `zrepl_` prefix
  - pruning keeps the following
    - `grid` with regex `"^zrepl_.*"`
    - `grid` with regex `"^backup_.*"`
    - negated `regex` for `"^(zrepl|backup)_.*"`
- `push` job with local connection
  - encrypted `send` with `send_properties` and `backup_properties` set `true`
  - `conflict_resolution` uses `initial_replication: all`
  - `replication.protection` uses `initial` and `incremental` as `guarantee_nothing`. Necessary to work with multiple disk properly (is this true?)
  - `snapshotting` creates daily `backup_` prefixed snapshots
  - `keep_sender` pruning does nothing and `keep_receiver` keeps 5 years of daily backups with `regex: "^backup_.*"`
- `sink` job
  - inherits some `properties` (followed documentation)
  - sets `placeholder.encryption: off` (followed documentation)

### **Problems/Issues I'm facing:**

1. For both pools I get almost always the following errors after waking up the `snap` job:
    ```
    Progress: [>--------------------------------------------------] 145.6 KiB / 301.5 MiB @ 0 B/s
    datapool                                    STEP-ERROR (step 1/67, 24.8 KiB/337.0 KiB) server error: zfs exited with error: signal: aborted (core dumped)
      stderr:
      nvlist_lookup_string(nvl, name, &rv) == 0 (0x2 == 0)
      ASSERT at ../../module/nvpair/fnvpair.c:403:fnvlist_lookup_string()
    ```

2. From time to time, I get the following output for at the beginning some and later for all of the datasets:
    ```
    datapool/A                        PLANNING-ERROR (step 0/0, 0 B/0 B) the receiver's latest snapshot is not present on sender:
    last common: @zrepl_2023-01-11_23:48:24
    sender-only:
      @zrepl_2023-01-12_00:03:24
      @zrepl_2023-01-12_00:18:25
    (... discarded some more ...)
      @zrepl_2023-01-12_08:18:30
    receiver-only:
      @backup_2023-01-12_00:00:02
    ```
    However, if I'm manually check the snapshots the list is much longer. For both sender and receiver. Strikingly, the sender only lists `@zrepl_` snapshots and ignores the `@backup_` snapshots. This is not what I expect.
    
3. Lastly for pruning sender and receiver I get the following error:
    `ERROR: replication cursor bookmark does not exist (one successful replication is required before pruning works)`
    This is probably due to the `guarantee_nothing` setting, which tells `zrepl` to not handle any `zfs-abstraction`s.

To be honest, I'm not sure whether my setup does not make sense or I'm actually facing some issues/maybe bugs. Any help is much appreciated.

Thank's in advance!

**Comment by se-jaeger** [comment]
Switch to using 2 backup disks `backupool_1` and `backupool_2` and duplicate the job setup accordingly. It works but is kind sub-optimal. This solves Issue 2 and 3. However, issue 1 remains.

**Comment by problame** [comment]
Thanks for this write-up, let's go through it one by one.

---

```  
  nvlist_lookup_string(nvl, name, &rv) == 0 (0x2 == 0)
  ASSERT at ../../module/nvpair/fnvpair.c:403:fnvlist_lookup_string()
```

That is a ZFS bug.
Turn on coredumps on your system and open an issue at https://github.com/openzfs/zfs .

I'd guess the command that failed with this assert was a `zfs send` command.
To get the exact args, enable zrepl debug logging - it logs each zfs command invocation.

---

Regarding the other items you mentioned: I have trouble understanding your goal here.
Please confirm or correct it.

You have a prod system, and you have two external HDDs.
You have three zpools: prod, hdd1, hdd2.

You want to be able to plug in _either_ hdd1 _or_ hdd2 into the prod system, and have zrepl replicate some prod datasets to the plugged-in HDD.
When you later plug in the other HDD, same thing: zrepl shall replicate the same set of prod datasets to that HDD.

Correct?
If so, I recommend:
- A single `snap` job on `prod` that's responsible for snapshot management
- Per HDD: a pair of `push` and `sink` jobs.
  - No need to lower `replication.protection`.
- All jobs must have unique names.

The reason why you need separate `push` jobs per HDD: zrepl needs to maintain a replication cursor bookmark per receiver. The replication cursor bookmark exists to avoid the `the receiver's latest snapshot is not present on sender` problem.

> The replication cursor bookmark and last-received-hold are managed by zrepl to ensure that future replications can always be done incrementally. The replication cursor is a send-side bookmark of the most recent successfully replicated snapshot, and the last-received-hold is a hold of that snapshot on the receiving side. Both are moved atomically after the receiving side has confirmed that a replication step is complete.

( https://zrepl.github.io/configuration/overview.html#zfs-abstractions-managed-by-zrepl )

**Comment by se-jaeger** [comment]
Hi, thanks for commenting on this.

The setup you described (prod, hdd1, hdd2) is the one I'm currently using. See my comment above. It works as expected! My aim was to not duplicate the `push` and `sink` job but it looks like that's the way to go here. Do you think it's worth to document this use case (can file an PR then)? Maybe as part of: https://zrepl.github.io/quickstart/backup_to_external_disk.html

If I find some time, I will debug the ZFS bug and create an issue there. 👍🏼 

Thanks!

**Comment by problame** [comment]
Sorry for the late reply.
Yes, I think it's valuable to document this use case, as an addendum to the existing `backup_to_external_disk` page.

Looking forward to PRs!

Also, if you open a ZFS issue, either mention this one in there, or link to it from here.
It'll help others who are hitting the same bug.

Meanwhile, I'll mark this issue as closed.
