### ISSUE TITLE
Replication doesn't work because connect times out

### ISSUE THREAD

**Issue by MoritzFago** [zrepl/zrepl#75]
I configured datacarrier according to the tutorial, and I patched zfs/zfs.go so that the line `const FORBIDDEN = "@#|<>*"` doesn't contain the space char.

The sync doesn't work

datacarrier log:
```
Jun 18 23:29:54 datacarrier zrepl[97397]: [INFO][Defiant Full][main.run]: connecting
Jun 18 23:30:04 datacarrier zrepl[97397]: [ERRO][Defiant Full][main.run]: error connecting err="dial_timeout of 10s exceeded"
```

the defiant log doesn't contain any enties at that time. A manual login with the specified key works an gets me the zrepl banner.

config:
```
# $FreeBSD: branches/2018Q2/sysutils/zrepl/files/zrepl.yml.sample 454572 2017-11-20 
#15:40:31Z woodsb02 $
#
# zrepl main configuration file.
# For documentation, refer to https://zrepl.github.io/
#
global:
  logging:
    - outlet: "stdout"
      level:  "debug"
      format: "human"

# Add "jobs:" section(s) here for your specific use cases.
jobs:

- name: Defiant Full
  # expect remote to connect via ssh+stdinserver with fullbackup_prod1 as client_identity
  type: pull
  connect:
    type: ssh+stdinserver # see global.serve.stdinserver for explanation
    host: defiant.fago.me
    port: 22
    user: root
    client_identity: server.fago.me
    identity_file: /usr/local/etc/zrepl/ssh/identity
  interval: 15m
  # snapshot these filesystems every 10m with zrepl_ as prefix
  mapping: {
    "<": "Library/Backups/defiant.fago.me/NX-74205",
#    "zroot/var/tmp": "!", #don't backup /tmp
  }
  initial_repl_policy: most_recent
  snapshot_prefix: zrepl_

  # keep 1 hour of snapshots (6 at 10m interval)
  # and  one day of bookmarks in case pull doesn't work (link down, etc)
  # => keep_bookmarks = 24h / interval = 24h / 10m = 144
  prune:
    policy: grid
    grid: 1x1h(keep=all) | 24x1h | 35x1d | 6x30d
```

defiant config:

```
# $FreeBSD: branches/2018Q2/sysutils/zrepl/files/zrepl.yml.sample 454572 2017-11-20 
#15:40:31Z woodsb02 $
#
# zrepl main configuration file.
# For documentation, refer to https://zrepl.github.io/
#
global:
  logging:
    - outlet: "stdout"
      level:  "error"
      format: "human"
    - outlet: "syslog"
      level:  "debug"
      format: "logfmt"

# Add "jobs:" section(s) here for your specific use cases.
jobs:

- name: Defiant Full
  # expect remote to connect via ssh+stdinserver with fullbackup_prod1 as client_identity
  type: source
  serve:
    type: stdinserver # see global.serve.stdinserver for explanation
    client_identity: server.fago.me

  # snapshot these filesystems every 10m with zrepl_ as prefix
  filesystems: {
    "NX-74205<": "ok",
#    "zroot/var/tmp": "!", #don't backup /tmp
  }
  snapshot_prefix: zrepl_
  interval: 15m


  # keep 1 hour of snapshots (6 at 10m interval)
  # and  one day of bookmarks in case pull doesn't work (link down, etc)
  # => keep_bookmarks = 24h / interval = 24h / 10m = 144
  prune:
    policy: grid
    grid: 1x1h(keep=all) | 24x1h
    keep_bookmarks: 97

```

**Comment by problame** [comment]
So at first, make sure that both sides are running the same version, preferrable 0.0.3 or master (with your patch applied). The change from 0.0.2 to 0.0.3 changed the RPC protocol.

Then: Do you have a problem with the general replication setup or only with filesystems with the space characters?

**Comment by MoritzFago** [comment]
> both sides are running the same version, preferrable 0.0.3 or master (with your patch applied)

They are both running the same binary from master with the patch as specified in my PR #79 (minus the comment, plus the removal of the tab char).
Versions:
```
Defiant:     zrepl version=0.0.3-11-gc7f0f77-dirty GOOS=freebsd GOARCH=amd64 Compiler=gc
Datacarrier: zrepl version=0.0.3-11-gc7f0f77-dirty GOOS=freebsd GOARCH=amd64 Compiler=gc
```

> Do you have a problem with the general replication setup or only with filesystems with the space characters?

Neither the source (defiant) dataset nor the destination dataset contains any spaces in their names. The replication did work erratically a few days ago, but now, after i cleaned up on the destination, it doesn't anymore. I cleaned up because the sync stoped working and the source had deleted the bookmarks needed to sync, so i removed the destination dataset and restarted.

Currently the destination gives this log output:
Datacarrier:
```
Jun 19 19:39:18 datacarrier zrepl[45988]: [INFO][Defiant Full][main.run]: connecting
Jun 19 19:39:19 datacarrier zrepl[45988]: [ERRO][Defiant Full][main.run]: error connecting err="proxy error, check remote configuration"
```

No corresponding log entries on the source side.

**Comment by problame** [comment]
I think you are encountering the problem found in https://github.com/zrepl/zrepl/issues/77#issuecomment-398418728 : when you manually try to connect via SSH, you cause an error which makes the `serve`-Task on the `source` side to close the UNIX socket in `/var/run/zrepl/stdinserver/CLIENT_ID` to which the `zrepl stdinserver CLIENT_ID` connects to.

This is a bug and will be fixed (the socket will stay open).

Until then, please retry without connecting to the source-side manually, i.e.,

* source: restart zrepl daemon
* pull: restart zrepl daemon
* only check the logs

Does that help?

**Comment by MoritzFago** [comment]
It doesn't.
Logs (since restart):
datacarrier (pull):

```
Jun 21 23:52:27 datacarrier zrepl[20429]: [INFO]: zrepl version=0.0.3-11-gc7f0f77-dirty GOOS=freebsd GOARCH=amd64 Compiler=gc
Jun 21 23:52:27 datacarrier zrepl[20429]: [DEBG]: starting daemon
Jun 21 23:52:27 datacarrier zrepl[20429]: [INFO]: starting jobs from config
Jun 21 23:52:27 datacarrier zrepl[20429]: [INFO][Defiant Full]: starting
Jun 21 23:52:27 datacarrier zrepl[20429]: [INFO][control]: starting
Jun 21 23:52:27 datacarrier zrepl[20429]: [INFO][Defiant Full][main.run]: connecting
Jun 21 23:52:37 datacarrier zrepl[20429]: [ERRO][Defiant Full][main.run]: error connecting err="dial_timeout of 10s exceeded"
```

defiant (source):
```
Jun 21 23:51:00 defiant zrepl[63152]: msg="zrepl version=0.0.3-11-gc7f0f77-dirty GOOS=freebsd GOARCH=amd64 Compiler=gc"
Jun 21 23:51:00 defiant zrepl[63152]: msg="starting jobs from config"
Jun 21 23:51:00 defiant zrepl[63152]: job="Defiant Full" msg=starting
Jun 21 23:51:00 defiant zrepl[63152]: job=control msg=starting
Jun 21 23:51:02 defiant zrepl[63152]: job="Defiant Full" task=autosnap.sync_up.wait_sync_point msg="wait for sync point" sync_point="Fri Jun 22 00:03:04 2018"
```

**Comment by MoritzFago** [comment]
Correction, later that night it started working:
datacarrier: (pull)
```
Jun 22 00:07:27 datacarrier zrepl[20429]: [INFO][Defiant Full][main.run]: connecting
Jun 22 00:07:29 datacarrier zrepl[20429]: [INFO][Defiant Full][main.run.pull.run]: request remote filesystem list
Jun 22 00:07:29 datacarrier zrepl[20429]: [DEBG][Defiant Full][main.run.pull.run]: map remote filesystems to local paths and determine order for per-filesystem sync
```

then it got the remote fs list, I got an error and i reconfigured it and now it works. Until my provider reconnected me (german specialty, ISPs reconnect you every 24h). I will monitor how zrepl handles that. I'll close that for now.

**Comment by MoritzFago** [comment]
Reopening because I don't understand why there should be a `dial_timeout of 10s exceeded`, that fixes itself in the meantime.
