### ISSUE TITLE
stdinserver is not restarted after timeout?

### ISSUE THREAD

**Issue by shivno** [zrepl/zrepl#77]
hi,
first, thanks for zrepl, it is awesome.

i have this problem:
did my setup after the tutorial, tested manual ssh from backup-srv if stdinserver is responding, closed the ssh session with ctrl+c.
afterwards zrepl on app-srv shows this: 
`SSHCON_PROXY_ERROR2018/06/19 11:17:46 error: dial unix /var/run/zrepl/stdinserver/isenu-backup1: connect: no such file or directory`
and i think it never recovers. maybe the stdinserver could be supervised? maybe i did something wrong.

thanks!

**Comment by problame** [comment]
> maybe the stdinserver could be supervised?
`zrepl stdinserver CLIENT_IDENTITY` is merely a stub process that is necessary to establish the connection from the client to the zrepl daemon.
stdinserver connects to a unix socket created by zrepl daemon in `/var/run/zrepl/stdinserver/CLIENT_IDENTITY`, forwards the connection from the client, and then waits until it is signaled by the client to exit.
As such, it doesn't need supervision.

However, zrepl daemon must be running on both sides.

zrepl daemon does not create the /var/run/zrepl/stdinserver directory.
On FreeBSD, this should be handled by the `/usr/local/etc/rc.d/zrepl`, see https://svnweb.freebsd.org/ports/head/sysutils/zrepl/files/zrepl.in?view=markup#l57

Are you running the daemon with the rc script or manually from the command line?
If so, maybe try running it from rc script once so the `install` commands get run and create the runtime dirs.

**Comment by shivno** [comment]
on freebsd, 0.3 with the rc script, right, runs on both sides. everything works ok, can you reproduce this?

- set up ssh on backup-srv with command=
- run daemon on app-srv
- socket is there
- connect with ssh manually from backup-srv
- socket is gone

**Comment by problame** [comment]
Uh, so if I understand you correctly, it works if you don't do the ssh test-connect?

**Comment by shivno** [comment]
right, i guess go closes the socket if it is being exited uncleanly or so. probably is reproducible locally somehow by starting zrepl stdinserver backupservername, then just kill the shell or similar.

**Comment by shivno** [comment]
right, it logs that. but the socket should stay alive imho, otherwise no further backups can be transferred. i dont know go so i dont know what is wrong.

**Comment by problame** [comment]
Right, so I guess we're lucky that if users follow the tutorial 1:1, they won't run into this (because the zrepl daemon is not yet running on the other side)

Will find a fix for 0.0.4. Thanks for reporting, patches are always welcome ;)

**Comment by shivno** [comment]
this is actually a severe issue, i just discovered that backups werent transferred for 2 days because of this issue (no logcheck yet on that server). so an addition to the docs exclaimer would be good imho with reference to this ticket or something. otherwise it works great!
