### ISSUE TITLE
File 'repomd.xml' from repository 'zrepl' is unsigned.

### ISSUE THREAD

**Issue by findesgh** [zrepl/zrepl#776]
When  I add and refresh the `zrepl`-rpm-repo on openSUSE Tumbleweed or Leap, it complains about the master index file being unsigned:

```text
Warning: File 'repomd.xml' from repository 'zrepl' is unsigned.

    Note: Signing data enables the recipient to verify that no modifications occurred after the data
    were signed. Accepting data with no, wrong or unknown signature can lead to a corrupted system
    and in extreme cases even to a system compromise.

    Note: File 'repomd.xml' is the repositories master index file. It ensures the integrity of the
    whole repo.

    Warning: We can't verify that no one meddled with this file, so it might not be trustworthy
    anymore! You should not continue unless you know it's safe.
```

This does not happen on Fedora. I don't know enough about `dnf` or `zypper` to understand what the difference/cause is. Surely this is not a check which `dnf` simply skips?

To reproduce:
```bash
podman run -it opensuse/tumbleweed /bin/bash
```
```bash
cat > /etc/zypp/repos.d/zrepl.repo <<EOF
[zrepl]
name = zrepl
baseurl = https://zrepl.cschwarz.com/rpm/repo
gpgkey = https://zrepl.cschwarz.com/rpm/rpm-key.asc
EOF
```
```bash
zypper ref
```

**Comment by problame** [comment]
Hi, yeah, makes sense to sign the `repomd.xml`.

Can you please try the staging repo? I made the change there

```
cat > /etc/zypp/repos.d/zrepl.repo <<EOF
[zrepl]
name = zrepl
baseurl = https://zrepl.cschwarz.com/rpm-staging/repo
gpgkey = https://zrepl.cschwarz.com/rpm/rpm-key.asc
EOF
```

Also, I would appreciate [a docs PR](https://github.com/zrepl/zrepl/) that adds instructions for SUSE-based distros. The RPMs I build appear to work but the paths for the repo spec appears to be different (?)

**Comment by problame** [comment]
(And apologies for the long delay)

**Comment by findesgh** [comment]
Tested the staging repo on a couple of systems (Fedoras and Tumbleweeds) and did not encounter any problems.

The RPMs seem to work, yes. I have not yet used zrepl "productively" (if that term makes any sense in a home-lab-setting :joy:), but I've had it running for a couple of weeks in a test setup and did not encounter problems. The plan is to go productive at some point, if I find the time.

Will look into a docs PR. The only difference really is the path.

**Comment by problame** [comment]
I just asked you to test the staging rep report because that is where this signed repomd.xml was deployed. in all other aspects, it should be bit identical to the production repo. Thanks for testing, I will deploy this to production in the future and then close this issue..

**Comment by problame** [comment]
It's still make sense to make the docs PR because right now there is no search result for OpenSUSE in the zrepl docs.

Maybe you can extend the current shell snippet to check lsb_release and use the right path based on that

**Comment by problame** [comment]
Deployed the signed repomd.xml to production, it will happen automatically going forward ✅
