### ISSUE TITLE
`read-only file system` error when zrepl tries to create filesystems

### ISSUE THREAD

**Issue by problame** [zrepl/zrepl#811]
oddly this prevents basic replication without any hooks for me, since zrepl tries to create filesystems, which then fails with Read-only file system

_Originally posted by @aep in https://github.com/zrepl/zrepl/issues/258#issuecomment-2254452637_

**Comment by problame** [comment]
@aep can you provide some details? I imagine the problem is happening on the receiving side because your `root_ds` doesn't have `mountpoint=none` set?

**Comment by aep** [comment]
> @aep can you provide some details? I imagine the problem is happening on the receiving side because your `root_ds` doesn't have `mountpoint=none` set?

yes, i believe thats the reason.
in combination with ```ProtectSystem=strict```

i'm not sure what the correct approach for this is. the Protect thing makes sense i think?

**Comment by problame** [comment]
As a rule of thumb, it's better to use mountpoint=none on the receiving side to prevent the receiving side filesystem from getting dirtied by the implicit mkdir that ZFS needs to do if the mountpoint directory doesn't exist in the parent dataset.

The again, I'm thinking to just remove the Protect... statements from the systemd unit.

**Comment by aep** [comment]
> The again, I'm thinking to just remove the Protect... statements from the systemd unit.

that's the difficulty here. i would not have noticed it without it.  i clearly dont want to mount the backups.
maybe  zrepl could just print a more useful error message?

**Comment by problame** [comment]
https://github.com/zrepl/zrepl/pull/831
