### ISSUE TITLE
Zrepl Security Concern and also how to do with the method said in point 2

### ISSUE THREAD

**Issue by basil-thgnet** [zrepl/zrepl#812]
Hi,

We have 2 almalinux servers (master and slave), and we wanted to replicate the snapshots created in master to slave. The methods we have followed are:

1. Used master in source tls  connect mode and slave in pull tls connect mode  >> the replications works fine

But for better security, we just need to manually created snapshots in master server using zfs command, and without zrepl service running in master. We just need to run the zrepl service in slave server in pull mode.

2. So, how can we achieve snapshot getting pulled from source server with no zrepl service running on master server?

3. Also, if we connect master in source tls  connect mode and slave in pull tls connect mode, how can we protect the snapshots in slave server if hacker access the server ? as the hacker can edit the zrepl yml file to prune the snapshots in the slave server.

so, could you let me know how we can protect the snapshots in backup server ?

Awaiting your response.

Thank you.

**Comment by InsanePrawn** [comment]
1. Uhuh?
2. You can't.
3. If your zrepl config is world-writeable, that's your problem. if an attacker is root on your machine, nobody can protect your snapshots. If the backup target is your problem, use push mode.


We can't design your security concept for you.
