### ISSUE TITLE
Request apt repository support for Linux Mint

### ISSUE THREAD

**Issue by wallart1** [zrepl/zrepl#816]
I have a Linux Mint 21.3 system (VM based on Ubuntu 22.04) that I want to use to follow along with development.
```
dan@foghorn:~$ echo "$(lsb_release -i -s | tr '[:upper:]' '[:lower:]') $(lsb_release -c -s | tr '[:upper:]' '[:lower:]')"
linuxmint virginia
```
I've tried using the instruction for Ubuntu, but it fails while trying to find any of the http resources. 

Would you mind updating your repository to include "linuxmint virginia" or update the Ubuntu apt instructions?

Much appreciated.

**Comment by gdevenyi** [comment]
Mint is just ubuntu.

You need to look up the codename maps between mint and ubuntu and do an appropriate substitution for the ubuntu codename.

**Comment by problame** [comment]
Yeah, I'm not interested in maintaining repos for more apt distros. Using the matching Ubuntu repos should work.
