### ISSUE TITLE
receiver pruning issues after pool move on sink

### ISSUE THREAD

**Issue by mdtancsa** [zrepl/zrepl#853]
On my primary sink server, I had to rebuild the pool to get rid of the special devices as well as just retire the old hard drives.  The original pool was 
zbackup2/sink/<all the clients that would push datasets here>
and the new was 
zbackup2a/zrepl/sink2<all the clients what would push datasets here>

I added a new sink job on the server listening on a different port with the root file system as zbackup2a/zrepl/sink2
- name: ten_g0-3b
  type: sink
  serve:
     type: tls
     listen: "192.168.x.x:1811"
     ca: ...
     cert: ...
     key: ...
     client_cns:
       - "example.sentex.ca"
       - "example2.sentex.ca"
  root_fs: "zbackup2a/zrepl/sink2"

One by one I would stop zrepl and the client that was doing the pushing
take a snapshot like zfs snapshot -r zbackup2/sink/example.sentex.ca@0
zfs send -RV zbackup2/sink/example.sentex.ca@0 | zfs recv zbackup2a/zrepl/sink2/example.sentex.ca

I would then zfs destroy -r zbackup2a/zrepl/sink2/example.sentex.ca@0

and then change the client's port (example.sentex.ca) to the new port 1811 and start up zrepl. It seemed to all work. The new diff snapshot would be sent and I would move onto the next server. All seemed good.  

The clients are all basically this config, some with a shorter some with a longer retention period
jobs:
- name: me_to_backup_server
  type: push
  connect:
    type: tls
    address: "192.168.x.x:1811"
    ca: /usr/local/etc/zrepl/certs/ca.crt
    cert: /usr/local/etc/zrepl/certs/example.sentex.ca.crt
    key:  /usr/local/etc/zrepl/certs/example.sentex.ca.key
    server_cn: "my_backup_server.sentex.ca"
  filesystems: {
    "zroot<": true
  }
  send:
    compressed: true
  snapshotting:
    type: periodic
    prefix: zrepl_
    interval: 30m
  pruning:
    keep_sender:
    - type: not_replicated
    - type: last_n
      count: 10
    - type: regex
      regex: "daily*"
    keep_receiver:
    - type: grid
      grid: 1x1h(keep=all) | 72x1h | 32x1d | 4x30d
      regex: "^zrepl_.*"
      
      

However, I noticed today, None of the longer term backup snapshots are there. They had all been deleted.  I had a lot of 1hr snaps, but nothing more than a few days.  All the other clients were the same way.

eg. 
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241122_105832_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241122_145832_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241122_155832_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241122_165832_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241122_175832_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241122_195832_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241122_205832_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241122_215833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241122_232832_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241123_002832_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241123_012832_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241123_022832_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241123_032833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241123_042833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241123_055833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241123_082833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241123_092833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241123_102833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241123_112833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241123_122833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241123_132833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241123_142833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241123_152833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241123_162833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241123_172833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241123_182833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241123_192833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241123_202833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241123_212833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241123_222833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241123_232833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241124_002833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241124_012833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241124_022833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241124_032833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241124_042833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241124_052833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241124_062833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241124_072833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241124_082833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241124_092833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241124_102833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241124_112833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241124_122833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241124_132833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241124_142833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241124_152833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241124_162833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241124_172833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241124_182833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241124_192833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241124_202833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241124_212833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241124_232833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241125_002834_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241125_015834_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241125_032833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241125_042833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241125_052833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241125_062833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241125_082833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241125_092833_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241125_102834_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241125_115834_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241125_132834_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241125_142834_000                                   0B      -      453K  -
zbackup2a/zrepl/sink/example.sentex.ca/zroot/var/tmp@zrepl_20241125_145834_000                                   0B      -      453K  -

2 things I am not sure of. What happened to the older logs ? Looking at zpool history it does seem to be zrepl deleting the datasets, but I dont understand why.  I renamed a couple of the datasets to example.sentex.ca.tmp so as to force a full send to see if this "unbreaks" things.  Anyone have any idea what might be going on ?

Its almost like the grid feature is broken ?

On the server FreeBSD 13 from Nov 12 
client: zrepl version=v0.6.1 go=go1.21.13 GOOS=freebsd GOARCH=amd64 Compiler=gc
server: zrepl version=v0.6.1 go=go1.21.13 GOOS=freebsd GOARCH=amd64 Compiler=gc

clients are anywhere from 0.6.0 to 0.6.1 (same as the server), all FreeBSD 13 or 14.

**Comment by mdtancsa** [comment]
found the issue. An errant script that didnt sanitize the input killed some of the snapshots due to the pool name change :(

**Comment by problame** [comment]
Hey @mdtancsa , so, to summarize:
* you did a low-downtime migration of the receiving side to a new pool
  * your procedure seems fine to me
* things worked initially
* an tool unrelated to zrepl deleted the snapshots

If so, I'd say we can close this issue? :)

**Comment by mdtancsa** [comment]
> Hey @mdtancsa , so, to summarize:
> 
> * you did a low-downtime migration of the receiving side to a new pool
>   
>   * your procedure seems fine to me
> * things worked initially
> * an tool unrelated to zrepl deleted the snapshots
> 
> If so, I'd say we can close this issue? :)

Add
* +1 shame points to @mdtancsa
