### ISSUE TITLE
syslog messages too long on freebsd

### ISSUE THREAD

**Issue by shivno** [zrepl/zrepl#87]
syslog message:
```
[ERRO]: outlet error outlet_type=*cmd.SyslogOutlet err="write unixgram ->/var/run/log: write: message too long"
```

config:
```
- outlet: syslog
  level: info
  format: logfmt
```

**Comment by problame** [comment]
The log messages in zrepl 0.1 will be shorter because we no longer include the semantic stack-trace in the 'task' field of the log output.
Could you try https://github.com/zrepl/zrepl/releases/tag/0.1.0-rc1 and report whether this issue is still relevant?

**Comment by shivno** [comment]
no problem, your zrepl is the best out of zfs replication sw! ill test soon when i have time for it
