### ISSUE TITLE
Mac OS support/community

### ISSUE THREAD

**Issue by JMoVS** [zrepl/zrepl#89]
Hi there,

I stumbled upon zref recently and was wondering if anybody

- either already tried running this on Mac OS (I mean it should work)
- attempted to package it and bring it into for example homebrew/macports

I'm looking into it and might start experimenting soon, just want to save double effort if it's already existing. It doesn't exist in homebrew right now but I think it first needs to be tested in Mac OS to work at all (which I will do soon ;-) ).

**Comment by problame** [comment]
zrepl 0.1 (Release candidate: https://github.com/zrepl/zrepl/releases/tag/0.1.0-rc1 ) includes a Darwin binary release, maybe this helps you get started.
I will close this issue for now, please report any bugs you encounter in separate issues.
