### ISSUE TITLE
Better explain grid prune strategy

### ISSUE THREAD

**Issue by Duffyx** [zrepl/zrepl#91]
Hello,

I think zrepl is an awesome tool if further developed. It has everything, local replication (which I am interested in), remote etc. However I fail to understand the prune strategy when using a grid.

What if I for example need to keep:
All daily snapshots for a week, all weekly snapshots for a month, all monthly snapshots for a year?
So max, 7 dailies, 4 weeklies, 12 monthlies. How would this fit in the grid style notation?

**Comment by problame** [comment]
Grid pruning is concerned with intervals and temporal resolution, not calendar days.
I have created issue #92 to keep track of that.

In general, the grid for your use case could look like this, assuming automatic snapshots at `interval=24h`: 
`7x1d | 4x7d | 12x30d`

**Comment by Duffyx** [comment]
Thanks for clearing this out! Looking forward to where zrepl is going, keep up the good work!
