### ISSUE TITLE
Local Snap&Prune job type (no replication)

### ISSUE THREAD

**Issue by Duffyx** [zrepl/zrepl#93]
Use case: use zrepl to replicate bootpool "zroot" to storagepool "storage/zroot" with local sink and push job. Pruning policy takes care of send and received snapshots on zroot and storage/zroot respectivelly. Altough, one might like to take snapshots of other datasets on the storagepool eg; storage/media.

A snapshot only job,  no replication.

Configuration could be like: 

jobs:
  - type: snap
    name: "taking snapshots of storagepool"
    filesystems: {
      "storage<": true,
      "storage/zroot": false
    }
   snapshotting:
      type: periodic
      interval: 1d
   pruning:
        - type: grid
          grid: 7x1d | 4x7d | 12x30d

**Comment by problame** [comment]
We used to have a combined local job in pre-0.1 versions.
0.1 now has the `local` [transport type](https://zrepl.github.io/configuration/transports.html#local-transport) with enables local replication: https://zrepl.github.io/configuration/jobs.html#replication-local (see example config).

**Comment by Duffyx** [comment]
I agree that we have an option and job type to take care of local replication. No issue here. So lets say I have zroot getting replicated to storage/zroot. A config using local replication only takes snapshots on the source and prunes both the source and destination, so taking snapshots on zroot, pruning on zroot and storage/zroot.

Lets say I want to take snapshots and prune them on a datasets not involved in the local replication job above, eg; storage/media,; storage/nextcloud; storage/downloads; these are not getting snapshot and pruned by the local replication job.

So a possible idea was to add a snapshot only job, that takes snapshots and prunes them but does not replicate anywhere.

Or am I not understanding you and this functionality is already available?

**Comment by problame** [comment]
No, this functionality is not available, but all the existing abstractions are there, it's really only about defining another job type.
I'll rename this issue and schedule it for a future release.

If anyone is interested in implementing it (good first issue)

* define a new job type in package `config` (search for use of config.PushJob and copy-paste)
* define a new job `SnapJob` in package `daemon/job` and hook it up in `daemon/job.FromConfig`
* implement `daemon/job.Job` for `daemon/job/.SnapJob`
  * `SnapJob.Run()` should instantiate a `snapper.Snapper` and `pruner.Pruner`

**Comment by problame** [comment]
This feature was implemented by @InsanePrawn  in #101
